### ISSUE TITLE
Need protein lengths in the final spreadsheet

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/Roary#116]
Some idea of average or min/max length of proteins in each cluster would be helpful

Even perhaps %id (amino?) level.

Torst

**Comment by tseemann** [comment]
Encountered this issue again.  Did a 300 genome study and a particular gene G was in every genome but was clustered into 6 separate clusters (clades). We couldn't tell which was which because they all had the same /product but different lengths.

**Comment by andrewjpage** [comment]
Since most genes should be the same length in a cluster would mode length be more useful than average length (as well as max/min)?
