### ISSUE TITLE
Add support for GFF files from NCBI

### ISSUE THREAD

**Issue by andrewjpage** [sanger-pathogens/Roary#120]
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.gff.gz

**Comment by tseemann** [comment]
NCBI GFF files don't include the .FASTA at the end, also the seqid (column 1) is just the NC_ number and not the full gi||ref|| ID that is in the FASTA.

**Comment by andrewjpage** [comment]
I rewrote Bio-RetrieveAssemblies (cpanm Bio::RetrieveAssemblies) so that it will download WGS and RefSeq assemblies and convert them to GFF (including the FASTA file at the end) which should make it easier to get existing data from NCBI.  It filters out dodgy stuff using RefWeak.   Theres a tweak or two I need to make to Roary first, but I hope in a day or so that you will be able to create a pan genome of all S. typhi by doing:

retrieve_assemblies -o my_files -f gff typhi
roary my_files/*.gff

**Comment by andrewjpage** [comment]
So Roary now works grand with WGS and RefSeq assemblies now. Its not everything in GenBank but it provides a vast quantity of data for people to play around with.

retrieve_assemblies -a -f gff typhi

http://sanger-pathogens.github.io/Roary/index.html#genbank_files
https://github.com/sanger-pathogens/Bio-RetrieveAssemblies

**Comment by stellareichling** [comment]
Hello
I am also trying to get Roary running with gff3 files form NCBI (annotated by PGAP). Is it possible to do to so without taking a detour over Bio-RetrieveAssemblies? 
Many thanks in advance and kind regards

**Comment by andrewjpage** [comment]
GFF3 files from NCBI usually only contain the annotation and not the nucleotide sequence. You'll need to make sure you get a file with the annotation and assembly in the same file. You can either do this by appending the assembly to the end of the GFF file (with ##FASTA as the delimiter) or you can convert from the gbff file (Genbank file with annotation and assembly) to a GFF file. Or you could use the script above.

**Comment by jotes35** [comment]
Hi @andrewjpage I tried your suggesting about appending but I still got an error message below is one such message.
2021/01/05 22:56:24 Could not extract any protein sequences from fixed_input_files/pMUM001.gff. Does the file contain the assembly as well as the annotation?
 Attached is the gff 
[pMUM001.gff.txt](https://github.com/sanger-pathogens/Roary/files/5773033/pMUM001.gff.txt)

**Comment by Detective-moneill** [comment]
Hi @andrewjpage I tried to install the cpanm Bio::RetrieveAssemblies, but got an error:
! Finding Bio::RetrieveAssemblies on cpanmetadb failed.
! Finding Bio::RetrieveAssemblies () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution Bio::RetrieveAssemblies

https://github.com/sanger-pathogens/Bio-RetrieveAssemblies also does not exist. 
Has this been moved? Thanks in advance!
