### ISSUE TITLE
You're missing some Perl dependancies

### ISSUE THREAD

**Issue by mscook** [sanger-pathogens/Roary#123]
Installation using -

**Installation - With bundled binaries** instructions.

You list -

cpanm Array::Utils BioPerl Exception::Class File::Find::Rule File::Grep File::Slurp::Tiny Graph Moose Moose::Role Text::CSV

On a fresh install of Ubuntu 14.04 you also need -
Log::Log4perl
File::Which

**Comment by andrewjpage** [comment]
Thanks a million for letting me know. I've updated the readme and the website with the extra dependancies.
Andrew

**Comment by mscook** [comment]
No problem. We have had best success with the Ubuntu/Debian instructions
(using a blank Ubuntu 14.04 VM spun up via vagrant) BUT we need to force
install due to failed BioPerl test failures.

On Fri, May 15, 2015 at 5:44 PM, andrewjpage <notifications@github.com>
wrote:

> Thanks a million for letting me know. I've updated the readme and the
> website with the extra dependancies.
> Andrew
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sanger-pathogens/Roary/issues/123#issuecomment-102302231>
> .
>



-- 
================================
Mitchell Jon Stanton-Cook <https://github.com/mscook> (@mscook)

Teaching Fellow &
Software Engineer/System Administrator
Beatson Microbial Genomics Group <http://beatsonlab.com>
University of Queensland
Brisbane, Australia
--------------------------------------------------------
Software Carpentry Workshop
Lead Instructor
UQ Bootcamp 02-03 July 2015  <http://bio-swc-bne.github.io/2015-07-02-UQ/>
--------------------------------------------------------
Co-organiser
2015 HealthHack Brisbane
October 23-24-25 2015 <http://www.healthhack.com.au>
================================

**Comment by andrewjpage** [comment]
Thanks for letting me know.
Andrew

**Comment by tseemann** [comment]
@mscook What BioPerl test failures were you getting?
