### ISSUE TITLE
Syntax (?) errors on perl 5.10.1

### ISSUE THREAD

**Issue by mgalardini** [sanger-pathogens/Roary#128]
Hi,

on our cluster setup we are using perl version 5.10.1, which gives the following errors when running

    roary

or 

    perl ~/PATH_TO_ROARY/roary

Type of arg 1 to values must be hash (not hash element) at [...]/perl5/lib/perl5/Bio/Roary/AnnotateGroups.pm line 106, near "} )"
BEGIN not safe after errors--compilation aborted at [...]/perl5/lib/perl5/Bio/Roary/AnnotateGroups.pm line 312.
Compilation failed in require at [...]/perl5/lib/perl5/Bio/Roary.pm line 15.
BEGIN failed--compilation aborted at [...]/perl5/lib/perl5/Bio/Roary.pm line 15.
Compilation failed in require at [...]/perl5/lib/perl5/Bio/Roary/CommandLine/Roary.pm line 8.
BEGIN failed--compilation aborted at [...]/perl5/lib/perl5/Bio/Roary/CommandLine/Roary.pm line 8.
Compilation failed in require at [...]/perl5/bin/roary line 12.
BEGIN failed--compilation aborted at [...]/perl5/bin/roary line 12.

Thanks a lot,
Marco

**Comment by mgalardini** [comment]
I've tested the attached fix with a handful of gff files from prokka, running the following command:

    ./roary -p 6 genomes/*.gff

and it worked just fine

Best,
Marco

**Comment by andrewjpage** [comment]
Thanks for the fix, I've merged it in.
