### ISSUE TITLE
Annotation missing in set_difference_unique_set_one/two_statistics.csv files

### ISSUE THREAD

**Issue by dutchscientist** [sanger-pathogens/Roary#137]
The files generated by the "query_pan_genome -a difference --input_set_one 1.gff,2.gff --input_set_two 3.gff,4.gff,5.gff -g clustered_proteins" (set_difference_unique_set_one/two_statistics.csv) do not have the information in the annotation column, which the gene_presence_absence.csv does have. It would be helpful if they do, is that possible?

**Comment by dutchscientist** [comment]
I have sent the query_pan_genome output of the test dataset to the previous query to roary@sanger.ac.uk.

**Comment by andrewjpage** [comment]
I've fixed this issue in version 3.0.2 and the annotation column is now populated. Thanks for reporting it.

**Comment by dutchscientist** [comment]
Thanks, much appreciated. Will try it out soon :-)
