### ISSUE TITLE
Getting Roary into Homebrew

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/Roary#152]
All the binary dependencies are in Homebrew Science. The main issue is Perl modules. Homebrew only **checks** to see if they are installed. You can install them your ones in custom places etc, but the dependencies are trickier.

Have you considered fatpack?
http://search.cpan.org/~mstrout/App-FatPacker-0.010003/lib/App/FatPacker.pm

I'm happy to help get it into Brew. If all the Perl deps were already installed, could i run it from the untarred file somehow? Or customize where it installs it?

**Comment by andrewjpage** [comment]
Mmmh looking at the perl dependancies, and how big some of them are (like
BioPerl & Moose), I would say getting a package that works reliably across
multiple different environments will be difficult. Might just have to live
with the two step install.  Thanks for offering to help with the brew stuff
though.

**Comment by tseemann** [comment]
You can assume people have Bio::Perl installed - that's a fundamental.

So, can you use Moo instead of Moose?

http://search.cpan.org/~haarg/Moo-2.000001/lib/Moo.pm#DESCRIPTION

**Comment by tseemann** [comment]
I don't seem to be able to install gubbins from Brew anymore:

https://gist.github.com/tseemann/edc12138c74ba8b74f46

Seems to think Numpy is not installed...

```
python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/bio/linuxbrew/Cellar/gubbins/1.4.5_1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install

Numerical Python (NumPy) is not installed.
```

Which is weird because it is:

```
brew info numpy
homebrew/python/numpy: stable 1.10.4, HEAD
Package for scientific computing with Python
http://www.numpy.org
/bio/linuxbrew/Cellar/numpy/1.9.2_1 (1,381 files, 39.7M)
  Built from source with: --with-python3 --with-openblas
/bio/linuxbrew/Cellar/numpy/1.10.1 (1,395 files, 42.5M)
  Built from source with: --with-python3 --with-openblas
/bio/linuxbrew/Cellar/numpy/1.10.4 (1,395 files, 42.8M) *
  Built from source with: --with-python3 --with-openblas
```
