### ISSUE TITLE
sadaf

### ISSUE THREAD

**Issue by Safmughal** [sanger-pathogens/Roary#154]
Hi.  I downloaded Roary on our iridis (SSH).  I am having a problem while trying to run (roary *.gff) on command line.  The error looks something like that
 
  EXCEPTION: Bio::Root::Exception -------------
MSG: Could not open PROKKA_SG1.gff.proteome.faa.intermediate.extracted.fa: No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /local/software/perl-modules/share/perl5/Bio/Root/Root.pm:486
STACK: Bio::Root::IO::_initialize_io /local/software/perl-modules/share/perl5/Bio/Root/IO.pm:351
STACK: Bio::SeqIO::_initialize /local/software/perl-modules/share/perl5/Bio/SeqIO.pm:491
STACK: Bio::SeqIO::fasta::_initialize /local/software/perl-modules/share/perl5/Bio/SeqIO/fasta.pm:87
STACK: Bio::SeqIO::new /local/software/perl-modules/share/perl5/Bio/SeqIO.pm:372
STACK: Bio::SeqIO::new /local/software/perl-modules/share/perl5/Bio/SeqIO.pm:413
STACK: Bio::Roary::ExtractProteomeFromGFF::_fastatranslate /local/software/roary/3.0.3/source/sanger-pathogens-Roary-5685c8b/lib/Bio/Roary/ExtractProteomeFromGFF.pm:138
STACK: Bio::Roary::ExtractProteomeFromGFF::_convert_nucleotide_to_protein /local/software/roary/3.0.3/source/sanger-pathogens-Roary-5685c8b/lib/Bio/Roary/ExtractProteomeFromGFF.pm:152
STACK: Bio::Roary::ExtractProteomeFromGFF::fasta_file /local/software/roary/3.0.3/source/sanger-pathogens-Roary-5685c8b/lib/Bio/Roary/ExtractProteomeFromGFF.pm:43
STACK: Bio::Roary::CommandLine::ExtractProteomeFromGff::run /local/software/roary/3.0.3/source/sanger-pathogens-Roary-5685c8b/lib/Bio/Roary/CommandLine/ExtractProteomeFromGff.pm:79
STACK: /local/software/roary/3.0.3/source/sanger-pathogens-Roary-5685c8b/bin/extract_proteome_from_gff:18
-----------------------------------------------------------

**Comment by andrewjpage** [comment]
Hi,
What operating system are you running? If its an older version of Linux or
a more obscure version, you'll need to install the dependancies through
your package management system yourself, or install them from source. For
example on CentOS/RedHat, this requires adding extra bioinformatics
repositories so that RPMs are available.  The ./install_dependancies.sh
script may also work for you.
Regards,
Andrew

**Comment by Safmughal** [comment]
Hi,
Thanks for your quick response.  In response to your above comments, I have the following information. 
The operating system is quite an old version of RedHat, RHEL v6.3. To do the installation I modified install_dependencies.sh by taking out all the Ubuntu commands/features, and then executed that script. This built copies of Parallel, Bedtools, Cd-hit and Prank in the build directory.
The installation of the perl modules was a bit more complicated. Initially, I installed the modules as listed in install_dependencies.sh, however subsequently I had to install a lot more modules. I decided to repeatedly run one of the roary scripts until there where no longer any perl related errors. The final list of perl modules is here:
 
parent, Graph::Writer::Dot, Sub::Exporter, Eval::Closure, Devel::OverloadInfo, Package::DeprecationManager, B::Hooks::EndOfScope, Package::Stash, namespace::clean, Module::Implementation, Data::OptList, Class::Load, Moose, Moose::Role, Test::Files, Graph::Writer, File::Which, Log::Log4perl, Text::CSV, Graph, File::Slurp::Tiny, File::Grep, File::Find::Rule, Exception::Class, Array::Utils
 
Some of the perl modules had to forcibly installed due to test errors. My final observation is that there doesn't appear to be a "BEDTOOLS_LIB_DIR", however I'm not sure why.

I hope the above details help.
Kind Regards
Sadaf

**Comment by andrewjpage** [comment]
Hi Sadaf,
I've just pushed up a newer version of the install script and some install
instructions for CentOS/Redhat. It might help somewhat and it builds all of
the external dependancies (and the ubuntu commands have been excluded).
I'm afraid I dont normally work with this distribution, so I'm working of a
basic centos6 vagrant box, so please excuse the not so neat instructions.
Alternatively you can use LinuxBrew http://brew.sh/linuxbrew/

With regards to the perl modules, 'cpanm Bio::Roary' should install all the
missing dependancies automatically.

Thanks for the feedback.
Andrew

**Comment by andrewjpage** [comment]
Hi Sadaf,
Doing a bit more playing around on CentOS6.6, it seems LinuxBrew is the
most straightforward way of setting up the software and installing the
dependancies.
So follow the instructions for Fedora here http://brew.sh/linuxbrew/
then:

brew tap homebrew/science

brew install bedtools cd-hit blast mcl prank parallel mafft exonerate
fasttree

cpanm -f Bio::Roary


Regards,

Andrew

**Comment by Safmughal** [comment]
Thanks Andrew for your efforts.  I appreciate that.  I will update you once I will go through it.
Kind Regards
Sadaf

**Comment by Safmughal** [comment]
Hi Andrew,
Just to let you know that the roary is working perfectly fine on our system.  Thanks for your immense support and efforts to resolve the installation issue.

Kind Regards
Sadaf

**Comment by andrewjpage** [comment]
Thanks for letting me know.
Andrew
