### ISSUE TITLE
labeling of missing values in CSV files

### ISSUE THREAD

**Issue by dutchscientist** [sanger-pathogens/Roary#156]
I primarily use the CSV files produced by Roary, and currently markers missing are represented by an empty cell if opened in a spreadsheet. With large datasets (say 500-1000 genomes) this is sometimes awkward, especially if one wants to do formatting. If all cells were filled (i.e. N/A for missing values), then this would make life a lot easier.

Is this possible? It saves doing Find/Replace of empty cells in Excel. I have done Find/Replace of "" in the text file, but this gives some errors and hence does not work well.

**Comment by andrewjpage** [comment]
Looking into this further, its not something that I think should be changed I'm afraid. Excel works quite well with having the cells empty (""), as do the standard csv parsers. If the cells were populated with NA, then it would mean you would have to account for this separately and has more downsides than an empty cell.

**Comment by dutchscientist** [comment]
No worries, I can easily work around this :-)
