### ISSUE TITLE
EXCEPTION: Bio::Root::Exception could not read ...faa.intermediate.extracted.fa

### ISSUE THREAD

**Issue by yanadya** [sanger-pathogens/Roary#175]
Hello, 

after asking IT to install roary into local cluster I have been stuck with the following error: 

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not read file 'nameX.gff.proteome.faa.intermediate.extracted.fa': No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /opt/apps/perl/5.22.0/lib/site_perl/5.22.0/Bio/Root/Root.pm:449
STACK: Bio::Root::IO::_initialize_io /opt/apps/perl/5.22.0/lib/site_perl/5.22.0/Bio/Root/IO.pm:270
STACK: Bio::SeqIO::_initialize /opt/apps/perl/5.22.0/lib/site_perl/5.22.0/Bio/SeqIO.pm:499
STACK: Bio::SeqIO::fasta::_initialize /opt/apps/perl/5.22.0/lib/site_perl/5.22.0/Bio/SeqIO/fasta.pm:87
STACK: Bio::SeqIO::new /opt/apps/perl/5.22.0/lib/site_perl/5.22.0/Bio/SeqIO.pm:375
STACK: Bio::SeqIO::new /opt/apps/perl/5.22.0/lib/site_perl/5.22.0/Bio/SeqIO.pm:421
STACK: Bio::Roary::ExtractProteomeFromGFF::_fastatranslate /opt/apps/roary/3.2.7/lib/Bio/Roary/ExtractProteomeFromGFF.pm:138
STACK: Bio::Roary::ExtractProteomeFromGFF::_convert_nucleotide_to_protein /opt/apps/roary/3.2.7/lib/Bio/Roary/ExtractProteomeFromGFF.pm:152
STACK: Bio::Roary::ExtractProteomeFromGFF::fasta_file /opt/apps/roary/3.2.7/lib/Bio/Roary/ExtractProteomeFromGFF.pm:43
STACK: Bio::Roary::CommandLine::ExtractProteomeFromGff::run /opt/apps/roary/3.2.7/lib/Bio/Roary/CommandLine/ExtractProteomeFromGff.pm:86
STACK: /opt/apps/roary/3.2.7/bin/extract_proteome_from_gff:18
-----------------------------------------------------------
I am sure my input files is ok, they  finished fine in my laptop with older roary (2.0.0). 
Any ideas of what to check are very welcome!

Thank you, 
Nadejda

**Comment by andrewjpage** [comment]
Hi Nadejda, 
It looks like the dependancies are not all installed.  Most likely the issue is with bedtools.  If you checkout the code from github then run the tests, they should pass.
https://github.com/sanger-pathogens/Roary/blob/master/

In particular if you run:
perl t/00_requires_external.t
it will check for the dependancies.

The recommended method of installation is using LinuxBrew or HomeBrew.
Regards,
Andrew

**Comment by andrewjpage** [comment]
version 3.2.9 now includes an option to check the dependancies which will make issues like this easier to detect.  Functionality in pull request https://github.com/sanger-pathogens/Roary/pull/180
