### ISSUE TITLE
Error "Cant open file: _uninflated_mcl_groups"

### ISSUE THREAD

**Issue by thorellk** [sanger-pathogens/Roary#179]
Hi!

I have downloaded roary 3.2.7 using homebrew on my Mac OSX Yosemite. It seemed to have installed properly but when I run there seems to be some problem with an intermediate file not being created/found. I ran it in verbose mode to see if I could get more clues but cannot see what is the root of the problem. Do you know what could be the problem? I append the command line output below.

Best wishes

Kaisa

roary -e -v *.gff

Please cite Roary if you use any of the results it produces:
    Andrew J. Page, Carla A. Cummins, Martin Hunt, Vanessa K. Wong, Sandra Reuter, Matthew T. G. Holden, Maria Fookes, Daniel Falush, Jacqueline A. Keane, Julian Parkhill (2015), "Roary: Rapid large-scale prokaryote pan genome analysis", Bioinformatics,
    doi: http://doi.org/10.1093/bioinformatics/btv421

2015/09/23 11:26:57 Fixing input GFF files
2015/09/23 11:27:03 Extracting proteins from GFF files
Extracting proteins from 513A.gff
Extracting proteins from PC2022III.gff
Extracting proteins from PC2777IV.gff
Extracting proteins from PC3053II.gff
Extracting proteins from PC3517II.gff
Extracting proteins from PC3714II.gff
Extracting proteins from PC390II.gff
Extracting proteins from PC3939II.gff
Extracting proteins from PC3997IV.gff
Extracting proteins from PC4226IV.gff
Extracting proteins from PC4580III.gff
Extracting proteins from PC4597II.gff
Extracting proteins from PC5099IV.gff
Extracting proteins from PC5538III.gff
Extracting proteins from PC5587platt.gff
Extracting proteins from PC5587u.gff
Extracting proteins from W1090330.gff
Combine proteins into a single file
Iteratively run cd-hit
Parallel all against all blast
Cluster with MCL
2015/09/23 11:51:37 Running command: pan_genome_post_analysis -o clustered_proteins -p pan_genome.fa -s gene_presence_absence.csv -c _clustered.clstr --output_multifasta_files -i _gff_files -f _fasta_files -t 11  --dont_create_rplots   -v  -j Local --processors 1 --group_limit 50000 -cd 99
2015/09/23 11:51:37 Reinflate clusters
Cant open file: _uninflated_mcl_groups
KaisaTiMac:kaisa$ ls
513A.gff			PC3714II.gff.proteome.faa	PC4597II.gff			W1090330.gff.proteome.faa
513A.gff.proteome.faa		PC390II.gff			PC4597II.gff.proteome.faa	_clustered
PC2022III.gff			PC390II.gff.proteome.faa	PC5099IV.gff			_clustered.clstr
PC2022III.gff.proteome.faa	PC3939II.gff			PC5099IV.gff.proteome.faa	_combined_files
PC2777IV.gff			PC3939II.gff.proteome.faa	PC5538III.gff			_combined_files.groups
PC2777IV.gff.proteome.faa	PC3997IV.gff			PC5538III.gff.proteome.faa	_fasta_files
PC3053II.gff			PC3997IV.gff.proteome.faa	PC5587platt.gff			_gff_files
PC3053II.gff.proteome.faa	PC4226IV.gff			PC5587platt.gff.proteome.faa	blast_identity_frequency.Rtab
PC3517II.gff			PC4226IV.gff.proteome.faa	PC5587u.gff
PC3517II.gff.proteome.faa	PC4580III.gff			PC5587u.gff.proteome.faa
PC3714II.gff			PC4580III.gff.proteome.faa	W1090330.gff

**Comment by andrewjpage** [comment]
Hi Kaisa,
It looks like an issue with MCL. Could you send me the output of these commands:

which mcl
mcl --version

which mcxdeblast
# copy the full path into the next command and run with perl
perl /full/path/to/mcxdeblast -h

**Comment by thorellk** [comment]
Hi!

Turned out mcl was installed by homebrew but not linked. When I linked it, it worked.

Thank you for the fast reply!

//Kaisa
