### ISSUE TITLE
Binaries with Higher GLIBC than available.

### ISSUE THREAD

**Issue by alexjironkin** [sanger-pathogens/Roary#191]
Hi,

The binaries supplied with roary complain about GLIBC:

```
/lib64/libc.so.6: version `GLIBC_2.14' not found
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found
```

Can the binaries supplied with the package be re-compiled against the lowest possible GLIBC please. We have 2.12 but, I am sure there are others that run older versions on the GLIBC

**Comment by andrewjpage** [comment]
Hi Alex,
Your best bet is to use LinuxBrew or install the dependancies from source.  GLIBC 2.12 was released 5 years ago and unfortunately we dont have the resources to support very old systems and only aim to support versions released up to 3 years ago.
