### ISSUE TITLE
Add embl output file mapping location of each core gene in the core genome alignment

### ISSUE THREAD

**Issue by EpiDemos82** [sanger-pathogens/Roary#192]
This is not an issue, just a request for a future release.  It would be great if there was an additional output embl that mapped the core genes to the core_gene_alignment.aln file.  Alternatively, this could be output in the gene_presence_absence.csv (e.g. core gene = yes/no, position in aln = 1..1469).

**Comment by andrewjpage** [comment]
Sorry forgot to mention that this has been added in https://github.com/sanger-pathogens/Roary/pull/218
so there is now an extra file with the coordinates.
