### ISSUE TITLE
Non-issue, FYI regarding my 'roary2svg.pl' script

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/Roary#195]
I didn't have much luck getting Marco's contrib/ plots script to work, so I ended up writing a basic SVG plotter for roary output. It's going to be a permanent part of Nullarbor but you can add it to your contrib/ folder if you think others would benefit.

https://raw.githubusercontent.com/tseemann/nullarbor/master/bin/roary2svg.pl

It's pretty basic... SVG sucks at fonts, so it's more confusing than it needs to be, and it may not even work 100% for crazy pan-genomes, not sure yet!

The --taxacol is so it's easy to adapt when you break the .csv file structure ;-)

I just use "convert foo.svg foo.png" to get an image if i need it.

Below is some details:

```
Usage: /home/tseemann/git/nullarbor/bin/roary2svg.pl [options] gene_presence_absence.csv > pan_genome.svg
  --help          This help.
  --verbose!      Verbose output (default '0').
  --width=i       Canvas width (default '1024').
  --height=i      Row height (and ~ font height) (default '20').
  --taxacol=i     Column in gpa.csv where taxa begin (default '14').
  --panonly!      Only non-core genes (default '0').
```

**Comment by andrewjpage** [comment]
Added as part of 3.5.5
