### ISSUE TITLE
.aln files

### ISSUE THREAD

**Issue by danknight** [sanger-pathogens/Roary#197]
Very cool tool!

I notice that after the alignment of the core genome is complete the content of the output directory 'pan_genome_sequences' containing the complete set of pan genome .fa.aln files gets deleted. 
I could put these individual .fa.aln files to good use, is it possible to stop this occuring? 

Cheers
Dan

**Comment by andrewjpage** [comment]
Hi Dan,
Just pass in the '-z' flag and it will keep the files.

Andrew

**Comment by danknight** [comment]
Great, thanks Andrew.
