### ISSUE TITLE
Accessory genes newick file contains full path of infividual files

### ISSUE THREAD

**Issue by dutchscientist** [sanger-pathogens/Roary#200]
The accessory_binary_genes.fa.newick addition is great. One thing I noticed is that the name of each entry contains the full path name, i.e. /usr/name/yadda1/yadda2/roary/cxgf68xy/sample1, /usr/name/yadda1/yadda2/roary/cxgf68xy/sample2, etc. 

I would prefer only the names without the path, is inclusion of the full pathname by design?

**Comment by andrewjpage** [comment]
Hi,
I fixed the issue just this morning, so updating roary to 3.4.3 or above
will make everything work.
Andrew

**Comment by dutchscientist** [comment]
Great, wanted to notify you earlier but only got around to it now. Thanks!
