### ISSUE TITLE
Use of uninitialized value in require at (eval ..) line 1.

### ISSUE THREAD

**Issue by thorellk** [sanger-pathogens/Roary#204]
Hi!

I get this recurring error message, also in the newest version. 

I ran with -v option to get a bit more info on when it is happening and it seems to be in the end of the FastTree part.

2015/11/13 09:40:24 Running command: /usr/local/bin/FastTree -fastest -nt accessory_binary_genes.fa > accessory_binary_genes.fa.newick 
FastTree Version 2.1.8 SSE3, OpenMP (4 threads)
Alignment: accessory_binary_genes.fa
Nucleotide distances: Jukes-Cantor Joins: balanced Support: SH-like 1000
Search: Fastest+2nd +NNI +SPR (2 rounds range 10) +ML-NNI opt-each=1
TopHits: 1.00*sqrtN close=default refresh=0.50
ML Model: Jukes-Cantor, CAT approximation with 20 rate categories
Initial topology in 0.00 seconds
Refining topology: 0 rounds ME-NNIs, 2 rounds ME-SPRs, 0 rounds ML-NNIs
Total branch-length 0.000 after 0.00 sec
Total time: 0.00 seconds Unique: 1/16 Bad splits: 0/0
Aligning each cluster
Use of uninitialized value in require at (eval 1957) line 1.

The next thing that happens is:
2015/11/13 09:41:08 Running command: protein_alignment_from_nucleotides  -v pan_genome_sequences/acdA.fa pan_genome_sequences/ackA.fa pan_genome_sequences/acpP.fa pan_genome_sequences/acyP.fa pan_genome_sequences/addA.fa pan_genome_sequences/adh.fa pan_genome_sequences/adk.fa pan_genome_sequences/ahpC.fa pan_genome_sequences/alaS.fa pan_genome_sequences/alr.fa

After this it continues to run and finishes without further complaints and I wonder if the error is something that one should be concerned about?

Best wishes,
Kaisa

**Comment by andrewjpage** [comment]
Fixed in 3.5.3

**Comment by xiaohai90** [comment]
Dear Andrew,

When I used the roary-3.6.1, command: roary  -e --mafft -p 8 *.gff
I got the error: "Use of uninitialized value in require at (eval 1157) line 1.".  
I checked the output files and compared with those listed on "https://sanger-pathogens.github.io/Roary/", and they were all generated but one "accessory_binary_genes.fa.newik".
 There is a empty file named "accessory_binary_genes.fa"  in my result.

Could you please help me with this issue?

Best Regards!
xiaohai

**Comment by rbutleriii** [comment]
Hello, I also got a similar error, but roary seems to have finished ok. 

roary -p 30 -f 85/ -e -n -i 85 *.gff                    ##returns "Use of uninitialized value in require at (eval 61054) line 1." 

Only happens if I add mafft option. Roary version 3.6.2.

**Comment by andrewjpage** [comment]
It is a warning rather than an error so probably safe to ignore. Usually
upgrading your perl modules makes it go away.
Andrew

**Comment by rbutleriii** [comment]
Thanks for the help.

**Comment by ga23981** [comment]
Hello, I am working on a cluster and tried following at the command prompt with just 2 gffs:

/usr/local/apps/eb/Roary/3.12.0/bin/roary PANS_1_10_annot/PROKKA_05172019.gff PANS_1_1_annot/PROKKA_05172019.gff

My GFFs do not have fasta files at the end.

Getting the following error:

Use of uninitialized value in require at /usr/local/apps/eb/Roary/3.12.0/lib/perl5/5.22.0/x86_64-linux-thread-multi/Encode.pm line 59

Please suggest!
