### ISSUE TITLE
I have published a Roary homebrew formula

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/Roary#208]
I've written a homebrew package for Roary in my tap.

https://github.com/tseemann/homebrew-bioinformatics-linux/blob/master/roary.rb

It doesn't install Roary itself (as Brew doesn't do Perl) but it installs its dependencies and checks that the Bio::Roary Perl module is installed.

**Comment by andrewjpage** [comment]
Very nice, thanks that! So the installation instructions would be:

brew install roary

cpanm Bio::Roary

**Comment by tseemann** [comment]
Yes, but just add this beforehand:

    brew tap tseemann/homebrew-bioinformatics-linux

Despite the name, most of the formulae work on OS X too, but not guaranteed. I try to migrate to homebrew-science where possible and I'm feeling masochistic.

**Comment by tseemann** [comment]
Updated to add `mafft` dep newer version.
