### ISSUE TITLE
Roary not checking tools needed to run

### ISSUE THREAD

**Issue by bachev** [sanger-pathogens/Roary#214]
Hi there,

### Bug report
When starting up, Roaring does not check whether tools it needs are in its path, leading to incomprehensible (for users) error reports. So, instead of somthing like "Could not run 'bedtools', is it installed? Is it in your $PATH?" the user gets (e.g).:

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not read file '/scratch2/tmp/homebachtmp/tmp/compgenomes/tm9omL9Afb/bpg16.gff.proteome.faa.intermediate.extracted.fa': No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/local/share/perl/5.10.0/Bio/Root/Root.pm:449
STACK: Bio::Root::IO::_initialize_io /usr/local/share/perl/5.10.0/Bio/Root/IO.pm:270
STACK: Bio::SeqIO::_initialize /usr/local/share/perl/5.10.0/Bio/SeqIO.pm:499
STACK: Bio::SeqIO::fasta::_initialize /usr/local/share/perl/5.10.0/Bio/SeqIO/fasta.pm:87
STACK: Bio::SeqIO::new /usr/local/share/perl/5.10.0/Bio/SeqIO.pm:375
STACK: Bio::SeqIO::new /usr/local/share/perl/5.10.0/Bio/SeqIO.pm:421
STACK: Bio::Roary::ExtractProteomeFromGFF::_fastatranslate /opt/biosw/roary/lib/Bio/Roary/ExtractProteomeFromGFF.pm:135
STACK: Bio::Roary::ExtractProteomeFromGFF::_convert_nucleotide_to_protein /opt/biosw/roary/lib/Bio/Roary/ExtractProteomeFromGFF.pm:149
STACK: Bio::Roary::ExtractProteomeFromGFF::fasta_file /opt/biosw/roary/lib/Bio/Roary/ExtractProteomeFromGFF.pm:40
STACK: Bio::Roary::CommandLine::ExtractProteomeFromGff::run /opt/biosw/roary/lib/Bio/Roary/CommandLine/ExtractProteomeFromGff.pm:95
STACK: /opt/biosw/bin/extract_proteome_from_gff:19

#### Suggested resolution
prokka (from tseeman) has a pretty flexible runtime tool checker which could be adapted for Roary in no time.

### Background
I just asked 1 hour agon on Twitter about a tool to find presence/absence of genes in bacterial genomes and got a pointer to Roary. What I see on GitHub looks fantastic both in terms of presentation and code.

I have a couple of bugs / observations for which I will open separate tickets, please excuse that spamming but I think Roary is simply too good to not make it even better.

This is occuring on a fairly old machine (Kubuntu 9.10) and I need to install a lot by hand to keep it running with current software. That might explain a couple of oddities I report which you would not expect on newer distributions or when installed vie simple apt-get, homebrew or similar. Still, having Roary quickly point to the obvious reason for fails will make life easier for a couple of people.

Best,
  Bastien

**Comment by andrewjpage** [comment]
Hi Bastien,
Thanks for trying out the software and for all the suggestions.  
Way ahead of you, I already borrowed the dependancy checking code from @tseemann , you can invoke it by passing in '-a' (roary -a). Its off by default to keep the noise down in normal operation.

As your on a very old version of Kubuntu, your best bet is probably to compile the dependancies from source. The install_dependancies.sh script https://github.com/sanger-pathogens/Roary/blob/master/install_dependencies.sh might be of help since it builds all the dependancies from source for Travis (Ubuntu 12.04).

**Comment by bachev** [comment]
Oh, I had no problem building what I needed, thank you. That script helped to find the packages :-)
