### ISSUE TITLE
Prepackaged binaries are dynamically linked and not working on older distributions

### ISSUE THREAD

**Issue by bachev** [sanger-pathogens/Roary#216]
Hi there,

this could get messy and I do not know whether you want to go down this path.

### Observation
The binaries prepackaged in the .tar.gz downloadable on http://sanger-pathogens.github.io/Roary/ are dynamically linked. Which means they will fail on older installations with, e.g., messages like these:

bach@trinity:/opt/biosw/roary/binaries/linux$ ./bedtools 
./bedtools: /lib/libc.so.6: version `GLIBC_2.15' not found (required by ./bedtools)
./bedtools: /lib/libc.so.6: version `GLIBC_2.14' not found (required by ./bedtools)

I just saw problems with GLIBC, but maybe there may be others lurking in the background. Users not always have the possibility to upgrade their machines or patch in newer versions of GLIBC.

You _could_ provide statically linked executables in the download (I do that for MIRA), but this might become a messy thing for OSX.

**Comment by andrewjpage** [comment]
Yep it could get very messy! And sorry it doesnt work on your setup.

I'm not sure if I would have the skills required to create & maintain static executables for a load of other peoples bioinformatics software which would work reliably on old+new versions of Linux and on multiple versions of OSX...  How do you do it for MIRA?

**Comment by bachev** [comment]
For Linux: I have a VirtualBox build machine with Kubuntu 10.4. Building statically there and haven't had a complaint in years.
For OSX: very tricky. Linking statically, but as not everything can be linked statically on OSX, usinf Max dylibbundler. Ugly as hell but it works.

**Comment by andrewjpage** [comment]
Excellent thanks for the tips
