### ISSUE TITLE
Roary not generating pan_genome_reference.fa

### ISSUE THREAD

**Issue by swlong** [sanger-pathogens/Roary#223]
Moving on from my earlier work, I am attempting to generate a "panplasmidome" using reference plasmid sequences from Genbank. Of course, as these plasmids are diverse, there is no real "core" to speak of, however having a "pan_genome_reference" could be useful for mapping short reads looking for known plasmid gene content. 

I've run roary several times but the pan_genome_reference.fa isn't being generated. It appears the other usual output files are being generated including gene_presence_absence.csv and all of the Rtab files. No errors or warnings are being generated. 

Altering the threshold for calling genes "core" to a low percentage so that some core genes are called does not appear to change the script behavior. Is there an inherent problem with using Roary to generate a pan-plasmid reference? I've tried gff converted from gb files, as well as fresh FASTA files annotated by Prokka. Same result. If this is in fact an error, and not a known limitation, I'll upload sample data. 

Best,
S. Wesley Long

**Comment by andrewjpage** [comment]
Sounds like an interesting project, although plasmids vary so much you'd
need to select them carefully to begin with. Do you get any 'core' genes in
the summary stats file? Make sure to use -e -n as parameters.
Andrew

**Comment by andrewjpage** [comment]
Also maybe turn off splitting paralogs since the gene order varys so much,
and people don't set the start consistently.

**Comment by swlong** [comment]
Andrew,

Thanks for the help! No core genes were found in the summary_stats using the defaults, which was no surprise. I hadn't run it with -e -n because I wasn't expecting a core gene alignment (as there were no core genes). However, running Roary with -e -n results in the generation of pan_genome_reference.fa as expected by Roary. Oddly enough the post-analysis step is still taking awhile to run - I say odd because there should be no core genes to align. I apologize that it wasn't clear to me that -e -n were necessary to generate the pan_genome_reference. 

Running with the -s to avoid splitting paralogs did not change the generation of pan_genome_reference.fa (or the lack thereof). 

Best,
S. Wesley Long

**Comment by andrewjpage** [comment]
Sorry if it wasnt clear in the documentation, its on my list to improve it somewhat.  
Andrew
