### ISSUE TITLE
Bio::Root::Exception thrown during core genome alignment, missing some sequence in core_gene_alignment.aln

### ISSUE THREAD

**Issue by swlong** [sanger-pathogens/Roary#224]
I had mentioned this when trying to figure out my roary_plots issue, but it appears to be separate so I wanted to post it here as I think I have noticed a real consequence to this error. 

The error below appears during the MAFFT core genome alignment step. I have noticed when scanning through core_gene_alignment.aln that there are stretches where one strain in the alignment is missing a gene and only has "-" listed across the length of the gene as opposed to bases. As this is a core genome alignment, it seems to me that no strain should be lacking an entire gene, especially when core is defined at present in 99% and we're looking at 5 genomes. This is visible in the Cdiff data which I have posted at my github. 

Error is:
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not open pan_genome_sequences/group_16429.fa.aln: No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/share/perl5/Bio/Root/Root.pm:486
STACK: Bio::Root::IO::_initialize_io /usr/share/perl5/Bio/Root/IO.pm:351
STACK: Bio::SeqIO::_initialize /usr/share/perl5/Bio/SeqIO.pm:491
STACK: Bio::SeqIO::fasta::_initialize /usr/share/perl5/Bio/SeqIO/fasta.pm:87
STACK: Bio::SeqIO::new /usr/share/perl5/Bio/SeqIO.pm:372
STACK: Bio::SeqIO::new /usr/share/perl5/Bio/SeqIO.pm:413
STACK: Bio::Roary::SortFasta::_input_seqio /usr/local/share/perl/5.18.2/Bio/Roary/SortFasta.pm:27
STACK: Bio::Roary::SortFasta::sort_fasta /usr/local/share/perl/5.18.2/Bio/Roary/SortFasta.pm:68
STACK: Bio::Roary::CommandLine::GeneAlignmentFromNucleotides::run /usr/local/share/perl/5.18.2/Bio/Roary/CommandLine/GeneAlignmentFromNucleotides.pm:107

STACK: /usr/local/bin/protein_alignment_from_nucleotides:14

And the error seems to occur multiple times during the MAFFT step. I'm running Biolinux 8, other dependency info available upon request. Also, the MAFFT step seems to usually take a particularly long time especially if more than a few strains are used (say 50 instead of 5). Not sure if this is the expected behavior or not. 

Best,
S. Wesley Long

**Comment by swlong** [comment]
Wondering if there has been any progress on this? Another person in my lab is now using roary with a different dataset on a different computer / linux install and encountering the same error. Surely we're not the only ones?

**Comment by TreeT2** [comment]
I have this issue also essentially the same error: 

Use of uninitialized value in require at (eval 77612) line 1.

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not read file 'pan_genome_sequences/yejB.fa.aln': No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /opt/software/perl/5.18.1/extras/lib/Bio/Root/Root.pm:449
STACK: Bio::Root::IO::_initialize_io /opt/software/perl/5.18.1/extras/lib/Bio/Root/IO.pm:270
STACK: Bio::SeqIO::_initialize /opt/software/perl/5.18.1/extras/lib/Bio/SeqIO.pm:499
STACK: Bio::SeqIO::fasta::_initialize /opt/software/perl/5.18.1/extras/lib/Bio/SeqIO/fasta.pm:87
STACK: Bio::SeqIO::new /opt/software/perl/5.18.1/extras/lib/Bio/SeqIO.pm:375
STACK: Bio::SeqIO::new /opt/software/perl/5.18.1/extras/lib/Bio/SeqIO.pm:421
STACK: Bio::Roary::SortFasta::_input_seqio /opt/software/perl/5.18.1/extras/lib/Bio/Roary/SortFasta.pm:27
STACK: Bio::Roary::SortFasta::sort_fasta /opt/software/perl/5.18.1/extras/lib/Bio/Roary/SortFasta.pm:68
STACK: Bio::Roary::CommandLine::GeneAlignmentFromNucleotides::run /opt/software/perl/5.18.1/extras/lib/Bio/Roary/CommandLine/GeneAlignmentFromNucleotides.pm:107
STACK: /opt/software/perl/5.18.1/extras/bin/protein_alignment_from_nucleotides:14

**Comment by giggzie02** [comment]
I have the same issue running Roary on Biolinux 8. I have checked all the dependencies and have ran the install_dependencies.sh. Is there some package I should update or install that I am unaware of?

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not read file 'pan_genome_sequences/thiD.fa.aln': No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/local/share/perl/5.18.2/Bio/Root/Root.pm:447
STACK: Bio::Root::IO::_initialize_io /usr/local/share/perl/5.18.2/Bio/Root/IO.pm:268
STACK: Bio::SeqIO::_initialize /usr/local/share/perl/5.18.2/Bio/SeqIO.pm:513
STACK: Bio::SeqIO::fasta::_initialize /usr/local/share/perl/5.18.2/Bio/SeqIO/fasta.pm:87
STACK: Bio::SeqIO::new /usr/local/share/perl/5.18.2/Bio/SeqIO.pm:389
STACK: Bio::SeqIO::new /usr/local/share/perl/5.18.2/Bio/SeqIO.pm:435
STACK: Bio::Roary::SortFasta::_input_seqio /usr/local/share/perl/5.18.2/Bio/Roary/SortFasta.pm:27
STACK: Bio::Roary::SortFasta::sort_fasta /usr/local/share/perl/5.18.2/Bio/Roary/SortFasta.pm:68
STACK: Bio::Roary::CommandLine::GeneAlignmentFromNucleotides::run /usr/local/share/perl/5.18.2/Bio/Roary/CommandLine/GeneAlignmentFromNucleotides.pm:107
STACK: /usr/local/bin/protein_alignment_from_nucleotides:14

**Comment by andrewjpage** [comment]
BioLinux 8 was last updated 4 years ago, so there could be many dependancy issues. I would start with upgrading the underlying OS.
