### ISSUE TITLE
[enhancement] use of Roary for DNA sequences/predicted genes?

### ISSUE THREAD

**Issue by dutchscientist** [sanger-pathogens/Roary#228]
Can Roary be adapted for DNA sequences? If I understand correctly how Roary works, then the GFF file can be used as well to produce the DNA sequences of the genes, and then the same procedure could be used to compare them?

**Comment by andrewjpage** [comment]
Yes you can provide just the genes. I did a test a while back where I took the pan genome reference fasta file and reannotated it with prokka. So you end up with a single contig for each gene. 
Then you can put that back into roary.  The only downside is that the ordering of the genes isnt there, so you loose the paralog splitting functionality (or its reduced).

**Comment by dutchscientist** [comment]
But that would still use the translation‎ to amino acids, I assume? I really mean comparing the actual DNA sequences.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: andrewjpageSent: Monday, 8 February 2016 10:48To: sanger-pathogens/RoaryReply To: sanger-pathogens/RoaryCc: dutchscientistSubject: Re: [Roary] [enhancement] use of Roary for DNA sequences/predicted genes? (#228)Yes you can provide just the genes. I did a test a while back where I took the pan genome reference fasta file and reannotated it with prokka. So you end up with a single contig for each gene. 
Then you can put that back into roary.  The only downside is that the ordering of the genes isnt there, so you loose the paralog splitting functionality (or its reduced).

—Reply to this email directly or view it on GitHub.

**Comment by andrewjpage** [comment]
Ah right. No thats something that will not be added to Roary I'm afraid since genes are at the heart of the algorithm.   I recall seeing another pan genome application which chunked up the input genomes into 500 base pieces and did an all against all blast, but cant remember the name off the top of my head I'm afraid.

**Comment by dutchscientist** [comment]
I still want to use the genes (so the FFN files from Prokka), but compare the DNA sequences rather than the translation. With my simple hat on it would only require use of BLASTN instead of BLASTP and use of cdhit with other switches for DNA?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: andrewjpageSent: Monday, 8 February 2016 11:01To: sanger-pathogens/RoaryReply To: sanger-pathogens/RoaryCc: dutchscientistSubject: Re: [Roary] [enhancement] use of Roary for DNA sequences/predicted genes? (#228)Ah right. No thats something that will not be added to Roary I'm afraid since genes are at the heart of the algorithm.   I recall seeing another pan genome application which chunked up the input genomes into 500 base pieces and did an all against all blast, but cant remember the name off the top of my head I'm afraid. 

—Reply to this email directly or view it on GitHub.

**Comment by tseemann** [comment]
Does Roary do clustering at the DNA or AA level ?

**Comment by andrewjpage** [comment]
At the AA level.

**Comment by andrewjpage** [comment]
So I'm afraid that I wont be adding this functionality because AA are at the heart of everything.

**Comment by dutchscientist** [comment]
OK, clear :)
