### ISSUE TITLE
create_pan_genome_plots.R - X11 font problem

### ISSUE THREAD

**Issue by miguelpmachado** [sanger-pathogens/Roary#230]
Hi,

I'm trying to create the pan genome plots using `create_pan_genome_plots.R`, but I keep getting the following error that I cannot fix:

> Saving 7 x 7 in image
> Error in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
>   X11 font -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 1 at size 16 could not be loaded
> Calls: ggsave ... <Anonymous> -> widthDetails -> widthDetails.text -> grid.Call
> Execution halted

Do you have any idea what should I do to solve this?

Best regards,

Miguel Machado

**Comment by tseemann** [comment]
Are you running this on a remote server that doesn't have X11 login, or on a machine with a GUI ?

**Comment by miguelpmachado** [comment]
Hi,
I'm running it in a remote server with X11 (`xeyes` works fine).
In R if I do `capabilities()` I get:
```
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE       FALSE       FALSE        TRUE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE       FALSE        TRUE       FALSE        TRUE       FALSE 
```
I also thought it might be a problem with X11-fonts packages installation, but I tried to install them in many different ways and recompile R afterwards, but it didn't solve the problem. Maybe I missed the correct way of doing it... Do you have any suggestion?
Best regards,
Miguel Machado

**Comment by tseemann** [comment]
It appears someone else has a similar problem within R Studio:

https://support.rstudio.com/hc/en-us/community/posts/202491007-Plot-is-throwing-error-not-displaying-output-properly-

(but no solution)
