### ISSUE TITLE
How to use multiple switches in commandline?

### ISSUE THREAD

**Issue by dutchscientist** [sanger-pathogens/Roary#232]
I am playing with the different switches in the commandline, and this gives problems.

What works: roary -v -s -i 80 *.gff
What does not work: roary -v -p 8 -s -i 80 *.gff (in any order, -p after the -i 80 also fails)

Wherever I put the -p 8 (to use multiple threads), it gives an error after checking the GFFs:
parallel: Error: Command (--no-notice) starts with '-'. Is this a wrong option?

While -g 100000 or -cd 80 works fine. Anything simple I am overlooking? The -p switch is exactly as in the -h helptext.

(using v 3.5.8, just updated)

**Comment by dutchscientist** [comment]
Or does the use of parallel (installed because of Prokka) make it unnecessary to specify the number of threads?

**Comment by andrewjpage** [comment]
By default it will only use 1 thread unless you request to use more.
There are 2 applications called parallel. You need GNU parallel which you
can check by running 'parallel -h'.   Have you aliased parallel by any
chance to suppress the annoying citation notice?

**Comment by tseemann** [comment]
Both Prokka and Roary use the same GNU Parallel.
