### ISSUE TITLE
Roary 3.5.8 works with -i 80 switch, but not with -i 90 or higher with large datasets?

### ISSUE THREAD

**Issue by dutchscientist** [sanger-pathogens/Roary#234]
I am rerunning a dataset done with an earlier version of Roary, now with 3.5.8, and suddenly it refuses to do the whole set (497 genomes) with the -i 90 or higher setting. It works fine until the generation of the tree with the accessory genes, and then it stops. After 3 days still no movement, whereas it was previously done in <6h.

When I make the dataset smaller, it works fine again, and all the GFF files individually work fine. When using -i 70 or -i 60, it works fine.

Tried it both on a server (double Xeon, 64 Gb RAM etc) and the Sanger Pathogens VM, same result. Any thoughts?

Haven't tried going back to the previous version yet, is that easy with cpan?

**Comment by dutchscientist** [comment]
Update: have downgraded to 3.5.7 via:
sudo cpanm -f AJPAGE/Bio-Roary-3.5.7

And then it works without a hitch again. Hence I think there is a bug somewhere, I just don't know what it is!

**Comment by andrewjpage** [comment]
Hi,
I have rolled back the changes and pushed it out as version 3.5.9. 
In 3.5.8 the entire accessory genome was used to create a binary tree & clusters, however it now goes back to its previous behaviour where its limited to 4000 genes (with the top and bottom % removed).

**Comment by dutchscientist** [comment]
Thanks, glad it's working again :)

**Comment by tseemann** [comment]
Can this be made an option?
