### ISSUE TITLE
BLAST Database error when running roary

### ISSUE THREAD

**Issue by duytintruong** [sanger-pathogens/Roary#239]
Dear Roary developers,

Thanks for developing such useful tool.
I am using Roary and encountering some strange bugs.

I produced the gff file with prokka as follows:
prokka tmp/G000800475.fna --outdir tmp/G000800475 --prefix G000800475 --kingdom k__Bacteria --genus g__Bifidobacterium --species s__Bifidobacterium_pseudolongum --strain 1 --centre C --locustag L --compliant --addgenes --metagenome --usegenus --cpus 10

The G000800475.fna and the G000800475.gff files can be found here:
https://www.dropbox.com/sh/44vm8bc4qb1ley0/AACQT4TsQy1Jr5tedj3U_ncsa?dl=0

Then, I obtained the G000800475.gff file and duplicated it:
mkdir tmp2
cp tmp/G000800475/G000800475.gff tmp2
cp tmp2/G000800475.gff tmp2/G000800475_2.gff

Then, I applied roary:
roary -p 10 -f tmp3 -e -g 1000000 tmp2/*.gff

and got the following error:
BLAST Database error: No alias or index file found for protein database [/CIBIO/sharedCM/users/duytin.truong/sources/chocophlan/tmp3/9qHkKRtk88/output_contigs] in search path [/CIBIO/sharedCM/users/duytin.truong/sources/chocophlan/tmp3::]
Use of uninitialized value in require at /home/e.pasolli/perl5/lib/perl5/File/Slurper.pm line 32.
Use of uninitialized value in require at /usr/lib/perl/5.18/Encode.pm line 60, <$group_handle> line 1670.
Use of uninitialized value in require at (eval 780) line 1.

Could you please have a look at the issue?

Many thanks,
Tin

**Comment by andrewjpage** [comment]
Hi Tin,

You've only given it a single genome. Try adding in a second genome (which isnt just a copy of the file) and you should get some meaningful results.

Andrew

**Comment by duytintruong** [comment]
Hi Andrew,

Thanks for your quick reply. I tried with 2 different genomes here (one is identical to the above) and got the same error. The two different gff files are here:
https://www.dropbox.com/sh/o7xxl275g599ya9/AACVP-qpKpA6V_LsR-5RzKGHa?dl=0

The command I executed was:
roary -p 10 -f tmp3 -e -g 1000000 roary2/*.gff

However, if I changed the name of one gff file:
mv roary2/s__Bifidobacterium_pseudolongum.gff roary2/s__Bifidobacterium_abc.gff

and reran:
rm -r tmp3
roary -p 10 -f tmp3 -e -g 1000000 roary2/*.gff

Then, roary worked.
Can you please check the issue?

Thanks,
Tin

**Comment by andrewjpage** [comment]
I've looked at your files and one has 5600 genes and the other 1600 genes? Roary is designed to work on a single species.
