### ISSUE TITLE
Core gene file missing error

### ISSUE THREAD

**Issue by duytintruong** [sanger-pathogens/Roary#241]
Dear Andrew,

I ran roary on four reference genomes of _Bacteroides ovatus_, the fna and gff files obtained from prokka can be found here:

https://www.dropbox.com/sh/r7202w9dkmfjdcy/AADtcwR79F6wLKP2a2jzXKMVa?dl=0

The command I used was:

roary -p 60 -f output -e -g 1000000 -i 95 input/G000218325.gff input/G000154125.gff input/G000273195.gff input/G000273215.gff

And I got the following errors:

Use of uninitialized value in require at /home/e.pasolli/perl5/lib/perl5/File/Slurper.pm line 32.
Use of uninitialized value in require at /usr/lib/perl/5.18/Encode.pm line 60.
Use of uninitialized value in require at (eval 846) line 1.

Core gene file missing: pan_genome_sequences/group_9579.fa.aln
Core gene file missing: pan_genome_sequences/group_165.fa.aln
Core gene file missing: pan_genome_sequences/uidA_2.fa.aln
Core gene file missing: pan_genome_sequences/gno.fa.aln
Core gene file missing: pan_genome_sequences/group_119.fa.aln
Core gene file missing: pan_genome_sequences/group_457.fa.aln
Core gene file missing: pan_genome_sequences/topA.fa.aln
Use of uninitialized value in require at /home/e.pasolli/perl5/lib/perl5/File/Slurper.pm line 32.
Use of uninitialized value in require at /usr/lib/perl/5.18/Encode.pm line 60.
Use of uninitialized value in require at (eval 964) line 1.

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not read file 'pan_genome_sequences/group_165.fa.aln': No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /home/e.pasolli/perl5/lib/perl5/Bio/Root/Root.pm:449
STACK: Bio::Root::IO::_initialize_io /home/e.pasolli/perl5/lib/perl5/Bio/Root/IO.pm:270
STACK: Bio::SeqIO::_initialize /home/e.pasolli/perl5/lib/perl5/Bio/SeqIO.pm:499
STACK: Bio::SeqIO::fasta::_initialize /home/e.pasolli/perl5/lib/perl5/Bio/SeqIO/fasta.pm:87
STACK: Bio::SeqIO::new /home/e.pasolli/perl5/lib/perl5/Bio/SeqIO.pm:375
STACK: Bio::SeqIO::new /home/e.pasolli/perl5/lib/perl5/Bio/SeqIO.pm:421
STACK: Bio::Roary::SortFasta::_input_seqio /CIBIO/sharedCM/tools/roary/lib/Bio/Roary/SortFasta.pm:38
STACK: Bio::Roary::SortFasta::sort_fasta /CIBIO/sharedCM/tools/roary/lib/Bio/Roary/SortFasta.pm:79
STACK: Bio::Roary::CommandLine::GeneAlignmentFromNucleotides::run /CIBIO/sharedCM/tools/roary/lib/Bio/Roary/CommandLine/GeneAlignmentFromNucleotides.pm:112
STACK: /CIBIO/sharedCM/tools/roary/bin/protein_alignment_from_nucleotides:19

-----------------------------------------------------------

Use of uninitialized value in require at /home/e.pasolli/perl5/lib/perl5/File/Slurper.pm line 32.
Use of uninitialized value in require at /usr/lib/perl/5.18/Encode.pm line 60.
Use of uninitialized value in require at (eval 886) line 1.

Can you please check the issue?

Thanks,
Tin

**Comment by andrewjpage** [comment]
resolved via email. The issue was all the  genomes shared the same prefix, so giving them each a unique prefix made things work.

**Comment by Aliceall** [comment]
Hi Andrew, 
I know the issue has been closed but I am having the same and I am not sure I understand how to fix this. I can send the prokka.giff files if needed. Thank you!

**Comment by igarrom** [comment]
Hello,
I know also the issue has been closed but I have the same problem: "Could not read file 'pan_genome_sequences/..." appears several times when running mafft and I do not know if now I can trust my results or they are incompleted.
Thank you!
