### ISSUE TITLE
Use of Roary with Mycoplasma genomes (Genetic Code Table 4)

### ISSUE THREAD

**Issue by dutchscientist** [sanger-pathogens/Roary#243]
I am trying to use Roary with Mycoplasma genomes, which use Genetic Code Table 4, i.e. TGA is used for Trp (W). Unfortunately Roary seems to expect the standard translation table, and genes with a TGA are not included in the analysis, probably because of a mismatch between the predicted length in the annotation and the length found by Roary when translating the GFF, or by Roary not recognising the stopcodon signs?

I don't see an option to specify an alternative Genetic Code Table in the command line of Roary. Can this be done? Is there an option of using the Prokka FAA files as input instead?

**Comment by andrewjpage** [comment]
Hi,
Theres an option to change the translation table built into roary:

    roary -t 4 *.gff

Could you let me know how it works out? 
Andrew

**Comment by dutchscientist** [comment]
Yes, that works fine, great :-) 

Did I miss that option in the helptext or manual, or is it one of the hidden features? Possibly worth to include on the manual page if the latter.

**Comment by tseemann** [comment]
I don't think that option has always been there, but it is in current 3.6.0
```
...
         -s        dont split paralogs
         -t INT    translation table [11]
         -z        dont delete intermediate files
...
```
