### ISSUE TITLE
number_of_conserved_genes.Rtab error

### ISSUE THREAD

**Issue by YangChaoCN** [sanger-pathogens/Roary#245]
Hi,

When I got the conserved_vs_total_genes.png, I found a sudden rise  in conserved genes number after the 100th strain was added, my colleague got the same sudden rise in the 100th  position with another database. It seems that Roary would give a strange result when more than 100 strains were used.

What's the reason?

Here is my conserved_vs_total_genes.png and number_of_conserved_genes.Rtab
![conserved_vs_total_genes](https://cloud.githubusercontent.com/assets/18415610/14809978/294f4f5e-0bc3-11e6-9987-516f4aa29c8a.png)
[number_of_conserved_genes.txt](https://github.com/sanger-pathogens/Roary/files/236088/number_of_conserved_genes.txt)

Best wishes,
YangChao

**Comment by andrewjpage** [comment]
Hi Yang,
By default a gene must be in 99% of isolates to be regarded as 'core'. This allows for the odd randomly broken assembly.  Using simple maths, for 1-99 samples, this means that a gene must be in every sample. For 100-199 samples, a gene can be missing from 1 isolate, and so on. This introduces artificial steps. You can set the core definition to be 100% which will remove this (but the core will be less tolerant to the odd random assembly break), or you can use R to interpolate and smooth the curve.
Regards,
Andrew

**Comment by YangChaoCN** [comment]
Thank for your help!
