### ISSUE TITLE
Error: You need to provide at least 2 files to build a pan genome

### ISSUE THREAD

**Issue by jinlizhang200706** [sanger-pathogens/Roary#251]
I tested roary using "roary -a" , seemed all the dependencies were successfully installed,  I'm confused about this error especially when all the dependencies was detected. 
this is the result of "roary -a "
###########
Please cite Roary if you use any of the results it produces:
    Andrew J. Page, Carla A. Cummins, Martin Hunt, Vanessa K. Wong, Sandra Reuter, Matthew T. G. Holden, Maria Fookes, Daniel Falush, Jacqueline A. Keane, Julian Parkhill,
        "Roary: Rapid large-scale prokaryote pan genome analysis", Bioinformatics, 2015 Nov 15;31(22):3691-3693
    doi: http://doi.org/10.1093/bioinformatics/btv421
        Pubmed: 26198102

2016/06/10 18:02:18 Looking for 'Rscript' - found /home/jinli/soft/R-3.0.1/bin/Rscript
2016/06/10 18:02:18 Determined Rscript version is 3.0
2016/06/10 18:02:18 Looking for 'awk' - found /usr/bin/awk
2016/06/10 18:02:18 Looking for 'bedtools' - found /opt/third_party/bedtools-2.17.0/bedtools
2016/06/10 18:02:18 Determined bedtools version is 2.17
2016/06/10 18:02:18 Looking for 'blastp' - found /home/jinli/soft/third/ncbi-blast-2.3.0+/bin/blastp
2016/06/10 18:02:18 Determined blastp version is 2.3.0
2016/06/10 18:02:18 Looking for 'grep' - found /bin/grep
2016/06/10 18:02:18 Looking for 'kraken' - found /home/jinli/soft/third/kraken-master/kraken
2016/06/10 18:02:18 Determined kraken version is 0.10.6-unreleased
2016/06/10 18:02:18 Looking for 'kraken-report' - found /home/jinli/soft/third/kraken-master/kraken-report
2016/06/10 18:02:18 Determined kraken-report version is 0.10.6-unreleased
2016/06/10 18:02:18 Looking for 'mafft' - found /home/jinli/bin/mafft
2016/06/10 18:02:18 Determined mafft version is 7.221
2016/06/10 18:02:18 Looking for 'makeblastdb' - found /home/jinli/soft/third/ncbi-blast-2.3.0+/bin/makeblastdb
2016/06/10 18:02:18 Determined makeblastdb version is 2.3.0
2016/06/10 18:02:18 Looking for 'mcl' - found /home/jinli/bin/mcl
2016/06/10 18:02:18 Determined mcl version is 14-137
2016/06/10 18:02:18 Looking for 'parallel' - found /home/jinli/soft/third/linuxbrew-master/bin/parallel
2016/06/10 18:02:18 Determined parallel version is 20160422
2016/06/10 18:02:18 Looking for 'prank' - found /home/jinli/bin/prank
2016/06/10 18:02:18 Looking for 'sed' - found /bin/sed
2016/06/10 18:02:18 Looking for 'cd-hit' - found /home/jinli/bin/cd-hit
2016/06/10 18:02:18 Determined cd-hit version is 4.6
2016/06/10 18:02:18 Looking for 'FastTree' - found /home/jinli/soft/third/linuxbrew-master/bin/FastTree
2016/06/10 18:02:18 Determined FastTree version is 2.1
2016/06/10 18:02:18 Roary version 1.006924
2016/06/10 18:02:18 Error: You need to provide at least 2 files to build a pan genome
Usage:   roary [options] *.gff
##########

**Comment by andrewjpage** [comment]
Hi,
Dont worry about the error. By default roary checks the dependancies and
continues (rather than exiting), so it expects to have some input files.
Regards,
Andrew

**Comment by jinlizhang200706** [comment]
thank you so much. I  supplied two gff files in this process and it worked. thank you.
