### ISSUE TITLE
Multi fasta files (amino acid) for pan genome 

### ISSUE THREAD

**Issue by raymondkiu** [sanger-pathogens/Roary#254]
Hello

I read about generating multi fasta files (nucleotide sequences) for pan genome and the usage for this is quite handy. I am also thinking if multi fasta (amimo acid) files can be generated for all the gene clusters- can be quite handy for use with other software such as interproscan?

**Comment by andrewjpage** [comment]
One way to do this is to take the pan_reference_genome.fa file, translate to amino acids, then use it as input to interproscan. We use the 'translate' command from: https://sourceforge.net/projects/fsa/files/ but there are loads of different tools which support it.
