### ISSUE TITLE
empty accessory_binary_genes.fa file

### ISSUE THREAD

**Issue by gsong1205** [sanger-pathogens/Roary#262]
I am wondering why I got an empty accessory_binary_genes.fa file?
Thanks!

**Comment by dutchscientist** [comment]
Which version of Roary do you use? See my new topic https://github.com/sanger-pathogens/Roary/issues/263, where I have problems with version 3.6.5. Going back to an earlier version may help.

sudo cpanm -f AJPAGE/Bio-Roary-3.6.4

**Comment by andrewjpage** [comment]
I've just uploaded a fix for this, thanks for reporting it.  Version 3.6.6 should be in CPAN in a few hours.
