### ISSUE TITLE
unexpected curve from number_of_conserved_genes.Rtab

### ISSUE THREAD

**Issue by kmurase1213** [sanger-pathogens/Roary#268]
Hi Andrew,

I use Roary for pangenome analysis of over 200 samples.
Roary is very rapid and useful pangenome pipeline, but I get unexpected curve from number_of_conserved_genes.Rtab file whenever input file is over 100. When I check contents of that file, there is a sudden surge in value (exactly hundredth). 

Would you be able to fix it ?

Thank you in advance.
Nori

[conserved_genes_curve.pdf](https://github.com/sanger-pathogens/Roary/files/393044/conserved_genes_curve.pdf)

**Comment by andrewjpage** [comment]
Hi Nori,
By default Roary defines a core gene as being present in 99% of isolates. So when you tick over the 100 sample mark, it goes from requiring all genes being in to the core, to allowing for 1 missing. At 200 then it allows for 2 genes to be missing etc...  You can smooth it out the curve in R, or set the core definition parameter to be 100%.
Regards,
Andrew

**Comment by kmurase1213** [comment]
Hi Andrew,
Thank you very much for your quick and polite reply.
I remake the curve in accordance with your advices.
Nori
