### ISSUE TITLE
Same dataset different results!

### ISSUE THREAD

**Issue by mmrec** [sanger-pathogens/Roary#271]
I ran Roary twice with same dataset, but result (core and accessory gene numbers) were slightly different in each run. My question: Is it normal?

**With alignment results:**
Core genes	(99% <= strains <= 100%)	1145
Soft core genes	(95% <= strains < 99%)	118
Shell genes	(15% <= strains < 95%)	840
Cloud genes	(0% <= strains < 15%)	598
Total genes	(0% <= strains <= 100%)	2701

**Without alignment results:**
Core genes	(99% <= strains <= 100%)	1148
Soft core genes	(95% <= strains < 99%)	118
Shell genes	(15% <= strains < 95%)	836
Cloud genes	(0% <= strains < 15%)	607
Total genes	(0% <= strains <= 100%)	2709

Thanks in advance.

**Comment by mmrec** [comment]
Found answer!

**Comment by slebras** [comment]
what was the answer

**Comment by andrewjpage** [comment]
It's in the FAQ. Theres some randomness to make it run in a reasonable time. Same applies to many heuristics for common problems.
