### ISSUE TITLE
Roary gives error

### ISSUE THREAD

**Issue by mmaesaar** [sanger-pathogens/Roary#272]
Iteratively run cd-hit
sh: line 1: 58934 Trace/BPT trap: 5       /usr/local/bin/cd-hit -i _combined_files -o _clustered -T 1 -M 1800 -g 1 -s 1 -d 256 -c 1 > /dev/null 2>&1
Cant open file: _clustered.clstrParallel all against all blast

------------- EXCEPTION -------------
MSG: Could not read file '_clustered': No such file or directory
STACK Bio::Root::IO::_initialize_io /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/Root/IO.pm:270
STACK Bio::SeqIO::_initialize /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/SeqIO.pm:499
STACK Bio::SeqIO::fasta::_initialize /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/SeqIO/fasta.pm:87
STACK Bio::SeqIO::new /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/SeqIO.pm:375
STACK Bio::SeqIO::new /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/SeqIO.pm:421
STACK Bio::Roary::ChunkFastaFile::_build__input_seqio /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/Roary/ChunkFastaFile.pm:27
STACK Bio::Roary::ChunkFastaFile::_input_seqio reader Bio::Roary::ChunkFastaFile::_input_seqio (defined at /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/Roary/ChunkFastaFile.pm line 18):8
STACK Bio::Roary::ChunkFastaFile::_build_sequence_file_names /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/Roary/ChunkFastaFile.pm:48
STACK Bio::Roary::ChunkFastaFile::sequence_file_names reader Bio::Roary::ChunkFastaFile::sequence_file_names (defined at /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/Roary/ChunkFastaFile.pm line 14):8
STACK Bio::Roary::ParallelAllAgainstAllBlast::_build__sequence_file_names /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/Roary/ParallelAllAgainstAllBlast.pm:61
STACK Bio::Roary::ParallelAllAgainstAllBlast::_sequence_file_names reader Bio::Roary::ParallelAllAgainstAllBlast::_sequence_file_names (defined at /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/Roary/ParallelAllAgainstAllBlast.pm line 23):8
STACK Bio::Roary::ParallelAllAgainstAllBlast::run /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/Roary/ParallelAllAgainstAllBlast.pm:112
STACK Bio::Roary::run /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/Roary.pm:92
STACK Bio::Roary::CommandLine::Roary::run /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Bio/Roary/CommandLine/Roary.pm:297
## STACK toplevel /usr/local/bin/roary:14

Can You help?

**Comment by andrewjpage** [comment]
Hi,
Could you send me the output of running 'roary -a' ?

Andrew

**Comment by mmrec** [comment]
Unfortunately I am not able to run Roary any more, it just won't start anymore after upgrading with:
`sudo cpanm -f Bio::Roary`

**Comment by andrewjpage** [comment]
Could you send me the error message your getting?
Andrew

**Comment by mmrec** [comment]
I am not able to reach computer I used to preform analysis. 
After the upgrade roary command was not in the bash. I tried to add path but it didn't help. 
Then tried to use brew to install earlier version, but it didn't help either.

Fortunately I had finished my analysis - just tried to preform checks.

**Comment by andrewjpage** [comment]
Grand, sounds like somethings up with your underlying system. Hope it
doesnt take you too much work to resolve.
Andrew

**Comment by mmrec** [comment]
Got roary working but same error.
roary -a output, it became a problem after cd-hit 4.6.6 update:

roary -a

Please cite Roary if you use any of the results it produces:
    Andrew J. Page, Carla A. Cummins, Martin Hunt, Vanessa K. Wong, Sandra Reuter, Matthew T. G. Holden, Maria Fookes, Daniel Falush, Jacqueline A. Keane, Julian Parkhill,
	"Roary: Rapid large-scale prokaryote pan genome analysis", Bioinformatics, 2015 Nov 15;31(22):3691-3693
    doi: http://doi.org/10.1093/bioinformatics/btv421
	Pubmed: 26198102

2016/09/08 19:37:51 Looking for 'Rscript' - found /usr/local/bin/Rscript
2016/09/08 19:37:51 Determined Rscript version is 3.2
2016/09/08 19:37:51 Looking for 'awk' - found /usr/bin/awk
2016/09/08 19:37:51 Looking for 'bedtools' - found /usr/local/bin/bedtools
2016/09/08 19:37:51 Determined bedtools version is 2.26
2016/09/08 19:37:51 Looking for 'blastp' - found /usr/local/bin/blastp
2016/09/08 19:37:51 Determined blastp version is 2.4.0
2016/09/08 19:37:51 Looking for 'grep' - found /usr/bin/grep
2016/09/08 19:37:51 Looking for 'kraken' - found /usr/local/bin/kraken
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.18/Bio/Roary/External/CheckTools.pm line 129.
2016/09/08 19:37:52 Determined kraken version is 
2016/09/08 19:37:52 Looking for 'kraken-report' - found /usr/local/bin/kraken-report
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.18/Bio/Roary/External/CheckTools.pm line 129.
2016/09/08 19:37:52 Determined kraken-report version is 
2016/09/08 19:37:52 Looking for 'mafft' - found /usr/local/bin/mafft
2016/09/08 19:37:52 Determined mafft version is 7.221
2016/09/08 19:37:52 Looking for 'makeblastdb' - found /usr/local/bin/makeblastdb
2016/09/08 19:37:52 Determined makeblastdb version is 2.4.0
2016/09/08 19:37:52 Looking for 'mcl' - found /usr/local/bin/mcl
2016/09/08 19:37:52 Determined mcl version is 14-137
2016/09/08 19:37:52 Looking for 'parallel' - found /usr/local/bin/parallel
2016/09/08 19:37:52 Determined parallel version is 20160822
2016/09/08 19:37:52 Looking for 'prank' - found /usr/local/bin/prank
2016/09/08 19:37:52 Looking for 'sed' - found /usr/bin/sed
2016/09/08 19:37:52 Looking for 'cd-hit' - found /usr/local/bin/cd-hit
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgomp.1.dylib
  Referenced from: /usr/local/bin/cd-hit
  Reason: image not found
2016/09/08 19:37:53 Could not determine version of cd-hit - please install version 4.6 or higher
2016/09/08 19:37:53 Looking for 'FastTree' - found /usr/local/bin/FastTree
2016/09/08 19:37:53 Determined FastTree version is 2.1
2016/09/08 19:37:53 Roary version 3.6.8
2016/09/08 19:37:53 Error: You need to provide at least 2 files to build a pan genome
Usage:   roary [options] *.gff

Options: -p INT    number of threads [1]
         -o STR    clusters output filename [clustered_proteins]
         -f STR    output directory [.]
         -e        create a multiFASTA alignment of core genes using PRANK
         -n        fast core gene alignment with MAFFT, use with -e
         -i        minimum percentage identity for blastp [95]
         -cd FLOAT percentage of isolates a gene must be in to be core [99]
         -qc       generate QC report with Kraken
         -k STR    path to Kraken database for QC, use with -qc
         -a        check dependancies and print versions
         -b STR    blastp executable [blastp]
         -c STR    mcl executable [mcl]
         -d STR    mcxdeblast executable [mcxdeblast]
         -g INT    maximum number of clusters [50000]
         -m STR    makeblastdb executable [makeblastdb]
         -r        create R plots, requires R and ggplot2
         -s        dont split paralogs
         -t INT    translation table [11]
         -z        dont delete intermediate files
         -v        verbose output to STDOUT
         -w        print version and exit
         -y        add gene inference information to spreadsheet, doesnt work with -e
         -h        this help message

Example: Quickly generate a core gene alignment using 8 threads
         roary -e --mafft -p 8 *.gff

For further info see: http://sanger-pathogens.github.io/Roary/

**Comment by mmrec** [comment]
Error occured after upgrading cd-hit to version 4.6.6. 
After upgrade had to upgrade gcc version 5 to version 6.
Then had to upgrade FastTree.

Now got Roary working again!

One Question, after running roary -a got following for kraken and kraken-report:

```
2016/09/08 20:06:52 Looking for 'kraken' - found /usr/local/bin/kraken
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.18/Bio/Roary/External/CheckTools.pm line 129.
2016/09/08 20:06:52 Determined kraken version is 
2016/09/08 20:06:52 Looking for 'kraken-report' - found /usr/local/bin/kraken-report
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.18/Bio/Roary/External/CheckTools.pm line 129.
2016/09/08 20:06:52 Determined kraken-report version is 
```

Full Roary -a output:
```
2016/09/08 20:06:51 Looking for 'Rscript' - found /usr/local/bin/Rscript
2016/09/08 20:06:51 Determined Rscript version is 3.2
2016/09/08 20:06:51 Looking for 'awk' - found /usr/bin/awk
2016/09/08 20:06:51 Looking for 'bedtools' - found /usr/local/bin/bedtools
2016/09/08 20:06:51 Determined bedtools version is 2.26
2016/09/08 20:06:51 Looking for 'blastp' - found /usr/local/bin/blastp
2016/09/08 20:06:52 Determined blastp version is 2.4.0
2016/09/08 20:06:52 Looking for 'grep' - found /usr/bin/grep
2016/09/08 20:06:52 Looking for 'kraken' - found /usr/local/bin/kraken
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.18/Bio/Roary/External/CheckTools.pm line 129.
2016/09/08 20:06:52 Determined kraken version is 
2016/09/08 20:06:52 Looking for 'kraken-report' - found /usr/local/bin/kraken-report
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.18/Bio/Roary/External/CheckTools.pm line 129.
2016/09/08 20:06:52 Determined kraken-report version is 
2016/09/08 20:06:52 Looking for 'mafft' - found /usr/local/bin/mafft
2016/09/08 20:06:52 Determined mafft version is 7.221
2016/09/08 20:06:52 Looking for 'makeblastdb' - found /usr/local/bin/makeblastdb
2016/09/08 20:06:52 Determined makeblastdb version is 2.4.0
2016/09/08 20:06:52 Looking for 'mcl' - found /usr/local/bin/mcl
2016/09/08 20:06:52 Determined mcl version is 14-137
2016/09/08 20:06:52 Looking for 'parallel' - found /usr/local/bin/parallel
2016/09/08 20:06:52 Determined parallel version is 20160822
2016/09/08 20:06:52 Looking for 'prank' - found /usr/local/bin/prank
2016/09/08 20:06:52 Looking for 'sed' - found /usr/bin/sed
2016/09/08 20:06:52 Looking for 'cd-hit' - found /usr/local/bin/cd-hit
2016/09/08 20:06:52 Determined cd-hit version is 4.6
2016/09/08 20:06:52 Looking for 'FastTree' - found /usr/local/bin/FastTree
2016/09/08 20:06:52 Determined FastTree version is 2.1
2016/09/08 20:06:52 Roary version 3.6.8
2016/09/08 20:06:52 Error: You need to provide at least 2 files to build a pan genome
Usage:   roary [options] *.gff
```

**Comment by alipirani88** [comment]
Hi andrew,

I am experiencing the same issue and have not been able to find the solution. Here is the error message from roary:

```
2016/10/06 17:26:26 Output directory created: /nfs/main/Ali/Project_RNA_seq/Ortholog_detection/temp_out_4
2016/10/06 17:26:26 Fixing input GFF files
2016/10/06 17:26:28 Extracting proteins from GFF files
Extracting proteins from /nfs/main/Ali/Project_RNA_seq/Ortholog_detection/temp/new_gff/HM26_10062016.gff
Extracting proteins from /nfs/main/Ali/Project_RNA_seq/Ortholog_detection/temp/new_gff/HM27_10062016.gff
Combine proteins into a single file
Iteratively run cd-hit
Cant open file: _clustered.clstrParallel all against all blast

------------- EXCEPTION -------------
MSG: Could not read file '_clustered': No such file or directory
STACK Bio::Root::IO::_initialize_io /home/username/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bio/Root/IO.pm:270
STACK Bio::SeqIO::_initialize /home/username/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bio/SeqIO.pm:499
STACK Bio::SeqIO::fasta::_initialize /home/username/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bio/SeqIO/fasta.pm:87
STACK Bio::SeqIO::new /home/username/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bio/SeqIO.pm:375
STACK Bio::SeqIO::new /home/username/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Bio/SeqIO.pm:421
STACK Bio::Roary::ChunkFastaFile::_build__input_seqio /nfs/main/bin_group/Roary/lib/Bio/Roary/ChunkFastaFile.pm:38
STACK Bio::Roary::ChunkFastaFile::_input_seqio reader Bio::Roary::ChunkFastaFile::_input_seqio (defined at /nfs/main/bin_group/Roary/lib/Bio/Roary/ChunkFastaFile.pm line 29):8
STACK Bio::Roary::ChunkFastaFile::_build_sequence_file_names /nfs/main/bin_group/Roary/lib/Bio/Roary/ChunkFastaFile.pm:59
STACK Bio::Roary::ChunkFastaFile::sequence_file_names reader Bio::Roary::ChunkFastaFile::sequence_file_names (defined at /nfs/main/bin_group/Roary/lib/Bio/Roary/ChunkFastaFile.pm line 25):8
STACK Bio::Roary::ParallelAllAgainstAllBlast::_build__sequence_file_names /nfs/main/bin_group/Roary/lib/Bio/Roary/ParallelAllAgainstAllBlast.pm:72
STACK Bio::Roary::ParallelAllAgainstAllBlast::_sequence_file_names reader Bio::Roary::ParallelAllAgainstAllBlast::_sequence_file_names (defined at /nfs/main/bin_group/Roary/lib/Bio/Roary/ParallelAllAgainstAllBlast.pm line 34):8
STACK Bio::Roary::ParallelAllAgainstAllBlast::run /nfs/main/bin_group/Roary/lib/Bio/Roary/ParallelAllAgainstAllBlast.pm:123
STACK Bio::Roary::run /nfs/main/bin_group/Roary/lib/Bio/Roary.pm:97
STACK Bio::Roary::CommandLine::Roary::run /nfs/main/bin_group/Roary/lib/Bio/Roary/CommandLine/Roary.pm:302
STACK toplevel /nfs/main/bin_group/Roary/bin/roary:19
-------------------------------------
```

This is the output from roary -a 

```
2016/10/06 17:32:49 Looking for 'Rscript' - found /home/username/anaconda/bin/Rscript
2016/10/06 17:32:49 Determined Rscript version is 3.1
2016/10/06 17:32:49 Looking for 'awk' - found /usr/bin/awk
2016/10/06 17:32:49 Looking for 'bedtools' - found /home/username/bin/bedtools2-master/bin/bedtools
2016/10/06 17:32:49 Determined bedtools version is 2.23
2016/10/06 17:32:49 Looking for 'blastp' - found /home/username/bin/blast/bin/blastp
2016/10/06 17:32:49 Determined blastp version is 2.2.31
2016/10/06 17:32:49 Looking for 'grep' - found /usr/bin/grep
2016/10/06 17:32:49 Looking for 'kraken' - found /nfs/main/bin_group/kraken-master/kraken
Use of uninitialized value in concatenation (.) or string at /nfs/main/bin_group/Roary/lib/Bio/Roary/External/CheckTools.pm line 139.
2016/10/06 17:32:49 Determined kraken version is 
2016/10/06 17:32:49 Looking for 'kraken-report' - found /nfs/main/bin_group/kraken-master/kraken-report
Use of uninitialized value in concatenation (.) or string at /nfs/main/bin_group/Roary/lib/Bio/Roary/External/CheckTools.pm line 139.
2016/10/06 17:32:49 Determined kraken-report version is 
2016/10/06 17:32:49 Looking for 'mafft' - found /nfs/main/bin_group/Roary/build/mafft-7.271-without-extensions/build/bin/mafft
2016/10/06 17:32:49 Determined mafft version is 7.271
2016/10/06 17:32:49 Looking for 'makeblastdb' - found /home/username/bin/blast/bin/makeblastdb
2016/10/06 17:32:49 Determined makeblastdb version is 2.2.31
2016/10/06 17:32:49 Looking for 'mcl' - found /nfs/main/bin_group/Roary/build/mcl-14-137/src/shmcl/mcl
2016/10/06 17:32:49 Determined mcl version is 14-137
2016/10/06 17:32:49 Looking for 'parallel' - found /nfs/main/bin_group/Roary/build/parallel-20160722/src/parallel
2016/10/06 17:32:49 Determined parallel version is 20160722
2016/10/06 17:32:49 Looking for 'prank' - found /nfs/main/bin_group/prank
2016/10/06 17:32:49 Looking for 'sed' - found /usr/bin/sed
2016/10/06 17:32:49 Looking for 'cd-hit' - found /nfs/main/bin_group/cd-hit
2016/10/06 17:32:49 Determined cd-hit version is 4.6
2016/10/06 17:32:49 Looking for 'FastTree' - found /nfs/main/bin_group/Roary/build/fasttree/FastTree
2016/10/06 17:32:49 Determined FastTree version is 2.1
2016/10/06 17:32:49 Roary version 1.006924
2016/10/06 17:32:49 Error: You need to provide at least 2 files to build a pan genome

```

I would appreciate any help with this regard.
Thanks

**Comment by diaz13** [comment]
Hello
I am working on a project based on all the genomes of enterococcus faecalis.
It's been a week since roary tells me this mistake.

Could not open /home/mamadou/Pangenome/gOwpb0VOYj/FPDW01.gff.proteome.faa: No such file or directory at /usr/share/perl5/Bio/Roary/SplitGroups.pm line 84.

**Comment by andrewjpage** [comment]
Hi, Its most likely a problem with your input data. 
I would double check the QC of the data to remove any obvious contamination, poor quality assemblies, different species, etc...
Then I would double check each assembly was annotated with a unqiue locus tag (so that each gene has a globally unique identifier).
Regards,
Andrew

**Comment by jananiravi** [comment]
@andrewjpage thanks for the really helpful package. I'm using gff files downloaded using `ncbi-genome-download` for all sequences matching a particular `taxid`. These are not 'my' sequences. Would you still recommend QC check with Kraken? I ask because I start with `roary -f ***` on my downloaded gff files followed by the same with the 'fixed' gff files. My output files are all empty, and I see some of the errors mentioned above. Not sure as to how to proceed with the pangenome analysis and exploration from here.

**Comment by senula2017** [comment]
I am getting this error
Please help me to fix this


Subhashinies-MacBook-Air:roary indika$ /Users/indika/miniconda3/bin/roary roary /Users/indika/pangenome *.gff
Can't locate Bio/Roary/CommandLine/Roary.pm in @INC (you may need to install the Bio::Roary::CommandLine::Roary module) (@INC contains:  /Users/indika/Roary/lib/Bio/Roary/lib /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/indika/miniconda3/bin/roary line 12.
BEGIN failed--compilation aborted at /Users/indika/miniconda3/bin/roary line 12.

**Comment by andrewjpage** [comment]
@senula2017 your error indicates the software is not installed correctly. I would reinstalling (conda install roary) or contact your local IT support/system administrator
