### ISSUE TITLE
Errors when downloaded sequences from NCBI

### ISSUE THREAD

**Issue by lindachuan123** [sanger-pathogens/Roary#274]
![20160830222125](https://cloud.githubusercontent.com/assets/16264216/18093489/9abe7cf8-6f02-11e6-9e00-9d643a6e8084.png)
![20160830222144](https://cloud.githubusercontent.com/assets/16264216/18093493/9defa6d6-6f02-11e6-9dd8-d7232fc41215.png)
![20160830222157](https://cloud.githubusercontent.com/assets/16264216/18093496/a0fc5130-6f02-11e6-8f81-c94c6c35600f.png)

**Comment by andrewjpage** [comment]
answered via email
