### ISSUE TITLE
query_pan_genome output meaning

### ISSUE THREAD

**Issue by pauruihu** [sanger-pathogens/Roary#275]
Hi, 
I used "query_pan_genome -a difference" to compare 2 samples. I've tried to find a detailed explanation about each *_statistics.csv output column, but I couldn't read anything related to it.
I'm a bit confused about "genome fragment" and "accessory fragment" and its order, but what it's more important for me is the meaning of "investigate" of the QC column.

Thank you in advance for your time.

Best,
Paula

**Comment by andrewjpage** [comment]
Hi Paula,
More details on the spreadsheet columns are available here:
http://sanger-pathogens.github.io/Roary/index.html#gene_presence_absencecsv

Investigate indicates that we think theres something not right about the
contig that the gene is located on. For example if you have a lot of
contigs with a single gene on them it could indicate contamination. So
these are flagged as potentially problematic and we indicate to the
researcher that they should manually investigate further to see if there is
an underlying issue with this data.
Regards,
Andrew
