### ISSUE TITLE
Questions: "Genome Fragment", "QC"

### ISSUE THREAD

**Issue by ConstantinV** [sanger-pathogens/Roary#276]
Hello!
First of all, I want to thank you a lot for this brilliant tool!  It saved my time. 
But I have several questions 
1. Could you explain to me the meaning of "Genome Fragment" column? Why genes from different genomes (and I suppose from different contigs) are located on the same  Genome Fragment?
2. What does mean QC column ? What kind of parameters of the particular gene group should I investigate? The possible reasons for low QS? And how to extract this group to separate fasta alignment (I assume you have standard commands)? 

Thank you.

**Comment by andrewjpage** [comment]
The genome fragment is drawn from the underlying graph of how the genes are connected at a contig level. These graphs are outputted in DOT format by roary and are a gold mine of information.
There is some filtering of the graph to get rid of weak connections. Basically what its saying is that this group of genes is often found together in assemblies. You can make it more accurate by adding in reference genomes which anchors the graph.

The QC column just flags up things which look a bit odd and which you should probably look into a bit more. I would eyeball at the underlying assembly and the contigs the flagged genes occur on. For example if you have lots of contigs with a single gene, this can indicate low level contamination.
