### ISSUE TITLE
roary_plots.py missing 

### ISSUE THREAD

**Issue by bioisu** [sanger-pathogens/Roary#277]
I installed roary on my bio linux. When I tried to run roary_plots.py, I used " python roary_plots.py core_gene_alignment.nwk gene_presence_absence.csv"
The results were 
python: can't open file 'roary_plots.py': [Errno 2] No such file or directory

I was wondering where to find the "roary_plots.py" script on linux?

**Comment by bioisu** [comment]
i used "roary -a"
At the end of the list, it said:
print:6: command not found: roary_plots.py                                      
print:7: command not found: roary_plots.py

**Comment by andrewjpage** [comment]
Hi, the roary_plots.py script is an additional program contributed by another researcher so you have to install it separately.  Details are here:
https://github.com/sanger-pathogens/Roary/tree/master/contrib/roary_plots

**Comment by jotes35** [comment]
Hi All,
How to I add labels to the trees generated by roary_plots.py
