### ISSUE TITLE
core genome alignment file

### ISSUE THREAD

**Issue by ceya** [sanger-pathogens/Roary#281]
Hello,

Does anyone know if the core sequence alignment file give concatenated CDS of the core genes? I found that the total number of nucleotides of my alignment cannot be divided by 3 (aka they are not complete coding sequences). Any idea why?

Thank you very much!!
Brooke

**Comment by andrewjpage** [comment]
Hi ceya. If you remove all the gaps from the alignment the sequences will divide by 3.
Regards,
Andrew
