### ISSUE TITLE
Is these results fine to use?

### ISSUE THREAD

**Issue by mmrec** [sanger-pathogens/Roary#282]
I have few problems with output:
1) I have 189 cases where same gene have ended up in different groups;
2) I have 15 cases where the paralogs couldn’t be split;
3) I have 36 cases where QC gives:
"Hypothetical protein with no hits to refseq/uniprot/clusters/cdd/tigrfams/pfam overlapping another protein with hits"
4) I have 27 cases where QC gives:
"Investigate"

Is it okay to use Roary with that kind of results or could You give pointers what to do with the situation?

Thanks

**Comment by tseemann** [comment]
For 1) how do you know it was the "same gene" ?

Roary was designed for within-species studies, some of its speed ups and heuristics do not work with divergenet data.

**Comment by mmrec** [comment]
In the github page it is said:

> "A non unique gene name, where sequences with the same gene name have ended up in different groups."

I have 189 non unique gene names - so I thought it was what that meant.

Is it not correct?

**Comment by mmrec** [comment]
I used Roary core alignment for BNG analysis and my main concern is if it is ok to use when I have three genes with QC:

> Hypothetical protein with no hits to refseq/uniprot/clusters/cdd/tigrfams/pfam overlapping another protein with hits

Should I exclude these genes with QC column with values Hypothetical... and Investigate?

**Comment by andrewjpage** [comment]
Hi, 
Roary does a bit of QC and flags things that may be errors. Its up to you to look at your data and to decide if theres something wrong (like erroneous annotation or host contamination).   We try and split paralogs but sometimes theres not enough information available to split them.  When paralogs are split, it can cause identical genes to end up in different clusters (based on the syntany).  You can turn this off by using the '-s' parameter.

**Comment by mmrec** [comment]
Thank You for really quick feedback
