### ISSUE TITLE
Regarding option -s

### ISSUE THREAD

**Issue by mmrec** [sanger-pathogens/Roary#289]
I tested this function you suggested in issue #282 but it's still confusing:
1) I used roary without using -s and results were as follows:
> Core genes	(99% <= strains <= 100%)	1171
> Soft core genes	(95% <= strains < 99%)	106
> Shell genes	(15% <= strains < 95%)	820
> Cloud genes	(0% <= strains < 15%)	1338
> Total genes	(0% <= strains <= 100%)	3435

Avg sequences per isolate had 19 genes values were > 1.

2) I used roary with -s and results were as follows:
> Core genes	(99% <= strains <= 100%)	1210
> Soft core genes	(95% <= strains < 99%)	103
> Shell genes	(15% <= strains < 95%)	665
> Cloud genes	(0% <= strains < 15%)	992
> Total genes	(0% <= strains <= 100%)	2970

Avg sequences per isolate had 196 genes values were > 1.

------------------------------------------------------------------
First:
Did I understand correctly when using -s paralogs aren't split and thats why 2) has less Total genes but more avg sequence per isolates?
 
Second:
I am little confused which output is proper to use? - Could you help me with that?

Thanks in advance.

**Comment by andrewjpage** [comment]
First:
Yes you are correct.

Second:
Its up to you to look at your data and understand whats going on I'm afraid. Best of luck with your research.

**Comment by mmrec** [comment]
Thanks
