### ISSUE TITLE
query_pan_genome define list of genome groups

### ISSUE THREAD

**Issue by torsten123** [sanger-pathogens/Roary#291]
is there a way to pass the names of the genomes for the two groups to the script other to input them into the comand line? Could I for example give just the location for two folders with the .gff inside to create the pangenome comparison? What would be the syntax for this?

**Comment by andrewjpage** [comment]
Sorry its a bit clunky, but the script requires you to list out the names.  Standard linux commands should be able to do the trick for you (like xargs and awk).
