### ISSUE TITLE
prank is not installed (Linuxbrew)

### ISSUE THREAD

**Issue by ilnamkang** [sanger-pathogens/Roary#294]
I've been trying to install Roary using Linuxbrew in my Linux server (Ubuntu 14.04).
Everything worked without a problem, except for prank.

When I tried to install prank, the source code file was not downloaded. Below is the error message.

memb@memb-72G[memb] brew install prank 
==> Installing prank from homebrew/science
==> Downloading http://wasabiapp.org/download/prank/prank.source.140603.tgz
curl: (52) Empty reply from server
Error: Failed to download resource "prank"
Download failed: http://wasabiapp.org/download/prank/prank.source.140603.tgz

(for your information, 'wget' also failed.)

But, I could download the source code file using my laptop (Windows 10) without any problem. So, I uploaded the file to cache directory of brew. But, it seems that 'brew install' cannot recognize the uploaded file. (There is no problem in the owner and permission of the file.)

How can I install prank using Linuxbrew?

Thanks.

**Comment by andrewjpage** [comment]
Hi,
It looks like a network setup issue on your server (proxy perhaps?). You should ask your local system administrator for assistance as they are best placed to help you.

On ubuntu 14.04 you can install all the dependencies using apt, for example:
sudo apt-get install prank

Andrew
