### ISSUE TITLE
Error: unexpected input in "_"

### ISSUE THREAD

**Issue by nghait** [sanger-pathogens/Roary#299]
# Dear all, is there anyone who experienced following: When I run 
$ roary -f roaryout -e -n -v -r -z - t 11 -c *.gff  
# The display show in a middle
Total time: 3.45 seconds Unique: 95/95 Bad splits: 0/92
Saving 7 x 7 image
Saving 7 x 7 image
Error:  unexpected input in "_"
Execution halted
Aligning each cluster

# .......and continuous run

# Could you give me a hint to fix it and help me get out of my struggling? 
# Your suggestion is highly appreciated.

**Comment by anweshmaile** [comment]
Faced this exact same issue and this was what worked for me (I may be wrong, as I'm new to this area...)

I was working with a small number of Leptospira isolates (11), out of which 10 were L. interrogans and 1 was L. biflexa...
So, when I gave all 11 gff files, this issue occurred and by removing the biflexa gff and using only 10 gff files, there was no issue. 
Additionally, 7 of the interrogans gff files with biflexa gff, did not give any error, but core genes were only 3 (out of ~5000 genes).
So, I think this is due high degree of dissimilarity. (Don't know exactly...)

**Comment by yachenhu** [comment]
Hi, nghait.
It occurred because this R script is trailing a piece of Perl code. 
Actually, it doesn't affect the result. If you want to fix it,  edit the script of create_pan_genome_plots, removing the lines from '__END__'
