### ISSUE TITLE
Old version in the master tarball?

### ISSUE THREAD

**Issue by MrsLaviniaG** [sanger-pathogens/Roary#300]
Hi,

I've just downloaded and installed roary from the source tarball.  It seems to be fine (thanks so much for all the clear comments in GitHub, I was able to correctly add all the dependencies), however I seem to have an old version:

./roary -a

Please cite Roary if you use any of the results it produces:
    Andrew J. Page, Carla A. Cummins, Martin Hunt, Vanessa K. Wong, Sandra Reuter, Matthew T. G. Holden, Maria Fookes, Daniel Falush, Jacqueline A. Keane, Julian Parkhill,
        "Roary: Rapid large-scale prokaryote pan genome analysis", Bioinformatics, 2015 Nov 15;31(22):3691-3693
    doi: http://doi.org/10.1093/bioinformatics/btv421
        Pubmed: 26198102

2017/01/12 09:59:34 Looking for 'Rscript' - found /usr/local/appl/bio/R/bin/Rscript
2017/01/12 09:59:34 Determined Rscript version is 3.2
2017/01/12 09:59:34 Looking for 'awk' - found /bin/awk
2017/01/12 09:59:34 Looking for 'bedtools' - found /usr/local/appl/bio/bedtools/bin/bedtools
2017/01/12 09:59:34 Determined bedtools version is 2.23
2017/01/12 09:59:34 Looking for 'blastp' - found /usr/local/appl/bio/ncbi-blast/bin/blastp
2017/01/12 09:59:34 Determined blastp version is 2.2.30
2017/01/12 09:59:34 Looking for 'grep' - found /bin/grep
2017/01/12 09:59:34 Looking for 'kraken' - found /usr/local/appl/bio/kraken/bin/kraken
Use of uninitialized value in concatenation (.) or string at /scratch/CAGRF12675/roary/lib//Bio/Roary/External/CheckTools.pm line 139.
2017/01/12 09:59:34 Determined kraken version is
2017/01/12 09:59:34 Looking for 'kraken-report' - found /usr/local/appl/bio/kraken/bin/kraken-report
Use of uninitialized value in concatenation (.) or string at /scratch/CAGRF12675/roary/lib//Bio/Roary/External/CheckTools.pm line 139.
2017/01/12 09:59:34 Determined kraken-report version is
2017/01/12 09:59:35 Looking for 'mafft' - found /home/gordonl/mafft/bin/mafft
2017/01/12 09:59:35 Determined mafft version is 7.307
2017/01/12 09:59:35 Looking for 'makeblastdb' - found /usr/local/appl/bio/ncbi-blast/bin/makeblastdb
2017/01/12 09:59:35 Determined makeblastdb version is 2.2.30
2017/01/12 09:59:35 Looking for 'mcl' - found /scratch/CAGRF12675/mcl/mcl-14-137/bin/bin/mcl
2017/01/12 09:59:35 Determined mcl version is 14-137
2017/01/12 09:59:35 Looking for 'parallel' - found /scratch/CAGRF12675/gnu/parallel-20150122/bin/bin/parallel
2017/01/12 09:59:35 Determined parallel version is 20150122
2017/01/12 09:59:35 Looking for 'prank' - found /home/gordonl/prank-msa/src/prank
2017/01/12 09:59:35 Looking for 'sed' - found /bin/sed
2017/01/12 09:59:35 Looking for 'cd-hit' - found /scratch/CAGRF12675/cdhit/cd-hit
2017/01/12 09:59:35 Determined cd-hit version is 4.6
2017/01/12 09:59:35 Looking for 'FastTree' - found /scratch/CAGRF12675/fasttree/FastTree
2017/01/12 09:59:35 Determined FastTree version is 2.1
**2017/01/12 09:59:35 Roary version 1.006923**
2017/01/12 09:59:35 Error: You need to provide at least 2 files to build a pan genome
Usage:   roary [options] *.gff

Options: -p INT    number of threads [1]
         -o STR    clusters output filename [clustered_proteins]
         -f STR    output directory [.]
         -e        create a multiFASTA alignment of core genes using PRANK
         -n        fast core gene alignment with MAFFT, use with -e
         -i        minimum percentage identity for blastp [95]
         -cd FLOAT percentage of isolates a gene must be in to be core [99]
         -qc       generate QC report with Kraken
         -k STR    path to Kraken database for QC, use with -qc
         -a        check dependancies and print versions
         -b STR    blastp executable [blastp]
         -c STR    mcl executable [mcl]
         -d STR    mcxdeblast executable [mcxdeblast]
         -g INT    maximum number of clusters [50000]
         -m STR    makeblastdb executable [makeblastdb]
         -r        create R plots, requires R and ggplot2
         -s        dont split paralogs
         -t INT    translation table [11]
         -z        dont delete intermediate files
         -v        verbose output to STDOUT
         -w        print version and exit
         -y        add gene inference information to spreadsheet, doesnt work with -e
         -h        this help message

Example: Quickly generate a core gene alignment using 8 threads
         roary -e --mafft -p 8 *.gff

For further info see: http://sanger-pathogens.github.io/Roary/

Shouldn't it be 3.6.1?

with thanks,

Lavinia Gordon.

**Comment by andrewjpage** [comment]
Hi,
It's a bug in how the version is worked out rather than an old version. It
looks like the bio Perl version number. Thanks for letting me know.
Andrew

**Comment by Kanwal03** [comment]
I have same problem. How can I update to newer version 3.12.0(installed through source code).
I have following output for roary -a
Use of uninitialized value in require at /usr/lib/x86_64-linux-gnu/perl/5.22/Encode.pm line 59.

Please cite Roary if you use any of the results it produces:
    Andrew J. Page, Carla A. Cummins, Martin Hunt, Vanessa K. Wong, Sandra Reuter, Matthew T. G. Holden, Maria Fookes, Daniel Falush, Jacqueline A. Keane, Julian Parkhill,
	"Roary: Rapid large-scale prokaryote pan genome analysis", Bioinformatics, 2015 Nov 15;31(22):3691-3693
    doi: http://doi.org/10.1093/bioinformatics/btv421
	Pubmed: 26198102

2018/12/31 11:25:34 Looking for 'Rscript' - found /usr/bin/Rscript
2018/12/31 11:25:34 Determined Rscript version is 3.2
2018/12/31 11:25:34 Looking for 'awk' - found /usr/bin/awk
2018/12/31 11:25:34 Looking for 'bedtools' - found /usr/bin/bedtools
2018/12/31 11:25:34 Determined bedtools version is 2.25
2018/12/31 11:25:34 Looking for 'blastp' - found /usr/bin/blastp
2018/12/31 11:25:36 Determined blastp version is 2.2.31
2018/12/31 11:25:36 Looking for 'grep' - found /bin/grep
2018/12/31 11:25:36 Looking for 'kraken' - found /usr/bin/kraken
2018/12/31 11:25:36 Determined kraken version is 0.10.5-beta
2018/12/31 11:25:36 Looking for 'kraken-report' - found /usr/bin/kraken-report
2018/12/31 11:25:36 Determined kraken-report version is 0.10.5-beta
2018/12/31 11:25:36 Looking for 'mafft' - found /usr/bin/mafft
2018/12/31 11:25:36 Determined mafft version is 7.271
2018/12/31 11:25:36 Looking for 'makeblastdb' - found /usr/bin/makeblastdb
2018/12/31 11:25:36 Determined makeblastdb version is 2.2.31
2018/12/31 11:25:36 Looking for 'mcl' - found /usr/bin/mcl
2018/12/31 11:25:36 Determined mcl version is 14-137
2018/12/31 11:25:36 Looking for 'parallel' - found /usr/bin/parallel
2018/12/31 11:25:37 Determined parallel version is 20141022
2018/12/31 11:25:37 Looking for 'prank' - found /usr/bin/prank
2018/12/31 11:25:37 Determined prank version is 150803
2018/12/31 11:25:37 Looking for 'sed' - found /bin/sed
2018/12/31 11:25:37 Looking for 'cdhit' - found /usr/bin/cdhit
2018/12/31 11:25:37 Determined cdhit version is 4.6
2018/12/31 11:25:37 Looking for 'fasttree' - found /usr/bin/fasttree
2018/12/31 11:25:37 Determined fasttree version is 2.1
2018/12/31 11:25:37 Roary version 1.007002

and what does it mean
Use of uninitialized value in require at /usr/lib/x86_64-linux-gnu/perl/5.22/Encode.pm line 59.
