### ISSUE TITLE
Ubuntu 16.04: still version 3.6.0?

### ISSUE THREAD

**Issue by dutchscientist** [sanger-pathogens/Roary#302]
I tried to use apt-get to update Roary on a Ubuntu 16.04 install, but that is still version 3.6.0?

Using the 14.04 instructions, cpan installs 3.7.0.

**Comment by maculatus** [comment]
Same here... I tried to update using apt-get and I got the 3.6.0 version

**Comment by andrewjpage** [comment]
The Debian Med team have packaged the latest version of Roary, but Ubuntu freezes things at a certain time point (as all distributions do). You can always get the latest release from CPAN. I think you can add an extra repository to your apt sources to get the latest update (not sure how).

**Comment by dutchscientist** [comment]
OK, clear. Probably best to change the instructions on the github page then? Otherwise people will miss out on the latest version.

**Comment by andrewjpage** [comment]
I've updated the installation instructions for Ubuntu 16.04.
Andrew
