### ISSUE TITLE
Controlling CD-hit parameters

### ISSUE THREAD

**Issue by dutchscientist** [sanger-pathogens/Roary#303]
I have two paralogs which have an identical C-terminus, but their N-terminus is distinct. The predicted proteins are ~750 aa, and about 500 identical amino acids (first 20 aa, then about 240 aa fairly distinct (40% identity, ~70% similarity) and then the 500 aa 98% identity.

Even when I set Roary to 99% identity at BLAST with the -i option, they get clustered. I assume that this happens at the CD-hit stage, where they are already grouped and hence not subject to BLAST separation?

Can we control the CD-hit settings when running Roary, for instance making it more stringent? Don't see that option in the --help output :)

**Comment by andrewjpage** [comment]
Given the info you have provided I think its more likely to be as a result of MCL rather than CD-hit.  Paralogs are not the easiest thing in the world to deal with, so any pull requests which improve things would be greatly appreciated.

**Comment by Isabelinho** [comment]
But is it possible control the CD-hit settings? Where I can see the default parameters?

**Comment by tseemann** [comment]
Which parameters?
Some of them like `-i` *must* be controlled by `roary` itself in its iteration loop.
