### ISSUE TITLE
Extract core genes of subset A absent in other genomes

### ISSUE THREAD

**Issue by shlomobl** [sanger-pathogens/Roary#307]
Hi,

Thanks for building this tool :-)

Two questions:
1) Is it possible to extract the core genes from a subset of strains, which are absent in the other strains? (the core of the accessory genes specific for that subset???)

2) How may I add more features to the output of query_pan_genome (e.g. gene product)? I guess this is more like a suggestion, it would be nice to have more output file formats in query_pan_genome.

Thanks!

**Comment by andrewjpage** [comment]
You can write a little script and use bedtools to extract out any genes you wish.  As for more features in query_pan_genome, I would welcome any pull requests from you with feature enhancements.
Regards,
Andrew
