### ISSUE TITLE
Use of uninitialized value in require at (eval 792) line 1.

### ISSUE THREAD

**Issue by GermainChev** [sanger-pathogens/Roary#308]
Hello 

I got this when I run roary:

Use of uninitialized value in require at /System/Library/Perl/5.18/darwin-thread-multi-2level/Encode.pm line 60.
Use of uninitialized value in require at /System/Library/Perl/5.18/darwin-thread-multi-2level/Encode.pm line 60.
Use of uninitialized value in require at (eval 792) line 1.

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

And the core_gene_alignment.aln has only fasta header in it without any sequence ...

Thanks for your Help !!

Germain

**Comment by andrewjpage** [comment]
The warning is just a warning from a dependancy of a dependancy in perl. Update your perl modules. 
As for not getting any core genes, that could be an installation issue, or more likely, a data issue.
