### ISSUE TITLE
Change CSV output files to TSV

### ISSUE THREAD

**Issue by oschwengers** [sanger-pathogens/Roary#315]
Hello,
thanks a lot for developing / maintaining Roary! It's a great tool!
Is there a special reason why output files (e.g. gene_presence_absence.csv) are written as quoted comma separated values instead of tab separated values?

As tsv is way easier to parse and slightly more storage efficient it would be great if this could be changed.

**Comment by andrewjpage** [comment]
Hi, we have no plans to change the output format from RFC 4180.
