### ISSUE TITLE
Results for same input differ always a bit (summary_statistics.txt)

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [sanger-pathogens/Roary#318]
I saw this effect on two different roary installations on two different machines; Once on roary 3.8.0 just installed today and an older roary 3.6.0 on another machine.

What I observe is that the results in `summary_statistics.txt` differ slightly. The core genome is always the same size. But shell and cloud genes fluctuate always plus/minus about 5-10 genes. Is this happening while Markov clustering (`mcl`)? Or is it a multi-threading thing?

I guess there is some non deterministic step?

I give the results of two examples calculated with roary 3.8.0 (I have twelve strains, that's why there are no soft core genes):

```
Core genes	(99% <= strains <= 100%)	969
Soft core genes	(95% <= strains < 99%)	0
Shell genes	(15% <= strains < 95%)	1640
Cloud genes	(0% <= strains < 15%)	1535
Total genes	(0% <= strains <= 100%)	4144
```

```
Core genes	(99% <= strains <= 100%)	969
Soft core genes	(95% <= strains < 99%)	0
Shell genes	(15% <= strains < 95%)	1650
Cloud genes	(0% <= strains < 15%)	1527
Total genes	(0% <= strains <= 100%)	4146
```

**Comment by andrewjpage** [comment]
Yes you are correct that mcl is non-deterministic, which makes Roary non-deterministic.

**Comment by MichaelsGITIGIT** [comment]
Thx for the answer!
