### ISSUE TITLE
sampling number is 10 in number of genes in pan and core genome

### ISSUE THREAD

**Issue by ghost** [sanger-pathogens/Roary#319]
How did you pick the number of sampling for the core, pan and new genes plots. Is there any parameter to change. I believe by default roary does 10 samples and from that makes the plots

**Comment by andrewjpage** [comment]
It is 10 and cannot be changed. Increasing it leads to substantially increased running times, but theres very little benefit in terms of the final output (since you can just use graph smoothing in R).
