### ISSUE TITLE
[version 3.8.0] Roary crashes at end on perl error message

### ISSUE THREAD

**Issue by dutchscientist** [sanger-pathogens/Roary#323]
Just updated to v. 3.8.0, and at the end of the run, it suddenly keeps on repeating the following message:

"Use of uninitialized value $filename in hash element at /usr/local/share/perl/5.18.2/Bio/Roary/GroupStatistics.pm line 98."

It is fairly late in the run, i.e. after the Blast comparisons. 

(for info: it is a 5829 genome comparison, 100000 groups, both with 90% and 70% cut-off, paralog clustering disabled)

I also get an earlier Perl error message, after extraction of the proteins and before combining them in  a single file:
"Use of uninitialized value in require at /usr/lib/perl/5.18/Encode.pm line 60."
That does not stop Roary working.

**Comment by thkuo** [comment]
I also got this problem and just found some relevant discussions in #199
It's seemingly not solved yet, so I am trying to install old version instead.

**Comment by dutchscientist** [comment]
I deinstalled and reinstalled, and I don't get the line 98 error message anymore.

However, I do notice that after running and producing the 17 files, memory is filling up and perl keeps on running. Only way to stop my 32 Gb RAM + 32 Gb swap te stop filling is to Ctrl-C the program. Very weird.

Unfortunately there is no older version on CPAN? Would be good to always leave one previous version on CPAN for testing purposes :)

**Comment by andrewjpage** [comment]
Hi @dutchscientist 
You can ignore the warning:
"Use of uninitialized value in require at /usr/lib/perl/5.18/Encode.pm line 60."

CPAN had a space issue and asked module authors do a spring clean. They said theres lots of mirrors which archive all historic versions so theres no need for them to also do it.  I'll keep the last 2 versions from now on.

Thats quite a massive pan genome. You might have insufficient RAM. Another possiblity is with the files themselves. If one is moved, temporarily unavailable (network disk down) or renamed while roary is running it will throw that error.

Andrew

**Comment by dutchscientist** [comment]
Thanks, Andrew. It worked fine with 3.7.0, so size should not be the issue?



Sent from my BlackBerry

**Comment by andrewjpage** [comment]
So the only coding [difference between 3.7.0 and 3.8.0](https://github.com/sanger-pathogens/Roary/compare/v3.7.0...v3.8.0) is a single line removing this parameter from the makeblastdb command:
`-parse_seqids`

In the latest version of blast the functionality of this parameter changed triggering a remote lookup at NCBI (which is silly really). This slowed down roary and introduced the requirement for a live internet connection. So it was removed.  What version of blast are you running?

**Comment by dutchscientist** [comment]
My Biolinux8 still runs v2.2.28. Should that make a difference?
