### ISSUE TITLE
core_genome_reference.fa & query_pan_genome -a difference

### ISSUE THREAD

**Issue by MostafaYA** [sanger-pathogens/Roary#331]
Hi, 

I have a couple of questions please

1.  Is it possible to  get a ref sequence fasta file for the core genome with a single representative sequence, like that one available for pan genome "pan_genome_reference.fa"?

2. "query_pan_genome -a difference" means genes present in set1 genomes but not in set2 or it means genes present set1, not in set2 as well as genes  present in set2 but not in set1?

Thanks a lot,

**Comment by tseemann** [comment]
Yes I agree `2.` is not clear from the docs:

```
Gene differences between sets of isolates
query_pan_genome -a difference --input_set_one 1.gff,2.gff --input_set_two 3.gff,4.gff,5.gff
```

**Comment by MostafaYA** [comment]
got the answer `2` from the original article supp data 

```
4.1.1 Difference between sets of isolates
If you have two sets of isolates, you can use this script to tell what the differences are (in terms
of genes). For example, you might have a set of drug resistant isolates, and another set of
susceptible isolates and you want to know are there genes how they differ. For a given pan
genome, you can pass in two lists of GFF files. It will output what genes are unique to set 1,
unique to set 2 and what they have in common.
query_pan_genome a difference input_set_one 1.gff,2.gff input_set_two 3.gff,4.gff,5.gff g clustered_proteins

The output files are the groups file and a spreadsheet detailing what’s in common and what’s
unique to each set:
● set_difference_unique_set_one_statistics.csv
● set_difference_unique_set_one
● set_difference_unique_set_two_statistics.csv
● set_difference_unique_set_two
● set_difference_common_set_statistics.csv
● set_difference_common_set
```

**Comment by TreeT2** [comment]
Hello,

Just wondering as part of this command how do you deal with basis from replicate gene names from the prokka output. e.g

Some genes may be split across contigs during annotation and labeled like gene_1 and gene_2. This gene could be in sets one and two but for whatever reason gene_2 is only in set one, introducing basis. 

Looking back over my data there is actually inconsistencies in gene names between prokka *fnn *faa Vs *gff and *Rtab files.  e.g. in the fasta files a gene is labelled as >[locus_tag] Invasin and in the gff it is call eae. I have several versions of eae (eae to eae_3) in my presence or absence Rtab with different distribution in the dataset. 

When I compare the gene difference downstream most in set one and two actually come back as closely related

**Comment by andrewjpage** [comment]
The most commonly occurring 'gene' name from the prokka output for the cluster is used. If its already been used for another cluster, a generic name group_XXX is used, and the gene is noted in the second column.   If the underlying assembly has fragmented genes, then theres not much roary can do. Long read sequencing or better assemblies will help, of course.   If you have closely related genes split over two clusters, it might be the paralog splitting functionality. You can turn it off with the -s option.

**Comment by andrewjpage** [comment]
> Is it possible to get a ref sequence fasta file for the core genome with a single representative sequence, like that one available for pan genome "pan_genome_reference.fa"?

Not currently, but you should be able to filter the pan_genome_reference.fa for a list of genes your interested in (like the core) using a simple BioPerl/BioPython/Awk script to achieve the same effect. Or take the first sequence from the core gene alignment fasta, and split it the genes using the header file. Any pull requests with additional functionality will be greatly apprechiated.
