### ISSUE TITLE
use Roary with RAST files

### ISSUE THREAD

**Issue by vladero** [sanger-pathogens/Roary#332]
Hi, we are trying to use roary with annotated genomes from RAST. But we got an error. Did any one succesfully use RAST files with Roary? can any one give the trick to convert RAST files to GFF that Roary can handle?'

Thanks in advance

Best Regards

Victor Ladero

**Comment by Slugger70** [comment]
Hi Victor,
I've never had any success with RAST gffs in Roary.. Nowadays I always use Prokka to annotate my genomes which creates gffs that Roary can read. 
Cheers, Simon.

**Comment by andrewjpage** [comment]
I also understand that Roary should be available with Galaxy shortly, which will provide a point and click interface to going from raw reads to pan genomes.

**Comment by vladero** [comment]
I open this issue because someone from the hekp team of roary said that some users could manage to use RAST files in roary. I tried several modifications directly or with artemis, with no success. Hope some one, if exist, that didi it could give a tip to get it.

Thanks for your answers, I will also follow the galaxy option.

**Comment by mcclaudi** [comment]
Hi Victor,
I have successfully used RAST genomes. I have downloaded both the gff3 files and the nucleotide sequence separately from the RAST server using the export options, then added the line ##FASTA  to the end of the gff files, followed by the actual contigs. Worked fine for me.
Good luck, Claudia

**Comment by vladero** [comment]
Dear Claudia, thanks a lot for your answer. I tried and the RAST files work now with Roary. It was a simple and effective solution.

Thanks to all

Victor

**Comment by mmrec** [comment]
@macclaudi - could you upload an example? - Thanks in advance!

**Comment by mcclaudi** [comment]
Sure, here is one example (I had to change the file format to .txt since the .gff would not upload, but the content is the same)

[RAST_2338.txt](https://github.com/sanger-pathogens/Roary/files/1175883/RAST_2338.txt)

**Comment by mmrec** [comment]
Thank you!

**Comment by tseemann** [comment]
Foiled by gff3/genbnk files without sequence again!
