### ISSUE TITLE
accessory_binary_genes.fa

### ISSUE THREAD

**Issue by kengcher** [sanger-pathogens/Roary#334]
Hi

I ran Roary on a set of B. longum genomes from NCBI (see list) and the accessory_binary_genes.fa file produced only had A and Cs. 

Was wondering if this make sense?

[Bifidobacterium_longum.ncbi_genome_download.log.txt](https://github.com/sanger-pathogens/Roary/files/1110100/Bifidobacterium_longum.ncbi_genome_download.log.txt)

[accessory_binary_genes.fa.txt](https://github.com/sanger-pathogens/Roary/files/1110095/accessory_binary_genes.fa.txt)

**Comment by TreeT2** [comment]
Hi kengcher

the As and Cs are so the fasta file will work with FastTree it is a rough interpretation. See FAQs on the sanger page: "How was the accessory binary tree built?" > https://sanger-pathogens.github.io/Roary/
