### ISSUE TITLE
Roary fixed_input_files and query_pan_genome issues

### ISSUE THREAD

**Issue by dwilko** [sanger-pathogens/Roary#336]
Hi,
This might be related to #298.

I am using Roary version 3.8.2 (on MacOS X) and Roary runs very well and I am able to plot the pan genome (roary_plots.py). All is well at this point.

However, when I investigate the folder titled "fixed_input_files" I notice that one of my input .gff files is missing (the first alphabetical file in any of my input file lists). This doesn't seem to be a problem at first as this 'missing' file is located in the gene_presence_absence.csv output. But, when I then query the difference between two different sets of isolates using query_pan_genome the output is not what I expect. In short, it picks out 1 gene from set one (which is an incorrect difference gene call as it is present in both sets) and nothing in set two. Searching manually there are >10 differences between each set one and two.

I have found a relatively quick fix for the problem above (regarding query_pan_genome) if this helps with the debugging? Re-running Roary but include another .gff file so that it will be first in your list alphabetically (I duplicate my 'first' file and call it 1.gff). This fixes the issue around the "fixed_input_files" and then when I run {query_pan_genome -a difference} followed by my query isolate lists (.gff files) I get the correct differences in the output files. I have confirmed this by checking manually. Only problem with this method is that roary_plots then includes the duplicate isolate.

Finally, thank you very much for providing this software!

Dan

**Comment by andrewjpage** [comment]
Hi Dan,
Thanks for the feedback, much appreciated. The presence of the fixed_input_files folder indicates that you have duplicate identifiers in your input files. When you run Prokka each sample needs to have a unique locus tag for the gene IDs (--locustag), which is the same requirement GenBank/EMBL have for submitting data. This should correct all the issues you've noticed above.
Regards,
Andrew
