### ISSUE TITLE
Cant open file: _clustered.clstr

### ISSUE THREAD

**Issue by menright99** [sanger-pathogens/Roary#339]
Currently having issues running roary on some Pseudomonas genome .gff files using macos terminal with roary etc installed using homebrew. Was working fine and seemed very stable until recently.

Getting the following error:-

Cant open file: _clustered.clstr
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not read file '_clustered': No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /Library/Perl/5.18/Bio/Root/Root.pm:449
STACK: Bio::Root::IO::_initialize_io /Library/Perl/5.18/Bio/Root/IO.pm:270
STACK: Bio::SeqIO::_initialize /Library/Perl/5.18/Bio/SeqIO.pm:499
STACK: Bio::SeqIO::fasta::_initialize /Library/Perl/5.18/Bio/SeqIO/fasta.pm:87
STACK: Bio::SeqIO::new /Library/Perl/5.18/Bio/SeqIO.pm:375
STACK: Bio::SeqIO::new /Library/Perl/5.18/Bio/SeqIO.pm:421
STACK: Bio::Roary::ChunkFastaFile::_input_seqio /Library/Perl/5.18/Bio/Roary/ChunkFastaFile.pm:27
STACK: Bio::Roary::ChunkFastaFile::sequence_file_names /Library/Perl/5.18/Bio/Roary/ChunkFastaFile.pm:48
STACK: Bio::Roary::ParallelAllAgainstAllBlast::_sequence_file_names /Library/Perl/5.18/Bio/Roary/ParallelAllAgainstAllBlast.pm:61
STACK: Bio::Roary::ParallelAllAgainstAllBlast::run /Library/Perl/5.18/Bio/Roary/ParallelAllAgainstAllBlast.pm:112
STACK: Bio::Roary::run /Library/Perl/5.18/Bio/Roary.pm:93
STACK: Bio::Roary::CommandLine::Roary::run /Library/Perl/5.18/Bio/Roary/CommandLine/Roary.pm:302
STACK: /usr/local/bin/roary:14

roary -a output gives:-
2017/08/03 15:03:15 Looking for 'Rscript' - found /usr/local/bin/Rscript
2017/08/03 15:03:15 Determined Rscript version is 3.3
2017/08/03 15:03:15 Looking for 'awk' - found /usr/bin/awk
2017/08/03 15:03:15 Looking for 'bedtools' - found /usr/local/Cellar/bedtools
2017/08/03 15:03:15 Determined bedtools version is 2.26
2017/08/03 15:03:15 Looking for 'blastp' - found /usr/local/bin/blastp
2017/08/03 15:03:15 Determined blastp version is 2.6.0
2017/08/03 15:03:15 Looking for 'grep' - found /usr/bin/grep
2017/08/03 15:03:15 Looking for 'kraken' - found /usr/local/Cellar/kraken
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.18/Bio/Roary/External/CheckTools.pm line 129.
2017/08/03 15:03:15 Determined kraken version is 
2017/08/03 15:03:15 Looking for 'kraken-report' - found /usr/local/bin/kraken-report
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.18/Bio/Roary/External/CheckTools.pm line 129.
2017/08/03 15:03:15 Determined kraken-report version is 
2017/08/03 15:03:15 Looking for 'mafft' - found /usr/local/Cellar/mafft
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.18/Bio/Roary/External/CheckTools.pm line 129.
2017/08/03 15:03:15 Determined mafft version is 
2017/08/03 15:03:15 Looking for 'makeblastdb' - found /usr/local/bin/makeblastdb
2017/08/03 15:03:15 Determined makeblastdb version is 2.6.0
2017/08/03 15:03:15 Looking for 'mcl' - found /usr/local/Cellar/mcl
2017/08/03 15:03:15 Determined mcl version is 14-137
2017/08/03 15:03:15 Looking for 'parallel' - found /usr/local/Cellar/parallel
2017/08/03 15:03:15 Determined parallel version is 20170722
2017/08/03 15:03:15 Looking for 'prank' - found /usr/local/Cellar/prank
2017/08/03 15:03:15 Looking for 'sed' - found /usr/bin/sed
2017/08/03 15:03:15 Looking for 'cd-hit' - found /usr/local/Cellar/cd-hit
2017/08/03 15:03:15 Determined cd-hit version is 4.7
2017/08/03 15:03:15 Looking for 'FastTree' - found /usr/local/Cellar/FastTree
2017/08/03 15:03:15 Determined FastTree version is 2.1
2017/08/03 15:03:15 Roary version 3.8.2

Individual dependencies seem to work ok?

Grateful for any help.

Thanks a lot.

Mark

**Comment by menright99** [comment]
Reinstalled dependancies and roary using conda. Now works great.

**Comment by tseemann** [comment]
@menright99 awesome. can you close this issue now? cheers.
