### ISSUE TITLE
Can "Fixing input GFF files" be parallelized?

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/Roary#342]
```
2017/08/19 15:30:12 Output directory created: roary
2017/08/19 15:30:12 Fixing input GFF files
```

This stage seems to serial, running a  1 core perl script.  
Could it get the GNU parallel treatment?

**Comment by andrewjpage** [comment]
Not without a fairly big refactor. Much of the time can be avoided by setting a unique sample locus tag in prokka ;)

**Comment by tseemann** [comment]
@andrewjpage Prokka has been doing unique locus tags for a while now. Hopefully most people use `v1.12` now.
