### ISSUE TITLE
Use of uninitialized value (Perl)

### ISSUE THREAD

**Issue by mmaesaar** [sanger-pathogens/Roary#345]
The issue is same as stated in #196. Can you explain why I get this message at the end of Roary's run:

`Use of uninitialized value in require at /System/Library/Perl/5.18/darwin-thread-multi-2level/Encode.pm line 60.`

**Comment by tseemann** [comment]
The error is likely a bug in the perl module itself. It doesn't seem to affect roary results.

The error is in this section - and you can see a bugzilla report about it. I don't think we can fix it.

```
# Make a %Encoding package variable to allow a certain amount of cheating
our %Encoding;
our %ExtModule;
require Encode::Config;
#  See
#  https://bugzilla.redhat.com/show_bug.cgi?id=435505#c2
#  to find why sig handers inside eval{} are disabled.
eval {
    local $SIG{__DIE__};
    local $SIG{__WARN__};
    require Encode::ConfigLocal;    #### HERE I THINK
};
```

**Comment by jananiravi** [comment]
Oh, that's a relief. It was worrisome since it said error instead of warning! Thanks for the clarification.
I see a similar error too:
```
Use of uninitialized value in require at /anaconda2/lib/site_perl/5.26.2/darwin-thread-multi-2level/Encode.pm line 61.
Use of uninitialized value in require at (eval 734) line 1.
```

**Comment by dnbaker** [comment]
I encountered this error currently with perl `5.22.1`, while it seems to work correctly if I comment out `require Encode::ConfigLocal;    #### HERE I THINK`. Roary's maintainers suggest simply updating perl Encode, but I wasn't able to get that fix to work.

**Comment by trstickland** [comment]
run the command
   `enc2xs -C`
which should create ConfigLocal.pm for you

**Comment by tseemann** [comment]
OMG THANK YOU @trstickland i've been trying to figure out how to resolve that for YEARS.

**Comment by andrewjpage** [comment]
Thanks @trstickland
