### ISSUE TITLE
[question] Should it take this long?

### ISSUE THREAD

**Issue by Guella** [sanger-pathogens/Roary#352]
Hello, i'm using Roary to make a pan genome of 192 species, all of the same genus.
I started running on a 8 CPU (16 threads) processor with 16gb memory on this thursday (07/09/2017) and its not over yet.
Did I do something wrong? or it should take this long?

Thank you.

**Comment by tseemann** [comment]
That is not very much RAM. It might have gone into disk swap which would slow it down by 1000x.
