### ISSUE TITLE
number_of_conserved_genes.Rtab

### ISSUE THREAD

**Issue by mmaesaar** [sanger-pathogens/Roary#354]
1) I found that after every 100 isolates "number_of_conserved_genes.Rtab" has slight increase in conserved genes counts - could you explain?

![number_of_conserved_genes rtab](https://user-images.githubusercontent.com/20073096/30319223-f88c502e-97b7-11e7-9f20-11c01c845fef.png)

2) If new genes average count 1 then it is not plotted with Rscript?

![new_genes rtab](https://user-images.githubusercontent.com/20073096/30319939-e658b7d8-97b9-11e7-8e82-1d1528fe8412.png)

![unique_vs_new_genes](https://user-images.githubusercontent.com/20073096/30319626-0d28d826-97b9-11e7-950d-92d99dac3212.png)

Thanks!

**Comment by andrewjpage** [comment]
Yes. By default a core gene is defined as being present in 99% of isolates.
As isolates are whole numbers, this leads to steps:

99*0.99 = ceil(98.01) = 99 (a gene is core if it is present in 99 out of 99
isolates).

100*0.99 = ceil(99) = 99 (a gene is core if it is present in  99 out of 100
isolates).

200*0.99 = ceil(198) = 198 (a gene is core if it is present in 198 out of
200 isolates).

You can smooth this in R using your favourite curve fitting algorithm or
can set the core definition to be 100%.
Regards,
Andrew

**Comment by mmaesaar** [comment]
Thanks for the explanation!
