### ISSUE TITLE
Feature Request: Clear error message for duplicated file names

### ISSUE THREAD

**Issue by nickp60** [sanger-pathogens/Roary#363]
Hi,
Just a small request:  I had a large dataset that (unknown to me) contained a few .gff files with the same basename.  When executing, I kept getting the "Could not extract any protein sequences" error, asking me to check whether or not my files actually had a sequence in them.  After renaming the files, the error went away.  I may be the only one to have this issue, but would it be difficult to add a earlier error. something to the effect of "error! basenames of gff files must be unique"?

Thanks for writing Roary!

**Comment by katrielalex** [comment]
+1 to this feature request. In particular, running Prokka with `--outdir foo` makes it generate output files of the form `foo/PROKKA_MMDDYYYY.gff`, so if you directly invoke roary on the results you get this error.
