### ISSUE TITLE
Strange hash in gene_presence_absence.csv

### ISSUE THREAD

**Issue by azufre451** [sanger-pathogens/Roary#364]
Hello,

I've been running Roary 3.11 and I've noticed that the locus tags in the gene_presence_absence.csv file have an hash prepended to the actual locus_tag. 

In Roary 3.8 the file contained the locus_tag directly, and that allowed for precise binding with the original .gff files. However, the format of version 3.11 is very different. 

Is this the normal behaviour of Roary 3.11? How is this hash computed? 

I attach an example of my .csv file.

[roarytest_1.1.csv.zip](https://github.com/sanger-pathogens/Roary/files/1488067/roarytest_1.1.csv.zip)

(using Roary 3.8, the file does not have these hashes)

Thanks!
Moreno

**Comment by andrewjpage** [comment]
It means you have non-unique identifiers in your input set (2 genes have the same locus tag). The solution is to make sure each sample has a unique locus tag (which is what you need if you want to submit data to the public archives).
