### ISSUE TITLE
Ns in core gene alignment

### ISSUE THREAD

**Issue by karchern** [sanger-pathogens/Roary#366]
Hello,

I occasionally  have a stretch of Ns in my core gene alignment. I don't think this makes any sense. Has this issue occured before? I tried searching past issues but didn't find anything.

Thank you.

**Comment by andrewjpage** [comment]
Hi,
If a core gene is absent you will get a stretch of N's. This is because by default the definition of a core gene is that it must be in 99% of isolates, so for that 1% you need to fill in the gap with something to make it all align.

**Comment by karchern** [comment]
Hi Andrew,
thanks for the answer. I always assumed roary filled up missing sites with gaps (- character) by default. I assume it uses "-" when _part_ of a gene is missing and Ns otherwise?

**Comment by andrewjpage** [comment]
Sorry I forgot I changed it recently, its the other way around, a dash is used for a missing gene.

**Comment by karchern** [comment]
I'm using roary 3.8.2. I assume this is not the most recent version. Do you know in which version you flipped? From visual inspection of my core gene alignment, I strongly believe that Ns correspond to entire missing genes and gaps correspond to missing bits of a gene. 

Thank you for the clarification!

**Comment by andrewjpage** [comment]
It was changed in the last release:
https://github.com/sanger-pathogens/Roary/releases

**Comment by karchern** [comment]
Great, thanks for the quick response!
