### ISSUE TITLE
missing CDSs in gene_presence_absence.csv?

### ISSUE THREAD

**Issue by memoriasresiduais** [sanger-pathogens/Roary#367]
Hi,

I have CDSs in the gff files that are absent in the  gene_presence_absence.csv file... Shouldn't all be there?
I don't understand why these are ignored or excluded... I'm using version 3.6.0.
Any thoughts and help will be welcome.
Thanks in advance!
Alexandra

**Comment by andrewjpage** [comment]
Hi,
As a first step could you update to the latest version (3.11.0).
Some things get filtered, like very small CDS's etc...
Andrew

**Comment by memoriasresiduais** [comment]
Thanks for the quick feedback, Andrew. Some of them are large CDS, so it's kind of strange...
I'll update the version and let you know if the problem is solved. Thanks!
Best,
Alexandra

**Comment by andrewjpage** [comment]
If they are large CDS's you should also check that they arent pseudogenes.

**Comment by andrewjpage** [comment]
From version 3.12.0 the minimum gene size has been dropped to 18 nucleotides from 120.

**Comment by memoriasresiduais** [comment]
Thanks for the info, Andrew, and for all the beautiful tools you’ve been developing and sharing with the community!
Have a nice day!

De : andrewjpage [mailto:notifications@github.com]
Envoyé : mercredi 31 janvier 2018 11:05
À : sanger-pathogens/Roary <Roary@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Author <author@noreply.github.com>
Objet : Re: [sanger-pathogens/Roary] missing CDSs in gene_presence_absence.csv? (#367)


From version 3.12.0 the minimum gene size has been dropped to 18 nucleotides from 120.

**Comment by Amilycd** [comment]
Hi, I encountered the same problem as you. Have you solved it? If so, what method did you use?

**Comment by memoriasresiduais** [comment]
Hi there,
I think the new version at the time solved the problem, but as I also found other problems in the grouping of gene families (i.e. identical proteins being split into different groups and different proteins within the same one - see https://github.com/sanger-pathogens/Roary/issues/616), I switched to PanACoTA...
