### ISSUE TITLE
Differences in core_alignment_header.embl and summary_statistics.txt 

### ISSUE THREAD

**Issue by ZiliaMR** [sanger-pathogens/Roary#369]
Hi,

I would like to know why the core alignment that Roary gave me is incomplete ? 
Because according with the file  summary_statistics, the core has: 

Core genes	(99% <= strains <= 100%)	1123
Soft core genes	(95% <= strains < 99%)	107
Shell genes	(15% <= strains < 95%)	336
Cloud genes	(0% <= strains < 15%)	2216
Total genes	(0% <= strains <= 100%)	3782

 But the file alignment has only 158 genes, it is too small. 

Cheers,

**Comment by andrewjpage** [comment]
This is because by default paralogous genes are excluded from the core gene alignment. You can force roary to include them (and only choose one version of the duplicated gene) by using the -ap parameter (newly added)
