### ISSUE TITLE
Sorting in version 3.11.0: uppercase letters first, lowercase second (non-alphabetical)

### ISSUE THREAD

**Issue by dutchscientist** [sanger-pathogens/Roary#371]
I just updated to version 3.11.0, and my first Roary runs show that the samples are now sorted according to case of the letters in the identifier, not alphabetical like in MS-Windows. That is new?

Example: ATCC* before An*

For me that is not helpful, as I alternate between Linux and MS-Windows. Is this by design or by accident, and can this be reversed?

**Comment by andrewjpage** [comment]
I dont recall changing anything recently but it does sound like a sensible
feature. Linux is case sensitive (the correct way), OSX and Windows are
not, which is alway fun.
There is a script bundled with Roary to reorder the spreadsheet with
regards to a tree called roary-pan_genome_reorder_spreadsheet. Give that a
try and see does it help? Or you can upgrade Windows to Linux....

**Comment by dutchscientist** [comment]
Ah, thanks for alerting me to the script. I don't have an opinion on what is correct and what is not, I work with both systems and just need to be sure that the sorting is correct.

But as said, I have not noticed this issue with v3.09, only since the upgrade earlier this week to v3.11.

Upgrading Windows to Linux is not an option. Our IT didn't even allow a dual-boot Windows/Linux computer, so on my analysis PC I have to run Linux via Virtualbox. Sad but true...

**Comment by dutchscientist** [comment]
I just realise that I may have not noticed it before as I commonly give the genomes a code+number rather than using the strain name. This was the first time I didn't do that, and hence I notice it now.

So it may not be a new feature/design, just me not noticing it!

**Comment by andrewjpage** [comment]
Grand thanks for letting me know.

**Comment by dutchscientist** [comment]
Yeah, sorry for the "oops" moment...
