### ISSUE TITLE
python: can't open file 'roary_plots.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by kenken86** [sanger-pathogens/Roary#385]
I'm new for this area. I know it's stupid question but I know how to use roary_plots.py. I try but it's come up with python: can't open file 'roary_plots.py': [Errno 2] No such file or directory. I'm in the wrong path or something?

**Comment by andrewjpage** [comment]
I would recommend you contact your local IT support.

**Comment by Guanguan8** [comment]
同问，解决了吗
