### ISSUE TITLE
query_pan_genome returns Segmentation fault: 11

### ISSUE THREAD

**Issue by JSHuisman** [sanger-pathogens/Roary#393]
Hi,

I installed Roary today and am trying to use it to get at the core genes of a small set of Ecoli samples. 

However, when using `roary -e --mafft -p 8 *.gff' I only get the following files: _uninflated_mcl_groups
blast_identity_frequency.Rtab
_clustered
_clustered.clstr
_combined_files
_combined_files.groups
No `gene_presence_absence.csv' like mentioned on the website.

Also - and potentially worse - whenever I try to run the query_pan_genome command (e.g. `query_pan_genome -a intersection *.gff' but also just with the -h flag) this results in 
Segmentation fault: 11

There were no issues during installation (I followed the conda procedure detailed on the roary website), and `roary -a' shows that all dependencies are installed.

Do you know what could be causing this problem, or what I could do to troubleshoot it? Any help would be much appreciated!

**Comment by tseemann** [comment]
It sounds like one of the dependencies is crashing, as you don't the `gene_presence_absence.csv` which is the most important output file.

Are you sure your conda bin directory is the **first** entry in your path?

What does `echo $PATH | tr ":" "\n" | nl` say?

**Comment by JSHuisman** [comment]
Do you know which dependency that might be? I get no error when running roary: it just finishes without the relevant files.

At the time of my original post anaconda was indeed not the first entry in my path. However, the problem persists even when it is. I am on MacOS (Sierra). 

`echo $PATH | tr ":" "\n" | nl` gives the following:

     1	/Users/username/anaconda2/bin
     2	/Users/username/code/canu/Darwin-amd64/bin
     3	/Users/username/code/bamtools/bin
     4	/Applications/CMake.app/Contents/bin
     5	/Users/username/code/Recycler/bin
     6	/Users/username/perl5/bin
     7	/Users/username/Documents/PhD/Databases/resfinder
     8	/Users/username/Documents/PhD/Databases/plasmidfinder
     9	/Users/username/perl5/perlbrew/bin
    10	/Users/username/code/SPAdes/bin
    11	/usr/local/bin
    12	/usr/bin
    13	/bin
    14	/usr/sbin
    15	/sbin
    17	/usr/local/ncbi/blast/bin
    18	/Library/TeX/texbin
    19	/Users/username/Library/Python/2.7/lib/python/site-packages
    20/Users/username/code/ncbi-blast-2.6.0+/bin
    21	/Users/username/code/quast-4.4/build/lib/quast_libs/bwa
    22/Users/username/code/samtools-1.4
    23/Users/username/code/kraken
    24/Applications/Julia-0.6.app/Contents/Resources/julia/bin

roary -a gives the following version numbers:
Rscript 3.3; bedtools 2.27; blastp 2.6.0; kraken 1.0; kraken-report 1.0; mafft 7.313; makeblastdb 2.6.0; mcl 14-137; parallel 20170422; prank 170427; cd-hit 4.7; FastTree 2.1; Roary 3.12.0

**Comment by andrewjpage** [comment]
Hi,
Could you post the full output of roary -a. It's possibly cd-hit

**Comment by JSHuisman** [comment]
The full output of roary -a:

2018/04/09 10:36:01 Looking for 'Rscript' - found /usr/local/bin/Rscript
2018/04/09 10:36:01 Determined Rscript version is 3.3
2018/04/09 10:36:01 Looking for 'awk' - found /usr/bin/awk
2018/04/09 10:36:01 Looking for 'bedtools' - found /Users/username/anaconda2/bin/bedtools
2018/04/09 10:36:01 Determined bedtools version is 2.27
2018/04/09 10:36:01 Looking for 'blastp' - found /Users/username/anaconda2/bin/blastp
2018/04/09 10:36:01 Determined blastp version is 2.6.0
2018/04/09 10:36:01 Looking for 'grep' - found /usr/bin/grep
2018/04/09 10:36:01 Looking for 'kraken' - found /Users/username/code/kraken/kraken
2018/04/09 10:36:01 Determined kraken version is 1.0
2018/04/09 10:36:01 Looking for 'kraken-report' - found /Users/username/code/kraken/kraken-report
2018/04/09 10:36:01 Determined kraken-report version is 1.0
2018/04/09 10:36:01 Looking for 'mafft' - found /Users/username/anaconda2/bin/mafft
2018/04/09 10:36:02 Determined mafft version is 7.313
2018/04/09 10:36:02 Looking for 'makeblastdb' - found /Users/username/anaconda2/bin/makeblastdb
2018/04/09 10:36:02 Determined makeblastdb version is 2.6.0
2018/04/09 10:36:02 Looking for 'mcl' - found /Users/username/anaconda2/bin/mcl
2018/04/09 10:36:02 Determined mcl version is 14-137
2018/04/09 10:36:02 Looking for 'parallel' - found /Users/username/anaconda2/bin/parallel
2018/04/09 10:36:02 Determined parallel version is 20170422
2018/04/09 10:36:02 Looking for 'prank' - found /Users/username/anaconda2/bin/prank
2018/04/09 10:36:02 Determined prank version is 170427
2018/04/09 10:36:02 Looking for 'sed' - found /usr/bin/sed
2018/04/09 10:36:02 Looking for 'cd-hit' - found /Users/username/anaconda2/bin/cd-hit
2018/04/09 10:36:02 Determined cd-hit version is 4.7
2018/04/09 10:36:02 Looking for 'FastTree' - found /Users/username/anaconda2/bin/FastTree
2018/04/09 10:36:02 Determined FastTree version is 2.1
2018/04/09 10:36:02 Roary version 3.12.0

**Comment by tseemann** [comment]
It seems to look ok. 
Here is mine:
```
2018/04/22 14:47:37 Looking for 'Rscript' - found /home/linuxbrew/.linuxbrew/bin/Rscript
2018/04/22 14:47:37 Determined Rscript version is 3.4
2018/04/22 14:47:37 Looking for 'awk' - found /home/linuxbrew/.linuxbrew/bin/awk
2018/04/22 14:47:37 Looking for 'bedtools' - found /home/linuxbrew/.linuxbrew/bin/bedtools
2018/04/22 14:47:37 Determined bedtools version is 2.27
2018/04/22 14:47:37 Looking for 'blastp' - found /home/linuxbrew/.linuxbrew/bin/blastp
2018/04/22 14:47:37 Determined blastp version is 2.7.1
2018/04/22 14:47:37 Looking for 'grep' - found /usr/bin/grep
2018/04/22 14:47:37 Looking for 'kraken' - found /home/linuxbrew/.linuxbrew/bin/kraken
2018/04/22 14:47:37 Determined kraken version is 1.0
2018/04/22 14:47:37 Looking for 'kraken-report' - found /home/linuxbrew/.linuxbrew/bin/kraken-report
2018/04/22 14:47:37 Determined kraken-report version is 1.0
2018/04/22 14:47:37 Looking for 'mafft' - found /home/linuxbrew/.linuxbrew/bin/mafft
2018/04/22 14:47:37 Determined mafft version is 7.313
2018/04/22 14:47:37 Looking for 'makeblastdb' - found /home/linuxbrew/.linuxbrew/bin/makeblastdb
2018/04/22 14:47:37 Determined makeblastdb version is 2.7.1
2018/04/22 14:47:37 Looking for 'mcl' - found /home/linuxbrew/.linuxbrew/bin/mcl
2018/04/22 14:47:37 Determined mcl version is 14-137
2018/04/22 14:47:37 Looking for 'parallel' - found /home/linuxbrew/.linuxbrew/bin/parallel
2018/04/22 14:47:37 Determined parallel version is 20180322
2018/04/22 14:47:37 Looking for 'prank' - found /home/linuxbrew/.linuxbrew/bin/prank
2018/04/22 14:47:37 Determined prank version is 170427
2018/04/22 14:47:37 Looking for 'sed' - found /home/linuxbrew/.linuxbrew/bin/sed
2018/04/22 14:47:37 Looking for 'cd-hit' - found /home/linuxbrew/.linuxbrew/bin/cd-hit
2018/04/22 14:47:37 Determined cd-hit version is 4.7
2018/04/22 14:47:37 Looking for 'FastTree' - found /home/linuxbrew/.linuxbrew/bin/FastTree
2018/04/22 14:47:37 Determined FastTree version is 2.1
2018/04/22 14:47:37 Roary version 3.12.0
```

**Comment by JSHuisman** [comment]
This issue was resolved after updating my perl installation and all required libraries.
