### ISSUE TITLE
Question: what programs can be used to visualize embl and dot files?

### ISSUE THREAD

**Issue by karinlag** [sanger-pathogens/Roary#394]
According to the documentation, it says that these files can be used for visualizaton. My google foo is having very limited success regarding finding software that I can input these to. Could you give me any tips in this regard?

**Comment by andrewjpage** [comment]
Artemis can visualize embl files. Lots of graph programs can visualize dot files, the one I use is gephi

**Comment by andrewjpage** [comment]
You can also pop the output into phandango or panx to interactivity view data

**Comment by karinlag** [comment]
So, I tried putting a core_accessory.header.embl into Artemis, and it fails, saying the 'entry contains no sequence'. Are there options to roary that I'm not using, and/or other ways of working around this?

And thanks for the tips regarding gephi and phandango/panx :smiley:

**Comment by andrewjpage** [comment]
With Artemis load in the core gene alignment FASTA file, then add the annotation (embl or gff) on top. I think you load the annotation under File->Add Entry.

**Comment by karinlag** [comment]
@andrewjpage Thanks so much for this, this helps a lot!
