### ISSUE TITLE
Roary including non-protein coding features?

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/Roary#398]
As I understand it, Roary uses `cd-hit` and `blastp` and is designed for proteins only.

However, it seems it allows other non-protein-coding features into the mix:
```
default => '(CDS|ncRNA|tRNA|tmRNA|rRNA)'
```
The default should be `CDS` only.

It seems that there is a size filtering step which tends to remove "most" of these features but they can still leak through.

**Comment by embatty** [comment]
I changed this default to just CDS throughout, and it removes the tRNA groups I was seeing in the output. The other issue is that the RNA sequences were getting translated even though they aren't really open reading frames - you could add `-complete => 1 `to the translate function to perform these checks and it would give a warning on anything that doesn't look like a valid protein. That might not be necessary as I assume most people are using sequences annotated by Prokka, and so they will have sensible ORFs in the input files.

**Comment by andrewjpage** [comment]
Thank you @embatty for the pull request which fixes this. I've merged it just now.
