### ISSUE TITLE
gene_presence_absence.csv incomplete

### ISSUE THREAD

**Issue by cgcattctggaatat** [sanger-pathogens/Roary#402]
Hi,

Regardless of how I run roary, the gene_presence_absence.csv file is incomplete. The gene name is always displayed as a 'group' and no annotation is provided.
I have tried using different .gff files (including a set which provided complete output in the past (April 2016), using roary v3.6.0) , which makes me think there is something wrong with my current version of roary (v3.6.2), rather than the .gff files.

How can I get the gene annotations displayed properly in the output?

Thanks

**Comment by mmaesaar** [comment]
You are using very old (more than 2 yo) version of roary. I have had all sort of problems using old versions of roary. No problems have occurred since I have installed the latest version. I would recommend you to update roary.

**Comment by cgcattctggaatat** [comment]
I tried uninstalling and reinstalling with apt-get, but it says the version stayed the same.
I tried to install again using cpanm and it finally upgraded to v3.12.0 and works fine now.
No idea why this didnt work before, sorry.
