### ISSUE TITLE
Tutorial data: extract_proteome_from_gff

### ISSUE THREAD

**Issue by tylerarice** [sanger-pathogens/Roary#403]
Hello,

I'm trying to learn the ropes using the tutorial data (genomes of 6 Listeria isolates), but having some trouble with the .gff files that came out when I ran Prokka.  Thanks for advising how I might troubleshoot.
-Tyler

Tylers-iMac:Roary tutorial tylerrice$ roary -f ./demo -e -n -v *.gff
Use of uninitialized value in require at /Applications/anaconda/lib/perl5/5.22.0/darwin-thread-multi-2level/Encode.pm line 59.

Please cite Roary if you use any of the results it produces:
    Andrew J. Page, Carla A. Cummins, Martin Hunt, Vanessa K. Wong, Sandra Reuter, Matthew T. G. Holden, Maria Fookes, Daniel Falush, Jacqueline A. Keane, Julian Parkhill,
	"Roary: Rapid large-scale prokaryote pan genome analysis", Bioinformatics, 2015 Nov 15;31(22):3691-3693
    doi: http://doi.org/10.1093/bioinformatics/btv421
	Pubmed: 26198102

2018/06/08 14:25:00 Output directory name exists already so adding a timestamp to the end
2018/06/08 14:25:00 Output directory created: ./demo_1528482300
2018/06/08 14:25:00 Fixing input GFF files
2018/06/08 14:25:02 Extracting proteins from GFF files
Extracting proteins from /Users/tylerrice/Documents/YALE/Palm lab/Data/Comparative_Genomics/Roary_tutorial/PROKKA_06082018-2.gff
Extracting proteins from /Users/tylerrice/Documents/YALE/Palm lab/Data/Comparative_Genomics/Roary_tutorial/PROKKA_06082018-3.gff
Extracting proteins from /Users/tylerrice/Documents/YALE/Palm lab/Data/Comparative_Genomics/Roary_tutorial/PROKKA_06082018-4.gff
Extracting proteins from /Users/tylerrice/Documents/YALE/Palm lab/Data/Comparative_Genomics/Roary_tutorial/PROKKA_06082018-5.gff
Extracting proteins from /Users/tylerrice/Documents/YALE/Palm lab/Data/Comparative_Genomics/Roary_tutorial/PROKKA_06082018-6.gff
Extracting proteins from /Users/tylerrice/Documents/YALE/Palm lab/Data/Comparative_Genomics/Roary_tutorial/PROKKA_06082018.gff
Error: Cant access file lab/Data/Comparative_Genomics/Roary_tutorial/demo_1528482300/sIeMCcuPK6
Usage: extract_proteome_from_gff [options] *.gff
Take in GFF files and create FASTA files of the protein sequences

Options: -o STR    output suffix [proteome.faa]
         -t INT    translation table [11]
         -f        filter sequences with missing data
         -v        verbose output to STDOUT
         -d STR    output directory
         -w        print version and exit
         -h        this help message

For further info see: http://sanger-pathogens.github.io/Roary/

...

Combine proteins into a single file
Cant open file: /Users/tylerrice/Documents/YALE/Palm lab/Data/Comparative_Genomics/Roary_tutorial/demo_1528482300/sIeMCcuPK6/PROKKA_06082018-2.gff.proteome.faa

**Comment by tylerarice** [comment]
Thanks Sohini, worked like a charm.

**Comment by lyesinrin** [comment]
Hi, i don't know if this will work for you, but i had the same issue because of spaces in my file names, which i just changed with underscores, hope this will help
