### ISSUE TITLE
Tutorial data: extract_proteome_from_gff 

### ISSUE THREAD

**Issue by sohini5981** [sanger-pathogens/Roary#406]
Hello,
My issue is exactly similar to #403
I have already converted my .fasta files to .gff files.
However when I run 
roary -e --mafft -p 8 *.gff

 I get the following error:

Cant open file: /Users/sohiniguha/Desktop/roary tutorial/gff/ltHxCLGref/USDA122.gff.proteome.faa

I checked and it seems that there Is a transient creation of a file which. then disappears.
I have also done rotary -a.Below is the report:

Please cite Roary if you use any of the results it produces:
    Andrew J. Page, Carla A. Cummins, Martin Hunt, Vanessa K. Wong, Sandra Reuter, Matthew T. G. Holden, Maria Fookes, Daniel Falush, Jacqueline A. Keane, Julian Parkhill,
	"Roary: Rapid large-scale prokaryote pan genome analysis", Bioinformatics, 2015 Nov 15;31(22):3691-3693
    doi: http://doi.org/10.1093/bioinformatics/btv421
	Pubmed: 26198102

2018/07/04 21:26:27 Looking for 'Rscript' - found /usr/local/bin/Rscript
2018/07/04 21:26:27 Determined Rscript version is 3.4
2018/07/04 21:26:27 Looking for 'awk' - found /usr/bin/awk
2018/07/04 21:26:27 Looking for 'bedtools' - found /anaconda3/bin/bedtools
2018/07/04 21:26:27 Determined bedtools version is 2.27
2018/07/04 21:26:27 Looking for 'blastp' - found /anaconda3/bin/blastp
2018/07/04 21:26:27 Determined blastp version is 2.6.0
2018/07/04 21:26:27 Looking for 'grep' - found /usr/bin/grep
2018/07/04 21:26:27 Optional tool 'kraken' not found in your $PATH
2018/07/04 21:26:27 Optional tool 'kraken-report' not found in your $PATH
2018/07/04 21:26:27 Looking for 'mafft' - found /anaconda3/bin/mafft
2018/07/04 21:26:28 Determined mafft version is 7.313
2018/07/04 21:26:28 Looking for 'makeblastdb' - found /anaconda3/bin/makeblastdb
2018/07/04 21:26:28 Determined makeblastdb version is 2.6.0
2018/07/04 21:26:28 Looking for 'mcl' - found /anaconda3/bin/mcl
2018/07/04 21:26:28 Determined mcl version is 14-137
2018/07/04 21:26:28 Looking for 'parallel' - found /anaconda3/bin/parallel
2018/07/04 21:26:28 Determined parallel version is 20170422
2018/07/04 21:26:28 Looking for 'prank' - found /anaconda3/bin/prank
2018/07/04 21:26:28 Determined prank version is 170427
2018/07/04 21:26:28 Looking for 'sed' - found /usr/bin/sed
2018/07/04 21:26:28 Looking for 'cd-hit' - found /anaconda3/bin/cd-hit
2018/07/04 21:26:28 Determined cd-hit version is 4.7
2018/07/04 21:26:28 Looking for 'FastTree' - found /anaconda3/bin/FastTree
2018/07/04 21:26:28 Determined FastTree version is 2.1
2018/07/04 21:26:28 Roary version 3.12.0

Any advice would be great.Thanks in advance

Regards
Sohini

**Comment by kashrest** [comment]
Hi, I got a similar error. How did you resolve this?
