### ISSUE TITLE
moose.pm issue

### ISSUE THREAD

**Issue by KunathBJ** [sanger-pathogens/Roary#407]
Hello,

I'm trying to run Roary. Fun fact, I ran it yesterday and it worked. I run it today, it doesn't (i did uploaded couple of thing for a different software but now, even when I try to install roary from scratch that doesn't work). I'm on ubuntu 14.04

My issue is apparently related to moose.pm. I tried to install it, I ran install_dependencies.sh and I installed the perl dependencies ( sudo cpanm  Array::Utils Bio::Perl Exception::Class File::Basename File::Copy File::Find::Rule File::Grep File::Path File::Slurper File::Spec File::Temp File::Which FindBin Getopt::Long Graph Graph::Writer::Dot List::Util Log::Log4perl Moose Moose::Role Text::CSV PerlIO::utf8_strict Devel::OverloadInfo Digest::MD5::File)

Yet I always have the same issue that says:
Can't locate Moose.pm in @INC (you may need to install the Moose module) (@INC contains: /home/benoit/Roary/t/lib /home/benoit/Roary/lib /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/site_perl/5.28.0/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/site_perl/5.28.0 /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0 /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.28.0/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.28.0) at /home/benoit/Roary/lib/Bio/Roary/CommandLine/Roary.pm line 13.
BEGIN failed--compilation aborted at /home/benoit/Roary/lib/Bio/Roary/CommandLine/Roary.pm line 13.
Compilation failed in require at /usr/local/bin/roary line 12.
BEGIN failed--compilation aborted at /usr/local/bin/roary line 12.

Do you guys have any idea? Thanks a lot!
Ben

**Comment by andrewjpage** [comment]
There are installation instructions for Ubuntu 14.04 in the readme file which might be easier to work with than installation from source.

**Comment by rotheconrad** [comment]
I'm having this same issue right now. Very helpful comment.
