### ISSUE TITLE
issues with running and empty files

### ISSUE THREAD

**Issue by BJCampbelllab** [sanger-pathogens/Roary#411]
Hi-
I just installed and tried roary.  

(base) -bash-4.2$ roary -e --mafft -p 8 /home/bcampbell/pangenome/original_files/SAR11.15/*.gff /home/bcampbell/pangenome/original_files/SAR11.33/*.gff

I got these errors during the run: 
Use of uninitialized value in require at /home/shared/miniconda3/lib/perl5/5.22.0/x86_64-linux-thread-multi/Encode.pm line 59.

makeblastdb: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

blastp: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

I also ran the union, intersection and complement. 

It looks like I did get some files that had data in them (gene_presence_absence.csv, pan_genome_reference.fa, some .Rtab files and summary_statistics.txt ; but many are empty.

So, any suggestions would be greatly appreciated!

**Comment by andrewjpage** [comment]
There is a problem with your ncbi-blast+ installation, likely due to missing libraries. If you run 'blastp' on the command line you will get the same error. Try reinstalling it and if that doesnt work, contact your local IT support for assistance.

Also I notice that your filenames are '.gff'. You'll need to give them a unique name (like sample1.gff).

**Comment by BJCampbelllab** [comment]
Thanks.  We had to reinstall it a few times, and ended up with the long installation version, but it seems to be working now.



Dr. Barbara Campbell
Associate Professor
Graduate Program Coordinator, Microbiology
Department of Biological Sciences
Clemson University
155B Life Sciences Facility
190 Collings Street
Clemson, SC 29634
Bcampb7@clemson.edu<mailto:Bcampb7@clemson.edu>
Phone: 864-656-0559
http://campbelllab.wix.com/campbelllab
From near to far,
from here to there,
funny things are everywhere.
—Dr. Seuss, One Fish Two Fish Red Fish Blue Fish
