### ISSUE TITLE
MSG: Got a sequence without letters. Could not guess alphabet?

### ISSUE THREAD

**Issue by raw937** [sanger-pathogens/Roary#414]
--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

No idea?

**Comment by raw937** [comment]
also core genes looks funny?
Core genes	(99% <= strains <= 100%)	0
Soft core genes	(95% <= strains < 99%)	0
Shell genes	(15% <= strains < 95%)	141
Cloud genes	(0% <= strains < 15%)	9150
Total genes	(0% <= strains <= 100%)	9291

**Comment by tseemann** [comment]
What was the command line and input data?

**Comment by andrewjpage** [comment]
There's a problem with your input dataset and it looks like you have multiple different species/genus. I would recommend you quality control your input data, for example run it through mash or kraken.
