### ISSUE TITLE
Exiting early because number of clusters is too high

### ISSUE THREAD

**Issue by raw937** [sanger-pathogens/Roary#415]
#error 1
Use of uninitialized value in require at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Encode.pm line 69.
#error 2
Number of clusters (75436) exceeds limit (50000). Multifastas not created. Please check the spreadsheet for contamination from different species or increase the --group_limit parameter.
2018/08/09 15:34:36 Exiting early because number of clusters is too high

Prokka gff's
roary -e --mafft -p 8 *.gff -f my_folder

**Comment by andrewjpage** [comment]
The first is a warning and it's from a dependency of a dependency so out of our control. 
The second is a warning to let you know there might be a problem with your input data and the message tells you what to do.

**Comment by raw937** [comment]
How do I fix the dependency of the dependency?

How do I change the --group_limit parameter? What is your suggesting here? 
I can use kraken to check correct?

**Comment by tseemann** [comment]
`         -g INT    maximum number of clusters [50000]`   ?  (from `roary -h`)

**Comment by geraldmoreno993** [comment]
Greeting Dr. Tseeman, i has the same #error 2 only (of above), i did the reccomendation` -g INT    maximum number of clusters [50000] ` but i had the same respons: 

Thanks in advance Dr.

```
Total time: 2.05 seconds Unique: 34/34 Bad splits: 0/31
Number of clusters (45604) exceeds limit (10000). Multifastas not created. Please check the spreadsheet for contamination from different species or increase the --group_limit parameter.
2024/07/08 22:34:52 Exiting early because number of clusters is too high
```

**Comment by andrewjpage** [comment]
In many cases this indicates your data has more than one species or is contaminated. I would start with QC of the data before running roary.

**Comment by geraldmoreno993** [comment]
thank u, effectively, my data was contaminated.  

> In many cases this indicates your data has more than one species or is contaminated. I would start with QC of the data before running roary.
