### ISSUE TITLE
Is it possible to run roary without prokka output files?

### ISSUE THREAD

**Issue by drdee255** [sanger-pathogens/Roary#417]
I have 5 files for each organisms...

1. genome(.fna)
2. genome_feature(.gff)
3. proteins(.faa)
4. protein_features(.gpff)
5. genbank(.gbff) 

I have tried to put all .gff files in one directory and run roary (with default param), it gives me error ----

`Does the file contain the assembly as well as the annotation?
BLAST Database error: No alias or index file found for protein database [/home/drdee/Desktop/roary_tutorial/strepto/gff/8WPpgYUMDG/output_contigs] in search path [/home/drdee/Desktop/roary_tutorial/strepto/gff::]
Use of uninitialized value in require at /usr/lib/x86_64-linux-gnu/perl/5.26/Encode.pm line 61.
Use of uninitialized value in require at /usr/local/share/perl/5.26.1/File/Slurper.pm line 36.
`
Again, I have tried with .gpff files, it throws exception -------- does not look like GFF3 to me.

How can I run roary, without using prokka.

Note:- I had downloaded all files from NCBI.

**Comment by tseemann** [comment]
You need to combine the .gff and the .fna to make a gff3 file. 

The most important things is to ensure the ID in column 1 of the GFF matches *exactly* the ID of the contigs in the FNA file.  In the past NCBI GFFs did **not** match their FASTA files (!).


I just had a look here and it seems the files are good now in the new ASSEMBLY ftp site:
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/002/563/515/GCA_002563515.1_ASM256351v1

So you can do this:

```
cat genome.gff genome.fna) > genome.gff3
```

Then just give roary all the .gff3 files.
