### ISSUE TITLE
Installation through Bioconda not working

### ISSUE THREAD

**Issue by Aron-github** [sanger-pathogens/Roary#418]
Dear developer,

I am trying to download roary through conda, but the system freezes trying to solve the environment once I type "conda install roary". I'm sure my conda environment is up and running since I have other conda enviroment (e.g. prokka) working correctly. Are you aware of any issue on the subject on your side?

Best regards,
Nora

**Comment by tseemann** [comment]
Can you try `conda update --all` first?

**Comment by Aron-github** [comment]
Dear tseemann,

I followed your suggestion and I got a "# All requested packages already installed.". However, no changes in the "conda install roary" result: it keeps freezing trying to solve the environment.

Thank you for your support, any other help would be greatly appreciated.
Best,
Nora

**Comment by tseemann** [comment]
It sounds like your conda environment isn't working properly, or you don't have proper internet access.

Are you using minconda2 or miniconda3 ?
Did you activate your conda environment?
 
You can always `mv miniconda miniconda.old` to try reinstalling. if it doesn't work you can just move it back.

**Comment by Aron-github** [comment]
Dear Tseemann,

are you suggesting that I should activate the conda environment _before_ installing roary? I always do the opposite (activate to use an already installed env).

My sysadm installed miniconda 3 and set up a specific folder for all conda instances, therefore I'm always using the -p version of the commands to link the conda image to the right path. 
So for roary I did:

```
conda create -p $MY_PATH/roary
conda install -p $MY_PATH/roary roary
source activate $MY_PATH/roary
```

From version info: I currently run conda 4.5.11 with python version 2.7.15. 

Thanks again for your support.
Best regards,

Nora

**Comment by tseemann** [comment]
I think you should ask your sysadmin to install roary and ensure it works.

**Comment by Aron-github** [comment]
Dear Tseemann,

with the help of my sysadmin we tryed to circumvent the error. We found that, by specifying the version of roary we needed, the command actually managed to solve the environment
```
conda install -p /pbs/scratch/bis/conda/roary roary=3.12.0
```

Unfortunately, the download issued several warnings:

```
Warning: 8 possible package resolutions (only showing differing packages):
  - bioconda::perl-test-exception-0.43-0, bioconda::perl-test-pod-1.51-0, bioconda::perl-text-diff-1.44-0
  - bioconda::perl-test-exception-0.43-pl5.22.0_0, bioconda::perl-test-pod-1.51-0, bioconda::perl-text-diff-1.44-0
  - bioconda::perl-test-exception-0.43-0, bioconda::perl-test-pod-1.51-0, bioconda::perl-text-diff-1.44-pl5.22.0_0
  - bioconda::perl-test-exception-0.43-pl5.22.0_0, bioconda::perl-test-pod-1.51-0, bioconda::perl-text-diff-1.44-pl5.22.0_0
  - bioconda::perl-test-exception-0.43-0, bioconda::perl-test-pod-1.51-pl5.22.0_0, bioconda::perl-text-diff-1.44-pl5.22.0_0
  - bioconda::perl-test-exception-0.43-pl5.22.0_0, bioconda::perl-test-pod-1.51-pl5.22.0_0, bioconda::perl-text-diff-1.44-pl5.22.0_0
  - bioconda::perl-test-exception-0.43-0, bioconda::perl-test-pod-1.51-pl5.22.0_0, bioconda::perl-text-diff-1.44-0
  - bioconda::perl-test-exception-0.43-pl5.22.0_0, bioconda::perl-test-pod-1.51-pl5.22.0_0, bioconda::perl-text-diff-1.44done
```
This prevented roary to work properly on some test sample when I activated the source:

```
source activate /pbs/scratch/bis/conda/roary
cd $my_test_path
roary -p 8 -f $my_test_path/Roary_output -e -n -r *.gff >roary_EXEC.txt 2> roary_ERR.txt
```
which resulted in the following error:

```
Use of uninitialized value in require at /pbs/scratch/bis/conda/roary/lib/perl5/5.22.0/x86_64-linux-thread-multi/Encode.pm line 59.
2018/09/10 16:04:32 Input file contains duplicate gene IDs, attempting to fix by adding a unique suffix, new GFF in the fixed_input_files directory: /pbs/scratch/bis/test_roary/104-2014_S26.gff
Use of uninitialized value in require at /pbs/scratch/bis/conda/roary/lib/perl5/site_perl/5.22.0/Bio/Roary/CommandLine/RoaryPostAnalysis.pm line 10.
Can't locate File/Find/Rule.pm in @INC (you may need to install the File::Find::Rule module) (@INC contains:  /pbs/scratch/bis/test_roary/Roary_output/lib /pbs/scratch/bis/conda/roary/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi /pbs/scratch/bis/conda/roary/lib/perl5/site_perl/5.22.0 /pbs/scratch/bis/conda/roary/lib/perl5/5.22.0/x86_64-linux-thread-multi /pbs/scratch/bis/conda/roary/lib/perl5/5.22.0 .) at /pbs/scratch/bis/conda/roary/lib/perl5/site_perl/5.22.0/Bio/Roary/CommandLine/RoaryPostAnalysis.pm line 10.
BEGIN failed--compilation aborted at /pbs/scratch/bis/conda/roary/lib/perl5/site_perl/5.22.0/Bio/Roary/CommandLine/RoaryPostAnalysis.pm line 10.
Compilation failed in require at /pbs/scratch/bis/conda/roary/bin/pan_genome_post_analysis line 12.
BEGIN failed--compilation aborted at /pbs/scratch/bis/conda/roary/bin/pan_genome_post_analysis line 12.
```

Any idea on how to solve these issues?

Thanks again for your support.
Best regards,

Nora

**Comment by tseemann** [comment]
I have dug deeper and I think roary on conda is broken and needs to rebuilt again for the recent perl upgrade.

I am trying here:
https://github.com/bioconda/bioconda-recipes/pull/10895

**Comment by Aron-github** [comment]
Dear tseeman,

thanks a lot for your support!
I'll wait for you to be back at me as soon as I can try to download Roary via conda again.

Best,
Nora

**Comment by tseemann** [comment]
It seems to have re-built, but this doesn't mean it will work yet.

Try this:
```
conda update --all
```

**Comment by Aron-github** [comment]
Dear tseeman,

conda freezes again at "Solving the environment" when I try to update all. 
Do you think it could be useful if I try re-creating the environment from the start?

Best regards,
Eleonora

**Comment by tseemann** [comment]
It's not freezing - it can take up to 30 minutes for me sometimes too :(

You could try reinstalling miniconda3 from scratch, yes.

**Comment by Aron-github** [comment]
Dear tseeman,

after waiting for several hours, I had to kill the process of conda update.
The last thing I will do is to try reinstalling miniconda, possibily in a containerized env. (so not to conflict with the one setup by my sysadmin) and see if anything changes.

Any other suggestion would be greatly apreciated.
Best regards,
Nora

**Comment by DolapoA** [comment]
Any news on this issue?
I too cannot get past the solving environment stage to install Roary.

**Comment by andrewjpage** [comment]
Hi @DolapoA 
@tseemann @Slugger70 and myself will be at a Hackathon at the end of next week and will hopefully be able to take a look then.  We do this in our spare time, hence the longer time scales. If you sys admin can help give us some more clues, that would be very helpful.
Regards,
Andrew

**Comment by DolapoA** [comment]
@andrewjpage Okay thanks, just wanted to know if there was something I should be doing.

**Comment by tseemann** [comment]
@slugger70 won't be coming - he has had too many trips this year :-P

**Comment by darwinbandoy** [comment]
Hi Torsten,

Have you managed to make the conda installation working?

**Comment by tseemann** [comment]
@darwinbandoy @Aron-github @DolapoA 

@druvus has rebuilt roary!
https://github.com/sanger-pathogens/gubbins/issues/235

**Comment by Aron-github** [comment]
Dear tseemann,

sweet, now everything seems to work fine! Thank you and @druvus for addressing this!
Best,
Nora
