### ISSUE TITLE
How many .gff files does Roary need?

### ISSUE THREAD

**Issue by DolapoA** [sanger-pathogens/Roary#419]
I was trying to run Roary3.12 with a single .gff file I obtained from running Prokka on my sample, but it popped up with this error:
Error: You need to provide at least 2 files to build a pan genome
Have I misused Prokka and therefore I should have obtained more than 2 .gff files. Or is Roary3.12 playing up? 
I used the standard command to run Roary:
$ Roary *.gff 

In addition I noticed this comment too:
Use of uninitialized value in require at /home/x/miniconda/lib/perl5/5.22.0/x86_64-linux-thread-multi/Encode.pm line 59.

Maybe this is root cause of my problem?

**Comment by andrewjpage** [comment]
A pan-genomes of a single sample is itself, so you need at least 2 samples.
