### ISSUE TITLE
query_pan_genome 'Cant access file' error (Non-Working-Directory inputs)

### ISSUE THREAD

**Issue by SomeoneInParticular** [sanger-pathogens/Roary#421]
Hello Developers,

I have been trying to run roary as part of a Snakemake workflow, and was trying to use query_pan_genome to identify the core genome of subsets of samples in the run. 
Trying to run 
```
'query_pan_genome -a intersection -o path/to/output -g run_tag/annotations/roary/clustered_proteins run_tag/annotations/prokka/file1.gff,run_tag/annotations/prokka/file2.gff'
```
Results in the following error:
```
Error: Cant access file run_tag/annotations/prokka/file1.gff,run_tag/annotations/prokka/file2.gff
```
All of the paths are relative to the working directory of the pipeline, and a double checked that they all existed and were formatted correctly for the program. 

The files in the roary and prokka directories were generated by roary and prokka, respectively, and I have not deleted any of the files they produced (though I did move the roary files into their appropriate directory to bypass issue https://github.com/sanger-pathogens/Roary/issues/404, using the standard bash 'mv' command)

Let me know if you need any other details or information regarding this issue!

Best Regards,

Kalum

P.S. Forgot to mention I had also tried providing full, explicit paths for all directories (rather than paths relative to the working directory); this also did not work.

**Comment by tseemann** [comment]
@SomeoneInParticular I don't think roary works with relative or absolute pths, the gff files need to be in the current directory.

**Comment by SomeoneInParticular** [comment]
Ah, alright. Would the program work with soft linked files then @tseemann?

**Comment by tseemann** [comment]
I think symlinks work yes - i have to do this in Nullarbor to make roary work.

**Comment by SomeoneInParticular** [comment]
I just tried it out; as long as all the symlinks for the gff files are in the same folder it will work happilly. The roary protein_cluster file can be in a different directory, however, which is a bit unusual. 

Thanks for the help!
