### ISSUE TITLE
Pan genome for fungal genomes

### ISSUE THREAD

**Issue by bhanusakhamuri** [sanger-pathogens/Roary#425]
Does roary work for fungal genomes that are annotated?

**Comment by tseemann** [comment]
If roary supported Genbank files it will be trivial to add support, one would just use `$cds->spliced_seq->translate()` to get the proteins.

**Comment by andrewjpage** [comment]
If you want to submit a pull request I would be happy to accept.

**Comment by Lamm-a** [comment]
@tseemann Did you ever happen to do this? Currently looking for a tool to get fungal pan/core genomes

**Comment by teddyaroca** [comment]
This would be quite the useful feature that is not available elsewhere. I looked around and there are not good options to do this with fungal genomes. Same goes for annotations/gene predictions.
