### ISSUE TITLE
Compilation aborted at pan_genome_post_analysis

### ISSUE THREAD

**Issue by annesicard** [sanger-pathogens/Roary#427]
Hello, 

while running roary -e --mafft -p 8 *.gff (roary v.3.12.0), I obtained the following error message:

>Use of uninitialized value $command[0] in pattern match (m//) at /Users/anaconda3/bin/parallel line 9065.
Use of uninitialized value in require at /Users/anaconda3/lib/perl5/site_perl/5.22.0/Bio/Roary/CommandLine/RoaryPostAnalysis.pm line 10.
Can't locate File/Find/Rule.pm in @INC (you may need to install the File::Find::Rule module) (@INC contains:  /Users/Documents/prokka_output/gff_6c/lib /Users/anaconda3/lib/perl5/site_perl/5.22.0/darwin-thread-multi-2level /Users/anaconda3/lib/perl5/site_perl/5.22.0 /Users//anaconda3/lib/perl5/5.22.0/darwin-thread-multi-2level /Users/anaconda3/lib/perl5/5.22.0 .) at /Users/anaconda3/lib/perl5/site_perl/5.22.0/Bio/Roary/CommandLine/RoaryPostAnalysis.pm line 10.
BEGIN failed--compilation aborted at /Users/anaconda3/lib/perl5/site_perl/5.22.0/Bio/Roary/CommandLine/RoaryPostAnalysis.pm line 10.
Compilation failed in require at /Users/anaconda3/bin/pan_genome_post_analysis line 12.
BEGIN failed--compilation aborted at /Users/anaconda3/bin/pan_genome_post_analysis line 12.

**Comment by andrewjpage** [comment]
The software doesnt appear to have been installed correctly and a required dependancy is missing. Try reinstalling using:
cpanm -f Bio::Roary
This will then install the missing perl dependancies.
