### ISSUE TITLE
No gene annotation in gene_presence_absence.csv output  

### ISSUE THREAD

**Issue by dinesh1st** [sanger-pathogens/Roary#428]
Can you please advise me why I am not getting gene annotation in gene_presence_absence.csv output  file? My previous experience was I got the name of all the genes and annotations in this output. However, this time Roary gave me only group numbers.  The difference between these two attempts was earlier one I have used draft genomes and this time I am using complete genomes. Does it make difference?

**Comment by andrewjpage** [comment]
Could you paste the output of `roary -a` ?

**Comment by dinesh1st** [comment]
2018/10/23 22:13:17 Optional tool 'Rscript' not found in your $PATH
2018/10/23 22:13:17 Looking for 'awk' - found /usr/bin/awk
2018/10/23 22:13:17 Looking for 'bedtools' - found /Users/dinesh/anaconda2/bin/bedtools
2018/10/23 22:13:17 Determined bedtools version is 2.27
2018/10/23 22:13:17 Looking for 'blastp' - found /Users/dinesh/anaconda2/bin/blastp
2018/10/23 22:13:20 Determined blastp version is 2.7.1
2018/10/23 22:13:20 Looking for 'grep' - found /usr/bin/grep
2018/10/23 22:13:20 Optional tool 'kraken' not found in your $PATH
2018/10/23 22:13:20 Optional tool 'kraken-report' not found in your $PATH
2018/10/23 22:13:20 Looking for 'mafft' - found /Users/dinesh/anaconda2/bin/mafft
2018/10/23 22:13:20 Determined mafft version is 7.407
2018/10/23 22:13:20 Looking for 'makeblastdb' - found /Users/dinesh/anaconda2/bin/makeblastdb
2018/10/23 22:13:20 Determined makeblastdb version is 2.7.1
2018/10/23 22:13:20 Looking for 'mcl' - found /Users/dinesh/anaconda2/bin/mcl
2018/10/23 22:13:20 Determined mcl version is 14-137
2018/10/23 22:13:20 Looking for 'parallel' - found /Users/dinesh/anaconda2/bin/parallel
2018/10/23 22:13:21 Determined parallel version is 20160622
2018/10/23 22:13:21 Looking for 'prank' - found /Users/dinesh/anaconda2/bin/prank
2018/10/23 22:13:21 Looking for 'sed' - found /usr/bin/sed
2018/10/23 22:13:21 Looking for 'cd-hit' - found /Users/dinesh/anaconda2/bin/cd-hit
2018/10/23 22:13:21 Determined cd-hit version is 4.7
2018/10/23 22:13:21 Looking for 'FastTree' - found /Users/dinesh/anaconda2/bin/FastTree
2018/10/23 22:13:21 Determined FastTree version is 2.1
2018/10/23 22:13:21 Roary version 3.7.0
2018/10/23 22:13:21 Error: You need to provide at least 2 files to build a pan genome
Usage:   roary [options] *.gff

**Comment by andrewjpage** [comment]
It looks like you are running an older version of Roary (released 2 years ago). Please upgrade to the latest version and try again.
