### ISSUE TITLE
Unexpected error code when running Roary as subprocess in Python. Error: You need to provide at least 2 files to build a pan genome 

### ISSUE THREAD

**Issue by slebras** [sanger-pathogens/Roary#433]
Hello,

I have been attempting to use Roary with the subprocess module in python and have been running into the following error:
```
Error: You need to provide at least 2 files to build a pan genome
error code 255
```
this occurs with the following commands: 
```
subprocess.Popen(["roary", "-f", "output", "-p", "4", "gff_directory/*.gff"], shell=False)
# the above translates to the command line: roary -f output -p 4 gff_directory/*.gff
```
a simple call with "ls gff_directory" shows that there are 6 .gff files (the sample gffs from the tutorial. Even the following executes properly:
```
subprocess.Popen(["ls", "gff_directory"], shell=False)
# the above translates to the command line: ls gff_directory
```
To make things more interesting, the following command runs without error:
```
subprocess.Popen("roary -f output -p 4 gff_directory/*.gff", shell=True)
# the above translates to: roary -f output -p 4 gff_directory/*.gff
```

Unfortunately using `shell=True` is ill-advised and can result in unfavorable results. The fundamental difference between `shell=True` and `shell=False` is that when True, the process is called via the linux shell.

Based on what I've tested so far, it seems that the issue is related to Roary and not the subprocess module, primarily based on other command line executing successfully when interacting with the .gff files. 

Thank you for your time,
-Sebastian

**Comment by slebras** [comment]
Forgot to mention:
   Roary version: 3.12.0
   mac OS version: 10.14.1
   python version: 3.5.5

**Comment by andrewjpage** [comment]
Hey,
It's an error with your python I'm afraid. Using the wildcard to expand the
filename is a shell feature. You need to read in the directory and
explicitly pass the filenames. Try glob.
Andrew

**Comment by slebras** [comment]
Thank you so much!
