### ISSUE TITLE
Conda install cd-hit error on MacOS

### ISSUE THREAD

**Issue by mmaesaar** [sanger-pathogens/Roary#457]
After conda install roary -a gives following error:

`2019/09/03 00:54:05 Looking for 'cd-hit' - found /Users/mihkelm/miniconda3/bin/cd-hit
Use of uninitialized value in concatenation (.) or string at /Users/mihkelm/miniconda3/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 131.
2019/09/03 00:54:05 Determined cd-hit version is 
Use of uninitialized value in numeric lt (<) at /Users/mihkelm/miniconda3/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 132.
2019/09/03 00:54:05 Roary needs cd-hit 4.6 or higher. Please upgrade and try again.
`

Could someone help solve this.

**Comment by tseemann** [comment]
What does `cd-hit --version` say?

I am having issues with my brew version of cd-hit at the moment too:
```
cd-hit --version
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/gcc/lib/gcc/8/libgomp.1.dylib
  Referenced from: /usr/local/bin/cd-hit
  Reason: image not found
Abort trap: 6
```

**Comment by mmaesaar** [comment]
`cd-hit --version` gives same result as you described
`conda update --all` did not fix the issue

**Comment by tseemann** [comment]
Well then you need to install `cd-hit` by other means and ensure it is in the `$PATH` before your `miniconda3/bin` folder.

Also do you have a correct channel order?
```
$ cat ~/.condarc
channels:
  - conda-forge
  - bioconda
  - defaults
```

**Comment by mmaesaar** [comment]
@tseemann Everything should be fine, but error still exist. What has happend to roary installation from brew (issue #208)?

**Comment by AndrewCBarnes** [comment]
I'm getting same error running roary -a. 
2019/11/05 19:46:15 Looking for 'cd-hit' - found /Users/andrewbarnes/miniconda3/envs/sanger-pathogens/bin/cd-hit
Use of uninitialized value in concatenation (.) or string at /Users/andrewbarnes/miniconda3/envs/sanger-pathogens/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 131.
2019/11/05 19:46:15 Determined cd-hit version is 
Use of uninitialized value in numeric lt (<) at /Users/andrewbarnes/miniconda3/envs/sanger-pathogens/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 132.
2019/11/05 19:46:15 Roary needs cd-hit 4.6 or higher. Please upgrade and try again.

But I do get correct output from cd-hit --version 
(sanger-pathogens) MacBook-Pro-10:~ andrewbarnes$ cd-hit --version
		====== CD-HIT version 4.8.1 (built on Oct 26 2019) ======

Channel order also seems good:
(sanger-pathogens) MacBook-Pro-10:~ andrewbarnes$ cat ~/.condarc
channels:
  - sanger-pathogens
  - conda-forge
  - bioconda
  - defaults
  - r
Seems like I am overlooking something simple here, but thanks for any insight.

**Comment by tseemann** [comment]
What is the `sanger-pathogens` channel?  That looks like trouble to me. I would delete it. Then run `conda create -n roary_env roary ; conda activate roary`

**Comment by AndrewCBarnes** [comment]
Might be trouble. But did as suggested, deleted channel, cleared environments and built new roary-specific environment. And same problem. Unable to determine version of cd-hit even though cd-hit --version works and roary -w gives 3.12.0. Odd. 
`2019/11/06 13:08:22 Looking for 'sed' - found /usr/bin/sed
2019/11/06 13:08:22 Looking for 'cd-hit' - found /Users/andrewbarnes/miniconda3/envs/roary_env/bin/cd-hit
Use of uninitialized value in concatenation (.) or string at /Users/andrewbarnes/miniconda3/envs/roary_env/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 131.
2019/11/06 13:08:22 Determined cd-hit version is 
Use of uninitialized value in numeric lt (<) at /Users/andrewbarnes/miniconda3/envs/roary_env/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 132.`

`(roary_env) MacBook-Pro-10:~ andrewbarnes$ cd-hit --version
		====== CD-HIT version 4.8.1 (built on Mar  1 2019) ======`

**Comment by tseemann** [comment]
Well, i just checked my CPAN installed version:
```
2019/11/06 14:50:16 Looking for 'cd-hit' - found /home/linuxbrew/.linuxbrew/bin/cd-hit
Use of uninitialized value in concatenation (.) or string at /home/linuxbrew/.linuxbrew/Cellar/roary/3.12.0/perl5/lib/perl5/Bio/Roary/External/CheckTools.pm line 131.
2019/11/06 14:50:16 Determined cd-hit version is
Use of uninitialized value in numeric lt (<) at /home/linuxbrew/.linuxbrew/Cellar/roary/3.12.0/perl5/lib/perl5/Bio/Roary/External/CheckTools.pm line 132.
2019/11/06 14:50:16 Roary needs cd-hit 4.6 or higher. Please upgrade and try again.
```
Same problem! Must have happened when cd-hit 4.8 was released.
I'm wondering if it used to be X.Y and is now X.Y.Z ( 4.8.1 ).
Can you still run roary ?

**Comment by tseemann** [comment]
```
   },
    'cd-hit' => {
        GETVER => "cd-hit -h | grep 'CD-HIT version'",
        REGEXP => qr/version ($BIDEC) /,
        MINVER => "4.6",
    }
```

```
                ====== CD-HIT version 4.8.1 (built on Mar 20 2019) ======
```

**Comment by tseemann** [comment]
SOLUTION:

Edit `/Users/mihkelm/miniconda3/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm`
Go to line 131
Change it to: `REGEXP => qr/version ($BIDEC)/i,`

**Comment by tseemann** [comment]
@puethe i have filed a simple PR to fix this bug for you: https://github.com/sanger-pathogens/Roary/pull/473

**Comment by AndrewCBarnes** [comment]
Top work! Fixed.

**Comment by Rachael-16** [comment]
I have updated the CheckTools.pm with the new fix, I have update gcc to version 6, I have checked by conda channels 
`channels:
  - bioconda
  - conda-forge
  - defaults
  - r`

I'm still getting this error `Use of uninitialized value in concatenation (.) or string at /home/qiime/anaconda3/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 139.
2019/11/08 09:01:17 Determined cd-hit version is 
Use of uninitialized value in numeric lt (<) at /home/qiime/anaconda3/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 140.
2019/11/08 09:01:17 Roary needs cd-hit 4.6 or higher. Please upgrade and try again.`

Any help would be appreciated

**Comment by tseemann** [comment]
```
conda create -n roary_env roary=3.13.0
conda activate roary_env
roary -w
roary -a
```

**Comment by mmaesaar** [comment]
@tseemann your solution worked - thanks. But now when roary is called or roary -w I get following error:

`Use of uninitialized value in require at /Users/mihkelm/miniconda3/envs/roary_env/lib/site_perl/5.26.2/darwin-thread-multi-2level/Encode.pm line 61.`

**Comment by tseemann** [comment]
That "error" can safely be ignored. I get it too. I've tried to fix it, but it's just an "old perl module out of date now" problem.

**Comment by cabrerad** [comment]
I have the same error: " Looking for 'cd-hit' - found /home/cabrerad/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/roary_env/bin/cd-hit
Use of uninitialized value in concatenation (.) or string at /home/cabrerad/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/roary_env/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 131.
2020/01/16 16:16:52 Determined cd-hit version is 
Use of uninitialized value in numeric lt (<) at /home/cabrerad/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/roary_env/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 132.
2020/01/16 16:16:52 Roary needs cd-hit 4.6 or higher. Please upgrade and try again."

I downloaded Roary by doing this:
$ conda create -n roary_env -c conda-forge -c bioconda roary
$ conda activate roary_env

roary version is 3.13.0 and cd-hit version is 4.8.1

I already checked the .pm file ./miniconda3/4.3.27/envs/roary_env/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm and it already has the changes you mentioned above "REGEXP => qr/version\s+($BIDEC)/i'. 
 
How can I solve this? I can't run roary

**Comment by jaybake5** [comment]
Having the same issue as @cabrerad, Roary version is 3.13.0 and cd-hit version is 4.8.1, the CheckTools.pm file has already appears to have been fixed, and still getting the cd-hit error...

Any help would be truly appreciated!

**Comment by Rachael-16** [comment]
@jaybake5  
I think Roary acts a little odd on Debian systems if you're using ubuntu 16.04 or 18.04 I would suggest following in the install instruction here.

https://bioinformaticsreview.com/20190309/installing-roary-and-prokka-on-ubuntu/

I solved this problem by but installing this way and I literally tried everything else including editing the CheckTools.pm file myself.

Make sure you remove the conda install first. 

Hope this helps

**Comment by jaybake5** [comment]
@Rachael-16 thanks for the link! Actually, it turns out that the roary -a check fails, but actually running the program works, with no error messages relating to the cd-hit version.

@cabrerad , did you just try running yours?  It might work for you as well, despite the failed roary -a check...
