### ISSUE TITLE
Input .gff files size and number

### ISSUE THREAD

**Issue by npavlovikj** [sanger-pathogens/Roary#463]
Hi,

I am using Roary with 2 different datasets - one has 1200 .gff files (~7GB) and the second one has 2300 .gff files (~14GB).
Both jobs run for few hours, no errors are produced, and the time and memory resources are not exceeded. 
However, the output files generated from Roary are incomplete - just the _* files are there, and no *.aln and *.newick files.
I ran Roary with subset of these *.gff files (few MBs), and Roary produced all needed files.
Since the subset worked and the formatting of the *.gff files is not an issue, I was wondering whether there are some size and number limitations of the input *.gff files.
The command I am using is `roary -e --mafft -p 12 -cd 99 *.gff -f roary_output`- I also tried lower values of "cd" and "i", but no *.aln and *.newick files were still generated.

I would appreciate if you can let me know what the issue may be, and whether there is a feasible way for me to fix it and use Roary with these bigger datasets.

Thank you,
Natasha

**Comment by tseemann** [comment]
You are probably hitting some RAM limit of `cd-hit-est` or even `mafft` that are used internally to roary.

**Comment by npavlovikj** [comment]
Thanks for the prompt reply @tseemann, and suggestion . Indeed, increasing the RAM memory made Roary finish successfully. The increase in the memory must have been momentary since SLURM and "sacct" did not report it for the previous runs.
