### ISSUE TITLE
Empty core_gene_alignment.aln with normal pan-genome

### ISSUE THREAD

**Issue by therealcooperpark** [sanger-pathogens/Roary#466]
Hello,

I've been using Roary with great success for a while now, but my recent runs have started generating an empty core_gene_alignment.aln file (headers only, no sequences). An example of this is with 7 closely related Listeria Monocytogenes gff files. They've all been annotated using Prokka 1.14.0: 
`prokka <genome> --outdir <dir> --prefix <prefix> --cpus 24`.

Then the gff files are run through Roary 3.11.0:
`roary -p 24 -e -n -z -v -r -f <dir> <gffs>`

I'm not seeing any real errors in Prokka (one log file attached) [prokka.log](https://github.com/sanger-pathogens/Roary/files/3699497/prokka.log)

In Roary, I still don't see any unusual errors with the exception of `MSG: Got a sequence without letters. Could not guess alphabet` (log file attached) 
[roary.log](https://github.com/sanger-pathogens/Roary/files/3699504/roary.log)

The pan-genome itself looks fine:

> Core genes      (99% <= strains <= 100%)        2145
Soft core genes (95% <= strains < 99%)  0
Shell genes     (15% <= strains < 95%)  832
Cloud genes     (0% <= strains < 15%)   5584
Total genes     (0% <= strains <= 100%) 8561
>

But the genes themselves all start with "group" when I look in the `pan_genome_sequences` directory.

Any assistance for this problem would be great!

**Comment by tseemann** [comment]
Roary does not have an `-e` or `-n` option?

**Comment by tseemann** [comment]
`MSG: Got a sequence without letters. Could not guess alphabet` is a bad bioperl warning to see. It means your FASTA files are weird.

**Comment by therealcooperpark** [comment]
Thank you for the response! What a neat coincidence about that genome! Fortunately, a reinstall of Roary addressed this issue. I think one of the dependencies was altered during the installation of other software on our cluster.
