### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by gundizalv** [sanger-pathogens/Roary#467]
I run the command:

roary -o clustered -p 4 *.gff

And I get the following:

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: 'MEPEKKBP_01145' is not a valid frame
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/local/share/perl/5.28.1/Bio/Root/Root.pm:447
STACK: Bio::SeqFeature::Generic::frame /usr/local/share/perl/5.28.1/Bio/SeqFeature/Generic.pm:503
STACK: Bio::Tools::GFF::_from_gff3_string /usr/local/share/perl/5.28.1/Bio/Tools/GFF.pm:624
STACK: Bio::Tools::GFF::from_gff_string /usr/local/share/perl/5.28.1/Bio/Tools/GFF.pm:437
STACK: Bio::Tools::GFF::next_feature /usr/local/share/perl/5.28.1/Bio/Tools/GFF.pm:395
STACK: Bio::Roary::ReformatInputGFFs::_get_ids_for_gff_file /usr/share/perl5/Bio/Roary/ReformatInputGFFs.pm:170
STACK: Bio::Roary::ReformatInputGFFs::fix_duplicate_gene_ids /usr/share/perl5/Bio/Roary/ReformatInputGFFs.pm:54
STACK: Bio::Roary::CommandLine::Roary::run /usr/share/perl5/Bio/Roary/CommandLine/Roary.pm:271
STACK: /usr/bin/roary:14

All dependancies are installed. Could you give me some help?

**Comment by tseemann** [comment]
`MEPEKKBP_01145` looks like a locus_tag from a Prokka annotation.

Can you tell us what `grep -C 8 MEPEKKBP_01145 *.gff` says?

**Comment by gundizalv** [comment]
I get the following:

"Nesterenkonia_Act20.gff-ftsZ: FFPMKDKF_01802	DOGEMODO_02076	NLBGJGJH_01318	EOCKLONN_01568	JCOMBDED_04136	NBEHOIOD_00295	KOOFLHNF_01209	IAPFJDPG_00946	APMNOPNG_01744	AJBGAJDM_00163	CDDFAELE_00392	CEJMFPPK_03626	MBDIOONC_01576	BFCDHBHM_00690	MEPEKKBP_00671
Nesterenkonia_Act20.gff-group_1057: FFPMKDKF_00469	KOOFLHNF_00234	DOGEMODO_00392	NLBGJGJH_00185	IAPFJDPG_01229	CDDFAELE_01645	CEJMFPPK_03175	MBDIOONC_00690	AJBGAJDM_01361	APMNOPNG_01970	BFCDHBHM_00061	EOCKLONN_01840	MEPEKKBP_01449	JCOMBDED_01256	NBEHOIOD_00789
Nesterenkonia_Act20.gff-group_1105: FFPMKDKF_01035	DOGEMODO_00928	NLBGJGJH_01072	CDDFAELE_00951	CEJMFPPK_00321	EOCKLONN_00428	JCOMBDED_00586	NBEHOIOD_02186	KOOFLHNF_00792	IAPFJDPG_00438	MBDIOONC_00951	AJBGAJDM_03066	APMNOPNG_00429	BFCDHBHM_01856	MEPEKKBP_00601
Nesterenkonia_Act20.gff-group_430: FFPMKDKF_00304	NBEHOIOD_00430	DOGEMODO_00556	NLBGJGJH_00439	EOCKLONN_00944	KOOFLHNF_02254	IAPFJDPG_01532	CDDFAELE_01996	CEJMFPPK_00210	MBDIOONC_03491	AJBGAJDM_00578	APMNOPNG_02284	BFCDHBHM_00296	MEPEKKBP_00158	JCOMBDED_01697
Nesterenkonia_Act20.gff-group_20: FFPMKDKF_02234	JCOMBDED_00642	NBEHOIOD_01363	KOOFLHNF_01682	DOGEMODO_00046	NLBGJGJH_01475	EOCKLONN_01937	IAPFJDPG_02132	AJBGAJDM_01102	CDDFAELE_02519	CEJMFPPK_01820	MBDIOONC_03321	APMNOPNG_01124	BFCDHBHM_00969	MEPEKKBP_02045
Nesterenkonia_Act20.gff:group_280: FFPMKDKF_01462	KOOFLHNF_02336	DOGEMODO_02156	NLBGJGJH_00689	CEJMFPPK_01296	EOCKLONN_00013	JCOMBDED_00904	MEPEKKBP_01145	NBEHOIOD_00976	IAPFJDPG_01386	MBDIOONC_01098	AJBGAJDM_01579	APMNOPNG_00617	BFCDHBHM_00223	CDDFAELE_01923
Nesterenkonia_Act20.gff-group_87: FFPMKDKF_00464	DOGEMODO_00397	NLBGJGJH_00190	EOCKLONN_01845	NBEHOIOD_00794	BFCDHBHM_00066	JCOMBDED_03266	CEJMFPPK_03170	MBDIOONC_00685	MEPEKKBP_01444	KOOFLHNF_00229	CDDFAELE_01650	IAPFJDPG_01234	AJBGAJDM_01366	APMNOPNG_01975
Nesterenkonia_Act20.gff-group_86: FFPMKDKF_00446	DOGEMODO_00416	MEPEKKBP_01868	NLBGJGJH_00208	EOCKLONN_01863	CEJMFPPK_03752	KOOFLHNF_00211	CDDFAELE_01668	JCOMBDED_02302	NBEHOIOD_00816	IAPFJDPG_01252	AJBGAJDM_01384	APMNOPNG_01993	BFCDHBHM_00086	MBDIOONC_00667
Nesterenkonia_Act20.gff-group_26: FFPMKDKF_00235	DOGEMODO_00639	NLBGJGJH_02375	EOCKLONN_01033	JCOMBDED_01982	NBEHOIOD_02031	KOOFLHNF_02169	BFCDHBHM_01652	IAPFJDPG_01621	AJBGAJDM_02433	APMNOPNG_02206	CDDFAELE_02132	CEJMFPPK_02964	MBDIOONC_00523	MEPEKKBP_01599
Nesterenkonia_Act20.gff-group_31: FFPMKDKF_00473	DOGEMODO_00389	NLBGJGJH_00182	EOCKLONN_01837	JCOMBDED_01262	NBEHOIOD_00785	BFCDHBHM_00057	MBDIOONC_01318	KOOFLHNF_00237	CDDFAELE_01642	IAPFJDPG_01226	AJBGAJDM_02239	APMNOPNG_01967	CEJMFPPK_03178	MEPEKKBP_01016
Nesterenkonia_Act20.gff-group_1104: FFPMKDKF_01034	NBEHOIOD_02187	KOOFLHNF_00791	DOGEMODO_00927	NLBGJGJH_01073	IAPFJDPG_00437	CDDFAELE_00952	MBDIOONC_00952	AJBGAJDM_03065	APMNOPNG_00430	BFCDHBHM_01855	EOCKLONN_00429	MEPEKKBP_00602	JCOMBDED_00587	CEJMFPPK_00322
Nesterenkonia_Act20.gff-group_70: FFPMKDKF_00474	DOGEMODO_00388	BFCDHBHM_00056	EOCKLONN_01836	NLBGJGJH_00181	MBDIOONC_01317	APMNOPNG_01966	KOOFLHNF_00238	CDDFAELE_01641	NBEHOIOD_00784	CEJMFPPK_03179	MEPEKKBP_01017	IAPFJDPG_01225	AJBGAJDM_02240	JCOMBDED_03787
Nesterenkonia_Act20.gff-group_64: FFPMKDKF_02633	DOGEMODO_02275	NLBGJGJH_02712	EOCKLONN_00882	MEPEKKBP_01330	CEJMFPPK_01943	JCOMBDED_02801	NBEHOIOD_01632	KOOFLHNF_00640	CDDFAELE_01139	IAPFJDPG_00333	AJBGAJDM_00033	APMNOPNG_00746	MBDIOONC_00860	BFCDHBHM_02144
Nesterenkonia_Act20.gff-group_1115: FFPMKDKF_01225	NBEHOIOD_00562	KOOFLHNF_00958	DOGEMODO_01055	NLBGJGJH_00865	IAPFJDPG_00596	CDDFAELE_00770	CEJMFPPK_00010	AJBGAJDM_00701	APMNOPNG_01512	BFCDHBHM_00490	EOCKLONN_00242	MEPEKKBP_01123	JCOMBDED_02479	MBDIOONC_02493
--
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	4779	5426	.	-	0	ID=MEPEKKBP_01137;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:EXF26003.1;locus_tag=MEPEKKBP_01137;product=energy transducer TonB
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	5535	6653	.	-	0	ID=MEPEKKBP_01138;inference=ab initio prediction:Prodigal:2.6;locus_tag=MEPEKKBP_01138;product=hypothetical protein
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	6919	7575	.	+	0	ID=MEPEKKBP_01139;inference=ab initio prediction:Prodigal:2.6;locus_tag=MEPEKKBP_01139;product=hypothetical protein
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	7585	7803	.	-	0	ID=MEPEKKBP_01140;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:KUG58769.1;locus_tag=MEPEKKBP_01140;product=DNA-binding protein
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	8081	8827	.	+	0	ID=MEPEKKBP_01141;inference=ab initio prediction:Prodigal:2.6;locus_tag=MEPEKKBP_01141;product=hypothetical protein
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	8824	10689	.	+	0	ID=MEPEKKBP_01142;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:PRZ14181.1;locus_tag=MEPEKKBP_01142;product=MinD-like ATPase involved in chromosome partitioning or flagellar assembly
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	10797	15638	.	+	0	ID=MEPEKKBP_01143;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:OSM44224.1;locus_tag=MEPEKKBP_01143;product=glutamate dehydrogenase
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	15642	17162	.	+	0	ID=MEPEKKBP_01144;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:OSM44225.1;locus_tag=MEPEKKBP_01144;product=ATPase
Nesterenkonia_sp._F.gff:NZ_AFRW01000086.1	Prodigal:2.6	CDS	17274	17522	.	-	0	ID=MEPEKKBP_01145;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:EXF25896.1;locus_tag=MEPEKKBP_01145;product=WhiB family transcriptional regulator
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	17947	18405	.	+	0	ID=MEPEKKBP_01146;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:EXF25895.1;locus_tag=MEPEKKBP_01146;product=membrane protein
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	18454	18876	.	-	0	ID=MEPEKKBP_01147;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:OSM44228.1;locus_tag=MEPEKKBP_01147;note=DUF1844 domain-containing protein;product=hypothetical protein
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	19043	19660	.	+	0	ID=MEPEKKBP_01148;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:OSM44229.1;locus_tag=MEPEKKBP_01148;product=translation initiation factor IF-3
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	19995	20189	.	+	0	ID=MEPEKKBP_01149;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:EXF25886.1;locus_tag=MEPEKKBP_01149;product=50S ribosomal protein L35
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	20409	20789	.	+	0	ID=MEPEKKBP_01150;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:RJN31831.1;locus_tag=MEPEKKBP_01150;product=50S ribosomal protein L20
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	21235	21954	.	+	0	ID=MEPEKKBP_01151;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:TLQ00352.1;locus_tag=MEPEKKBP_01151;product=RNA methyltransferase
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	22114	22257	.	+	0	ID=MEPEKKBP_01152;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:PRZ14160.1;locus_tag=MEPEKKBP_01152;product=RNHCP domain-containing protein
Nesterenkonia_sp._F.gff-NZ_AFRW01000086.1	Prodigal:2.6	CDS	22506	23408	.	-	0	ID=MEPEKKBP_01153;eC_number=1.14.11.55;Name=thpD;gene=thpD;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:TLQ00287.1;locus_tag=MEPEKKBP_01153;product=ectoine hydroxylase"

**Comment by gundizalv** [comment]
[output_grep.txt](https://github.com/sanger-pathogens/Roary/files/3736960/output_grep.txt)

**Comment by tseemann** [comment]
```
Nesterenkonia_sp._F.gff:NZ_AFRW01000086.1	Prodigal:2.6	CDS	17274	17522	.	-	0	ID=MEPEKKBP_01145;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:EXF25896.1;locus_tag=MEPEKKBP_01145;product=WhiB family transcriptional regulator
```
All looks normal - `frame` is `0`.

**Comment by gundizalv** [comment]
But, what about the error. The run ends inmediatly without output files and folder named "clustered"

**Comment by gundizalv** [comment]
I found the problem. 
One of the input files was wrong. 
Thanks

**Comment by tseemann** [comment]
@gundizalv can you close this issue please?
