### ISSUE TITLE
Missing one input in gene_presence_absence.csv

### ISSUE THREAD

**Issue by jackchen129** [sanger-pathogens/Roary#472]
I had 25 input gff files for Roary, but one of them was always missing in the generated gene_presence_absence.csv file. But when I included this missing gff file with 2 of these 25 files as a simple test for Roary, it showed up in the gene_presence_absence.csv file, which means there should be nothing wrong with this gff file.

Please advise how to solve this problem.

Thanks.

**Comment by tseemann** [comment]
Please re-run your roary command and save all the output to a file and attach it to this issue.

eg. `roary -v  ....... 2>&1 | tee roary_log.txt` 

And upload `roary_log.txt`.

**Comment by jackchen129** [comment]
Thank you, Torsten! I have fixed this problem by keeping the original PROKKA file name for this input.

**Comment by tseemann** [comment]
Great news !
can you close this issue now please?
