### ISSUE TITLE
Few core genes, a big number of total genes

### ISSUE THREAD

**Issue by gundizalv** [sanger-pathogens/Roary#474]
I want to use roary to get unique genes from a particular Nesterenkonia strain

Summary_statistics.txt file give me the following results:

Core genes      (99% <= strains <= 100%)        14
Soft core genes (95% <= strains < 99%)  0
Shell genes     (15% <= strains < 95%)  994
Cloud genes     (0% <= strains < 15%)   39170
Total genes     (0% <= strains <= 100%) 40178

I have a problem with that, I guess, since when I check for unique genes in my strain of interest I have thousands. 

The number of contigs from each strain was the following:

Nesterenkonia_alba_DSM_19423.fna: **36**
Nesterenkonia_aurantiaca_DSM_27373.fna: **25**
Nesterenkonia_jeotgali_CD08_7.fna: **8**
Nesterenkonia_massiliensis_NP1.fna: **19**
Nesterenkonia_populi_DSM_27959.fna: **2**
Nesterenkonia_sandarakina_CG_35.fna: **56**
Nesterenkonia_sp._AN1.fna: **42**
Nesterenkonia_sp._F.fna:  **138**
Nesterenkonia_sp._GY074.fna:  **140**
Nesterenkonia_sp._GY239.fna:   **89**
Nesterenkonia_sp._JCM_19054.fna:   **1086**
Nesterenkonia_sp._M8.fna:   **11**
Nesterenkonia_sp._NBAIMH1.fna:    **1**
Nesterenkonia_sp._PF2B19.fna:     **509**
Nesterenkonia_sp._RB2.fna:     **57**

Which genomes I'd remove from the analysis? I mean, taking account of your argument about number of contigs, what's the threshold?

**Comment by tseemann** [comment]
It depends on the size of your genome. But the simplest thing is to look at the distribution of contig numbers in your set of samples, and remove all outliers. 1086 and 509 are clearly too many.  But are they all using the _same_ minimum-contig-size in those statistics?  The 140 and 138 are probably ok.

**Comment by gundizalv** [comment]
I removed the worst assembled genomes from the roary input but I still getting 10-14 core genes. What could be happening?

**Comment by tseemann** [comment]
Nesterenkonia is probably too diverse. Roary is for _intra-species_ only.
