### ISSUE TITLE
"roary" running time benchmark

### ISSUE THREAD

**Issue by npavlovikj** [sanger-pathogens/Roary#479]
Hi,

I am using Roary 3.12 on ~20,000 GFF files with 12 threads and 900GB of RAM. "roary" has been running for 9 days. I was wondering if there is any way or setting I can use to improve the running time and whether you have some benchmarking of how long it will actually take to finish these analysis.
The command I am using is `roary -e --mafft -p 12 -cd 99.0 -i 95 -f roary_output *.gff`

Thank you,
Natasha

**Comment by tseemann** [comment]
@npavlovikj roary is unlikely to ever finish with that many genomes, especially if the genomes are somewhat divergent.    Roary only works within species.

The second stage of roary is an ALL VERSUS ALL blast step.  So if you have 20,000 genomes, each with 5,000 proteins, that is 100,000,000 sequences (100 M or 10^8). Comparing all those to each other takes 100M x 100M comparisons, which is 10^16 = 10,000,000,000,000,000.  It's just far too much.

What are you trying to achieve?

Maybe consider other linear time clustering algorithms:
https://github.com/soedinglab/MMseqs2

**Comment by andrewjpage** [comment]
Roary has been run on over 10k genomes before and the resource usage you have posted sounds too high. The best way to speed up the software is to QC your data throughly, because as @tseemann points out, there is an explosion in comparisons.  So make sure all your samples are from a single species by checking with kraken or mash (dont trust the taxon from NCBI), make sure the assemblies are reasonable quality, e.g. exclude genomes which are very small or very big, or are heavily fragmented, have too many CDS etc...  You may already have intermediate output files which will give you an indication of the number of clusters (summary file).

**Comment by npavlovikj** [comment]
Hi @tseemann and @andrewjpage ,

Thank you so much for your prompt replies!

We are performing population genomics analysis of all serovars of Salmonella enterica, and want to do GWAS (probably with Scoary).
We do quality check on the raw reads, do assembly with "spades", use "quast" for assessing the quality of the assemblies, and we further remove assemblies that are fragmented and with low quality before we use "prokka".
Thus, I believe the GFF files used with "roary" are with good quality.

Is it possible to use clusters obtained from other tool, e.g. "mmseqs2", with "roary"?
I am using "mafft" instead of "prank" for MSA, which should be faster according to the documentation.

These are the files I already have in the output directory:
```
[npavlovikj@login.crane ~]$ ls -1a roary_output/
.
..
1IHIbVDWUP
5WtIpYBkkf
accessory_binary_genes.fa
blast_identity_frequency.Rtab
cfF5tM_ciL
_clustered
_clustered.clstr
clustered_proteins
_combined_files
_combined_files.groups
gedU7QW1VV
_inflated_mcl_groups
_inflated_unsplit_mcl_groups
jJhKZuMT4d
_labeled_mcl_groups
lNchUG4_nC
Lvq24yC9B_
_uninflated_mcl_groups
```

I can do `roary -qc` against KRAKEN to verify the quality of the genomes, but if you have any other suggestions, please let me know.

Thank you,
Natasha

**Comment by tseemann** [comment]
`mash triangle` followed by `quicktree` or `rapidnj` is a good way to break your 20k samples into appropriate clades to analyse independently.

What scientific question are you wanting to answer by putting 20K genomes into Roary?

**Comment by andrewjpage** [comment]
It looks like its working on splitting paralogs. You can turn this off by using -s.  If you take a look at the clustered_proteins file, it should tell you how many clusters there are (1 per line).  I think the _combined_files.groups file will just contain the 'core' genes. With Salmonella enterica you should get about 2000 core gene.  A quicker way might be to take the Salmonella wgMLST from Enterobase https://enterobase.warwick.ac.uk/species/index/senterica and compare your data to it?

**Comment by zhenghualiu** [comment]
How many gene clusters generated by CD-hit with your ~20,000 GFF files? 
I am running Roary 3.12 with ~8,000 GFF files and there were 28 M gene clusters for these files. I am wondering if this task can be finished in one month with 24 threads (1.9G Hz) and 450 GB of RAM. 
Looking forward to your kind replies.

**Comment by andrewjpage** [comment]
Roary current has a default upper limit of 50,000 (you can change it). 50,000 gene clusters is very high for a set pan-genome of closely related strains. If you are getting 28 million gene clusters, that indicates you are not looking at a set of closely related strain as each sample is contributing ~3,500 novel gene clusters. I would recommend you stop and reevaluate your research question and find the tools most appropriate to answer it.

**Comment by EllistonV** [comment]
How do I write the "mash triangle" result into a file?
