### ISSUE TITLE
detection of cd-hit version

### ISSUE THREAD

**Issue by thkuo** [sanger-pathogens/Roary#480]
The regex pattern for detecting cd-hit version caused me some problem, which was solved by changing it to `qr/version\s+($BIDEC)/i` (the position of 'i'). 
https://github.com/sanger-pathogens/Roary/blob/225d24ff96a3ee5bbb7f76ef3b66ee61c33a00ce/lib/Bio/Roary/External/CheckTools.pm#L100

**Comment by tseemann** [comment]
Ironically, I think i made that typo when trying to fix this original problem :-(

https://github.com/sanger-pathogens/Roary/commit/0c433a1869624ed9fa22764e9828fb86cc1cd4eb#diff-dbf052cd0060f3fa6d54a7da73d348eb

**Comment by peterjc** [comment]
Seeing:

```
$ roary -a
...
2020/10/07 14:14:23 Looking for 'cd-hit' - found /mnt/shared/scratch/pcock/apps/conda/bin/cd-hit
Use of uninitialized value in concatenation (.) or string at /mnt/shared/scratch/pcock/apps/conda/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 131.
2020/10/07 14:14:24 Determined cd-hit version is 
Use of uninitialized value in numeric lt (<) at /mnt/shared/scratch/pcock/apps/conda/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 132.
2020/10/07 14:14:24 Roary needs cd-hit 4.6 or higher. Please upgrade and try again.
...
```

I have cd-hit 4.8.1, either I did it wrong or the suggested fix is not enough?

**Comment by peterjc** [comment]
Looks like #503 only fixed one of the two REGEX

**Comment by peterjc** [comment]
Working now, PR pending...

**Comment by peterjc** [comment]
Looks like the version in Git should work, time for a point release and this issue can be closed?

**Comment by thkuo** [comment]
Thanks for fixing
