### ISSUE TITLE
problem with conda install

### ISSUE THREAD

**Issue by vjmorley** [sanger-pathogens/Roary#499]
I am having an issue installing with conda on MacOS.

`roary -a`

gives the following output:

`2020/04/03 18:31:18 Looking for 'Rscript' - found /usr/local/bin/Rscript
2020/04/03 18:31:18 Determined Rscript version is 3.6
2020/04/03 18:31:18 Looking for 'awk' - found /usr/bin/awk
2020/04/03 18:31:18 Looking for 'bedtools' - found /Users/val/opt/anaconda3/bin/bedtools
2020/04/03 18:31:18 Determined bedtools version is 2.29
2020/04/03 18:31:18 Looking for 'blastp' - found /Users/val/opt/anaconda3/bin/blastp
2020/04/03 18:31:19 Determined blastp version is 2.9.0
2020/04/03 18:31:19 Looking for 'grep' - found /usr/bin/grep
2020/04/03 18:31:19 Looking for 'kraken' - found /usr/local/bin/kraken
2020/04/03 18:31:19 Determined kraken version is 1.1.1
2020/04/03 18:31:19 Looking for 'kraken-report' - found /usr/local/bin/kraken-report
2020/04/03 18:31:19 Determined kraken-report version is 1.1.1
2020/04/03 18:31:19 Looking for 'mafft' - found /Users/val/opt/anaconda3/bin/mafft
2020/04/03 18:31:19 Determined mafft version is 7.455
2020/04/03 18:31:19 Looking for 'makeblastdb' - found /Users/val/opt/anaconda3/bin/makeblastdb
2020/04/03 18:31:19 Determined makeblastdb version is 2.9.0
2020/04/03 18:31:19 Looking for 'mcl' - found /Users/val/opt/anaconda3/bin/mcl
2020/04/03 18:31:19 Determined mcl version is 14-137
2020/04/03 18:31:19 Looking for 'parallel' - found /Users/val/opt/anaconda3/bin/parallel
2020/04/03 18:31:19 Determined parallel version is 20200322
2020/04/03 18:31:19 Looking for 'prank' - found /Users/val/opt/anaconda3/bin/prank
2020/04/03 18:31:19 Determined prank version is 170427
2020/04/03 18:31:19 Looking for 'sed' - found /usr/bin/sed
2020/04/03 18:31:19 Looking for 'cd-hit' - found /Users/val/opt/anaconda3/bin/cd-hit
Use of uninitialized value in concatenation (.) or string at /Users/val/opt/anaconda3/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 131.
2020/04/03 18:31:19 Determined cd-hit version is 
Use of uninitialized value in numeric lt (<) at /Users/val/opt/anaconda3/lib/site_perl/5.26.2/Bio/Roary/External/CheckTools.pm line 132.
2020/04/03 18:31:19 Roary needs cd-hit 4.6 or higher. Please upgrade and try again.
2020/04/03 18:31:19 Looking for 'FastTree' - found /Users/val/opt/anaconda3/bin/FastTree
2020/04/03 18:31:19 Determined FastTree version is 2.1
2020/04/03 18:31:19 Roary version 3.13.0`

I have tried installing cd-hit separately, and I have tried running

`conda update --all
`

and reinstalling, but that hasn't done the trick. Do you have any suggestions?

**Comment by vjmorley** [comment]
Quick update: 

`roary *.gff`

does run without errors and produce output files. Do I need to be concerned about the warnings with the test above?

**Comment by mmaesaar** [comment]
I had the same issue on Mac. The issue was resolved using following steps:
1) Uninstall current conda roary installation:
`conda remove roary`
2) Install roary environment using:
`conda create --name roary_env roary`
3) Activate created environment:
`conda activate roary_env`
4) Run to see if everything is working as it should:
`roary -a`

**Comment by vjmorley** [comment]
Thanks. I followed the steps from mmaesaar above, but I am still getting the same error message when I test roary.

**Comment by vjmorley** [comment]
As an update, roary does run and produce output files, but it gives warnings.

`roary *.gff`

gives the output

```
Use of uninitialized value in require at /Users/val/opt/anaconda3/envs/roary_env/lib/site_perl/5.26.2/darwin-thread-multi-2level/Encode.pm line 61.

Use of uninitialized value in require at /Users/val/opt/anaconda3/envs/roary_env/lib/site_perl/5.26.2/darwin-thread-multi-2level/Encode.pm line 61.
```

I'm not sure whether I need to be concerned here.

**Comment by mmaesaar** [comment]
@vjmorley I have same error when `roary -a`, but it can be safely ignored:

> That "error" can safely be ignored. I get it too. I've tried to fix it, but it's just an "old perl module out of date now" problem.
> 
> _Originally posted by @tseemann in https://github.com/sanger-pathogens/Roary/issues/457#issuecomment-557856526_

Is the error regarding cd-hit gone: `Roary needs cd-hit 4.6 or higher. Please upgrade and try again.` If not check the issue #457 

> If the problem still exists please check:
> ```
> conda update --all
> 
> # OR
> 
> conda create -n roary_env roary=3.13.0
> conda activate roary_env
> roary -w
> roary -a
> conda deactivate
> ```
> 
> _Originally posted by @tseemann in https://github.com/sanger-pathogens/Roary/issues/457#issuecomment-552074651_

OR

> What is the `sanger-pathogens` channel?  That looks like trouble to me. I would delete it.
>  ```
> conda config --remove channels sanger-pathogens
> conda create -n roary_env roary
> conda activate roary_env
> roary -w 
> # hopefully it says 3.12.0
> roary -a
> ```
> 
> _Originally posted by @tseemann in https://github.com/sanger-pathogens/Roary/issues/457#issuecomment-550105242_

**Comment by vjmorley** [comment]
Great. Thanks so much for your reply @mmaesaar .
