### ISSUE TITLE
is roary only for strains from the same species?

### ISSUE THREAD

**Issue by limin321** [sanger-pathogens/Roary#514]
Hi, 

I read the roary paper indicating it is applied to similar strains where they are in the same species.

My bacterial is is for sure the same genus, but the taxonomy is still debating, so people call it for example, Agrobacterium tumefaciens complex. 

In this case, I am not positive if all my strains can be considered in the same species. Will you still recommend to use roary??

Roary seems a very straightforward pipeline. Could you please explain how strict it is to decide which population I can choose roary.

Really appreciate your help.

Best,

**Comment by tseemann** [comment]
The documentation states it is only for "within species"
This is code for "not very divergent", say 10-20% at the DNA level.
Have you done a ANI (or FastANI) analysis of your genomes.

**Comment by limin321** [comment]
> The documentation states it is only for "within species"
> This is code for "not very divergent", say 10-20% at the DNA level.
> Have you done a ANI (or FastANI) analysis of your genomes.

Yes, I did fastANI analysis, ANI of all my strains are between 100 and 77.3 %.

**Comment by limin321** [comment]
> > The documentation states it is only for "within species"
> > This is code for "not very divergent", say 10-20% at the DNA level.
> > Have you done a ANI (or FastANI) analysis of your genomes.
> 
> Yes, I did fastANI analysis, ANI of all my strains are between 100 and 77.3 %.

Hi 
Since my DNA divergent level is between 0-22.7%, a little bit above the threshold 10-20%, will you still recommend me to try Roary? Will the result still be convincing ?
Thanks a lot.

Best,
limin
