### ISSUE TITLE
Roary Unable to Install on Remote Linux Server with SLURM manager

### ISSUE THREAD

**Issue by callaband** [sanger-pathogens/Roary#558]
Attempted to install roary on remote linux server with grid (SLURM manager). 

Attempts, Errors, etc.:
conda install roary (into base environment - install just ended without installing after an hour, no error provided)
created new environment and tried again, same thing happened.
conda create -n roary -c bioconda -c conda-forge -c defaults -c r roary (just ended without installing after 20min, no error provided, head node)
tried the above during an interactive session using the SLURM manager (compute node), no improvement.
Then, tried to install from tarball (both 3.12.0 and 3.13.0 attempted). Install did not error and appeared to complete, but roary --h (or any command) resulted in this error:
"Can't locate Bio/Roary/CommandLine/Roary.pm in @INC (@INC contains: /home/user/lib /home/user/perl5/lib/perl5 /home/user/Roary-v3.13.0/lib /home/user/Roary-v3.13.0/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/user/miniconda3/envs/roary/bin/roary line 12. BEGIN failed--compilation aborted at /home/user/miniconda3/envs/roary/bin/roary line 12." Attempted to fix path with export PATH=$CONDA_PREFIX/bin:$PATH, but error remains. 

The system administrator for our set-up also could not get roary to successfully install thus far. 

Ideas/Suggestions?

**Comment by danielarothschild** [comment]
Hi, I am having the same issue!

Did you manage to solve it yet?

**Comment by annabelledamerum** [comment]
Hi,
I never managed to get Roary working with conda, I instead use: 
`sudo apt-get install roary`
And this works.

**Comment by callaband** [comment]
Sys admin finally got successful install using:
`conda create -y -n roary -c defaults -c r -c conda-forge -c bioconda roary=3.13.0`

This issue is now resolved for me.

**Comment by liuqian666** [comment]
> Sys admin finally got successful install using: `conda create -y -n roary -c defaults -c r -c conda-forge -c bioconda roary=3.13.0`
> 
> This issue is now resolved for me.

It worked for me!
Thanks!
