### ISSUE TITLE
core_gene_alignment.newick

### ISSUE THREAD

**Issue by valery-shap** [sanger-pathogens/Roary#570]
Hello,

I have this file in the output folder. But there is no description of it in tutorial.
How was it produced? 
core_gene_alignment.aln + FastTree?

Best regards,
Valery

**Comment by zzzapperant** [comment]
As mentioned in the tutorial(http://sanger-pathogens.github.io/Roary/), you can use `FastTree –nt –gtr core_gene_alignment.aln > my_tree.newick`
