### ISSUE TITLE
Roary not working

### ISSUE THREAD

**Issue by KFWins2022** [sanger-pathogens/Roary#583]
Hey! I was able to get roary to respond to the command: 
roary --help

I downloaded the program in mamba as well as kracken after creating a conda environment.  I tried just doing something simple and this was the response I got (and the code that created that response):

roary -f output -e -mafft  Bio1.fsa.gff Bio2.fsa.gff Bio3.fsa.gff Bio8.fsa.gff Bio9.fsa.gff Bio10.fsa.gff Bio11.fsa.gff Bio12.fsa.gff Bio15.fsa.gff Bio16.fsa.gff

The response
MSG: ##feature-ontology header tag parsing unimplemented (repeated 10 times) followed by:
---------------------------------------------------
Use of uninitialized value in require at /home/user/miniconda3/envs/pga/lib/perl5/site_perl/5.22.0/Bio/Roary/CommandLine/RoaryPostAnalysis.pm line 10.
Can't locate File/Find/Rule.pm in @INC (you may need to install the File::Find::Rule module) (@INC contains:  /home/user/Desktop/gff/output/lib /home/userminiconda3/envs/pangenome/lib/perl5/site_perl/5.22.0/ /home/user/miniconda3/envs/pga/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi /home/user/miniconda3/envs/pga/lib/perl5/site_perl/5.22.0 /home/user/miniconda3/envs/pga/lib/perl5/5.22.0/x86_64-linux-thread-multi /home/user/miniconda3/envs/pga/lib/perl5/5.22.0 .) at /home/user/miniconda3/envs/pga/lib/perl5/site_perl/5.22.0/Bio/Roary/CommandLine/RoaryPostAnalysis.pm line 10.
BEGIN failed--compilation aborted at /home/userminiconda3/envs/pga/lib/perl5/site_perl/5.22.0/Bio/Roary/CommandLine/RoaryPostAnalysis.pm line 10.
Compilation failed in require at /home/user/miniconda3/envs/pga/bin/pan_genome_post_analysis line 12.
BEGIN failed--compilation aborted at /home/user/miniconda3/envs/pga/bin/pan_genome_post_analysis line 12.
(pga) roary --help
Use of uninitialized value in require at /home/user/miniconda3/envs/pga/lib/perl5/5.22.0/x86_64-linux-thread-multi/Encode.pm line 59.

I've been trying to get this to work for about two days and I have no idea what is wrong.  I generated the gff files with bakta not prokka, if that is the issue please let me know.

**Comment by KFWins2022** [comment]
So it turns out there is a conflict in package version for roary vs. everyone else. 

I am going to install (within that environment) the required versions and see if that fixes the issue.  Is there a way to update the dependencies within roary and other programs.  I've run conda update --all which hasn't fixed the issue at all.

**Comment by andrewjpage** [comment]
I have seen this error recently but I cant replicate it unfortunately.  I can see the version of Perl you are using is very old (released in 2015) so my guess is that your dependancy issues are related to this in some way. I just tried mamba with roary on a fresh ubuntu 18.04 LTS and it worked fine (perl 5.26). 

If you are running ubuntu, just run 'sudo apt-get install roary' as it is a more robust installation method.

**Comment by ldipotetjob** [comment]
[using GFF3 files generated by Bakta with roary](https://github.com/sanger-pathogens/Roary/issues/598) it is the same issue. I tested the same roary implementation with gff generated by prokka with **no problem**  the same implementation with gff generated with bakta and we have the issue(**warning**) and the result is different . So what I trusted with my test is the reason of the issue: I generated the gff files with bakta not prokka

**Comment by padafa** [comment]
Yes, if you use the --compliance parameter with Bakta, you will see the same message in Roary, and the run will abort. If you don't use the --compliance parameter with Bakta, Roary still displays the same warning but continues to build the pangenome. The number of genes in each category remains approximately the same compared to Prokka. My question is: how significant is this warning message?

**Comment by ldipotetjob** [comment]
We are not using --compliance parameter, roary never abort but doesn't work.

**Comment by indexofire** [comment]
concate your gff3 and fna files and add a #FASTA line between them. roary will finish the job.
