### ISSUE TITLE
Get a wrong core_gene_alignment.aln

### ISSUE THREAD

**Issue by augustkx** [sanger-pathogens/Roary#584]
Hi!
 I get a wrong core_gene_alignment.aln output, where there is no sequence, only isolate names:
 
 >iso_485.100

>iso_485.101

>iso_485.102

>iso_485.103

>iso_485.104

I used the command in snakemake pipeline: roary -f roary -v prokka/*/*gff -p 10 -e --mafft -g 700000 -z

I will appreciate it very much if you could give a hint where is wrong. Thanks in advance!

**Comment by andrewjpage** [comment]
What happens if you run the command outside of snakemake and put all the assemblies in the same directory? I can see your command is incorrect, mixing options at the end after the input files.   Try just running:
roary *.gff 
directly on the command line as a test.

**Comment by augustkx** [comment]
Hi, thanks for the reply.
Will` roary *.gff ` result in core_gene_alignment.aln? I need that file.

Outside of snakemake, it gives the right file, even if I didn't put all the assemblies in the same directory.

**Comment by augustkx** [comment]
roary *.gff
also tried, the same errors
